includes/functions-ur-core.php
It seems this if-else condition seems to be true
https://github.com/wpeverest/user-registration/blob/master/includes/class-ur-emailer.php#L90
When we do `return true` here https://github.com/wpeverest/user-registration/blob/master/includes/functions-ur-core.php#L775
Hence it seems whether the return value it true or -1, this condition seems to be triggered and although the user is successfully registered, the user gets the denied message
=> User registration denied message for successful login too

includes/class-ur-install.php
Lock the install routine via a transient to prohibit race conditions due to firing on init hook
=> lock install routine to only allow for one execution

includes/admin/class-ur-admin-profile.php, includes/frontend/class-ur-frontend-form-handler.php, includes/functions-ur-template.php
This PR utilizes postmeta instead of usermeta to store field key and label for for each form. Additionally, deleted form fields are now not rendered in user profile.
=> Update postmeta instead of usermeta

includes/abstracts/abstract-ur-form-field.php, includes/admin/class-ur-admin-profile.php, includes/frontend/class-ur-frontend-form-handler.php, includes/functions-ur-template.php
Previously data were saved in format like `0__Radio1` to retrieve deleted fields value. But since we are treating deleted fields not to display in user profile this values are now stored like `Radio1`. This scenerio is for radio and select fields which were changed as no need to save key and value pairs in usermeta :)
=> Refactor - How meta values are stored in usermeta

includes/admin/class-ur-admin-profile.php, includes/class-ur-form-handler.php, includes/frontend/class-ur-frontend-form-handler.php, includes/functions-ur-template.php
Previously, `serialize()` function was used resulting in double serialization because wordpress automatically serializes an array.
=> Update/checkbox refactor #26

includes/class-ur-install.php, includes/class-ur-post-types.php, includes/functions-ur-core.php
All updates between versions are ran. So if you update from 1.0 to 1.3, all functions in-between, including 1.2 one, will be ran too. Additionally this PR fixes more stuffs like dropping tables in multisite upon plugin uninstallation and PHPCS fixes.
CC @rabinstha @sanzeeb3
=> Refactor - Install scripts to run updates callback per version

includes/functions-ur-template.php, includes/shortcodes/class-ur-shortcode-login.php
With js code in use, due the theme it may be too heavy and takes a while to render the JS to work. So removed the js and `template_redirect` hook instead is used.
=> Remove js code and redirect using template_redirect hook

includes/functions-ur-template.php
Previously, if the user is already logged in and upon registration page this message was shown:
> You are currently logged in as {username}. Logout? 
It would be appropriate to redirect users to the redirect url set after registration in the settings.
=> Redirect users to the redirect url set in settings on registration page

includes/shortcodes/class-ur-shortcode-my-account.php
Problem tackled:
When a user, especially admin who is not registered through a form tries to access his/her profile then it throws a json_decode error. This occurs because the user profile uses the same registration form which user used while registering. But in this case, when admin is not registered through the form, it will not find it and thus send no data in JSON. 
Solution:
Extended the condition to check if the form data is empty to cover the rest of the block. This way, if form data is empty then no other code will run and I added an else statement where it will display "No profile found".
=> Fix: Json_decode error on user profile.

includes/functions-ur-page.php
1. First Login to see Logout menu.
2. After that Log out.
3. Check if Logout menu is removed.
> This issue was reported by users. It seems they have no menu setup, which creates the $items variable not to be an array. 
Fixed the issue by adding a condition to check if the $items variable is an array.
=> Fix - Menu Items invalid arguments

includes/admin/class-ur-admin-status.php
Redirected back to log status page after deleting selected log.
1. Delete log status.
2. And reload the same page.
3. Previously it used to delete the log again and again on reload.
> This PR fixes the issue of the log being deleted again on reload after deleting one log.
=> Fix - Log delete on reload

includes/shortcodes/class-ur-shortcode-my-account.php, templates/myaccount/form-edit-profile.php
Hook added to filter form data in profile details page.
This PR fixes the issue with billing_country field not displaying in profile details page.
=> Profile details field hook

includes/functions-ur-template.php
Simply escapes the attributes which caused misbehaved rendering of the form in case of checkbox. Although denying escape characters would be desirable in the long run, for product health, this will have to do for the time being.
Closes #180 
1. Uses ```esc_attr()``` on data-value and value attributes
Utilized an edge case ```""Hello">```, which would make the form break, along with the value attribute for the field.
&nbsp;
**Before**
&nbsp;
**After**
=> Correcting misbehaving data attrib and value fields for checkbox

includes/admin/class-ur-admin-notices.php
The notice displayed in the user registration form builder was disabled by adding the hide_unrelated_notices function to the in_admin_header action.
1. Install a plugin that displays a license activation notice.
2. Go to the user registration form builder. No notice will be displayed.
> Fix - Removed notice from form builder.
=> Removed notice from form builder

assets/js/frontend/password-strength-meter.js, assets/js/frontend/user-registration.js, includes/shortcodes/class-ur-shortcode-my-account.php, templates/myaccount/form-edit-password.php
Fixes password strength enqueue for frontend edit password option. Also includes frontend validation, and prevention of submit button.
1. Enable password strength from the form builder general settings.
2. Navigate to a user's dashboard, and click on "Edit password"
3. Observe the new functionality, as well as password strength appearing.
> Fix- Enqueue password strength
=> Fix- Enqueue password strength

assets/js/admin/admin.js
Previously, regardless of the option chosen during down-scaling a multi column row of fields, it'd default to the first column, thereby erasing the effort made in trying to get back to the previous state. This PR seeks to make sure that as much as possible, the multi column fields are upheld. Moving forward, the 3 -> 2 transition means the lost row's fields are redistributed between 1st and 2nd row.
Closes # .
1. Navigate to the form builder.
2. Try down-scaling a 3 columns row to 2 columns.
3. Observe that the 3rd (lost column) has its field elements redistributed.
> Fix - Section Division function now correctly redistributes columns.
=> Fix - Section Division function now correctly redistributes columns

assets/js/admin/admin.js, includes/admin/class-ur-admin-assets.php
This PR intends to alert the user that their field is going to be deleted. As deleted fields' meta id's are irrevocably gone, adding this minor notice might help reduce potentially unintentional field deletion attempts. A popup prompt now appears, and deletion only proceeds if agreed to the prompt.
1. Navigate to the form builder.
2. Click on the trash icon next to any given field.
3. Observe that a popup prompt now appears, and deletion only proceeds if agreed to the prompt.
> Enhance - Popup field for deletion.
> Added a few desirable and common i18n phrases.
=> Enhance - Popup field for deletion.

assets/js/admin/admin.js, includes/admin/class-ur-admin-menus.php
This PR intends to add a quality of life feature for users to be able to click out to lose focus, and have the edit-state revert back.
1. Navigate to the form builder.
2. Click on the edit button.
3. Make changes, and click to lose focus. The state should now revert back to the one that was present.
> Enhance - now allows clicking out of form name edit inputbox.
=> Enhance - now allows clicking out of form name edit inputbox

includes/admin/class-ur-admin.php
The bug was in how we were storing the `user_registration_users_listing_viewed` DateTime information. We were storing the `user_registration_users_listing_viewed` in 12-hour format whereas the WordPress stores the `user_registered` in 24-hour format.
So, that's why we're getting new users' registration count even after the page refresh because we were comparing 12-hour DateTime format with 24-hour DateTime format. I have changed the `user_registration_users_listing_viewed` to 24-hour DateTime format.
Closes #227 .
1. Check out the `fix/227` branch.
2. Check whether the new user registration notifications are removed or not.
> Fix: Display of new users count even after the all users page refresh.
=> Fix: Display of new users count even after the all users page refresh

assets/js/frontend/user-registration.js, includes/abstracts/abstract-ur-form-field.php, includes/frontend/class-ur-frontend-form-handler.php
Invalid Invite code without throwing an error user can register and Even Invite code is required '*" sign in red color is not showing this needs to be fixed by this PR.
Dependency: https://github.com/wpeverest/user-registration-invite-codes/pull/5
1. Invalid Invite code without throwing an error user can register.
2. Even Invite code is required '*" sign in red color is not showing.
> Fix - Invalid invite code not validate and required sign not showing.
=> Fix - Invalid invite code not validate and required sign not showing.

includes/admin/class-ur-admin-user-manager.php, includes/class-ur-user-approval.php
Previously when a user registered and approved into the site with other user registration plugins, tries to reset password through our login form, an admin approval still pending message was thrown. This PR purposes a solution to this issue.
1. Register a user into the system with other user registration plugins.
2. Try to reset that user's password through our login form.
3. An admin approval still pending message thrown previously will not be seen and the reset password email is sent.
> Fix - Reset password error for other plugins registered users.
=> Fix - Reset password error for other plugins registered users

assets/js/admin/admin.js
1. Create a form
2. Add some fields and make them required
3. Now try to toggle the `Hide Label` option of those fields
You should see that the red asterisk gets removed and doesn't get restored when you change the `Hide Label` option to **No**.
This PR fixes the above issue.
1. Switch to this branch and see if the issue still exist or not
> Fix - Required option and Hide Label option conflict
=> Fix - Required option and Hide Label option conflict

assets/js/admin/admin.js
This PR fixes an issue with form builder. You can't scroll while dragging fields in the form builder.
1. Go to the form builder
2. Add a lot of fields to make scrollbar appear
3. Now drag a new field and try to drag it down the form. The form should auto-scroll.
> Fix - Cannot auto-scroll while dragging fields in the form builder
=> Fix - Cannot auto-scroll while dragging fields in the form builder

includes/shortcodes/class-ur-shortcode-login.php, includes/shortcodes/class-ur-shortcode-my-account.php
Previously, Recaptcha script was loaded in lost password page even if the Recaptcha verification is not needed in the lost password page. This PR purpose a fix for this issue.
1. Enable ReCaptcha on the login page.
2. Visit the lost password page and view the source of the page.
3. Try searching for Recaptcha script there.
> Fix - ReCaptcha script loads in lost password page.
=> Fix - ReCaptcha script loads in lost password page

includes/functions-ur-core.php, includes/functions-ur-template.php
Previously following issues were encountered in WooCommerce my account page and checkout page.
1. The profile picture field was not appearing.
2. The max file limit and smartphone format settings were not being rendered in file upload and phone field respectively.
This PR pose fixes for these aforementioned issues.
1. Set max file limit and smartphone format settings in file upload and phone field respectively and sync them with WooCommerce.
2. Now test the file limit and smartphone format functionality of the file upload and profile picture field respectively in both WooCommerce checkout and my account page.
> Dev - User registration fields sync with woocommerce.
=> Dev - User registration fields sync with woocommerce

assets/js/frontend/user-registration.js
When the form is submitted, the submit button is disabled during ajax submission, and when the user fails to verify ReCaptcha, since the submit button is remained disabled, the user cannot submit the form after he verifies the ReCaptcha in next try. This PR resolves the mentioned issue.
1. Enable Recaptcha in a registration form.
2. Try registering a user using the ReCaptcha enabled registration form and fail ReCaptcha in first submit.
3. After failing to verify ReCaptcha, Verify ReCaptcha on the next tries, and click on the submit button. Now the user will be able to click on submit button and the form will be submitted.
> Fix - Disabled submit button on ReCaptcha fail.
=>  Fix - Disabled submit button on ReCaptcha fail 

assets/js/admin/admin.js
This PR fixes an issue with the Country field. When you Unselect All and select some countries then try to save the form, an error is shown saying Select at least 1 country.
1. Switch to this branch and go to the form builder
2. Add a Country field
3. Click on Unselect All button in the Selected Countries option
4. Then select some countries
5. Now try to save the form and see if any error is shown. Also verify in the frontend, whether the selected countries appears or not.
> Fix - Unselect All countries option in Country field
=> Fix - Unselect All countries option in Country field

includes/frontend/class-ur-frontend-form-handler.php
When a required field is hidden in registration form using field visibility addon, then the missing field validation treats the hidden field as missing field and throws field is required error on the frontend. This PR fixes this issue.
1. Hide a required field using field visibility addon.
2. Navigate to the registration form on the frontend and fill-up the form.
3. Check whether or not the field's required message is thrown.
> Fix - Ignore missing field validation based on field visibility settings.
=> Fix - Ignore missing field validation based on field visibility settings

assets/js/frontend/user-registration.js, includes/admin/class-ur-admin-profile.php
This PR resolve two issues are as bellow
1. Date Field value disappear on user update by admin
2. Date Field Format not compatible with woocommerce my-account
1. Create a form with Date Field and then register a user by filling date field.
2. After login test date-field with a different format in woo-commerce myaccount profile page.
3. In Backend Edit User and don't  change the date field and update user. And check whether date field value disappears  or not.
> Fix - Date Field value disappears on user update by admin and woocommerce compatibility.
=> Fix - Date Field value disappears on user update by admin and woocommerce compatibility

assets/js/admin/admin.js, includes/form/views/admin/admin-radio.php, includes/functions-ur-template.php
When the WordPress version is updated from 5.4 to 5.5, then the newly added option values in choice fields like checkbox, radio, select, select2, and multi-select2 were not being updated and reflected in the form builder properly. This PR fixes this issue.
1. Update your system's WordPress version from 5.4 to 5.5.
2. Navigate to the form builder and tweak with the choice fields. Verify whether or not the options in choice field are properly updated and reflected in the form builder.
> Tweak - Choice field option value change and update
=> Tweak - Choice field option value change and update

includes/abstracts/abstract-ur-form-field.php, includes/admin/class-ur-admin-import-export-forms.php, includes/admin/class-ur-admin-menus.php, includes/class-ur-form-handler.php
This PR fixes issues with Import, Export and Duplicating forms.
Depends on this [branch](https://github.com/wpeverest/user-registration-conditional-logic/tree/fix/foreach-error)
1. Activate the Conditional Logic addon
2. Create a form. Add fields and add Html in field descriptions
3. Now try to duplicate, import and export the form. See if everything is working properly.
> Fix - Feature to Import/Export/Duplicate form not working
=> Fix - Feature to Import/Export/Duplicate form not working

assets/js/frontend/password-strength-meter.js, assets/js/frontend/user-registration.js
This PR replaces the older function for password strength to match the new WordPress(5.5) standard. It removes this warning(see screenshot) from the console. 
1. Switch to the Develop branch and try to reset the password. 
2. When you are typing the new password, check the browser console. 
3. You will see the message there.
> Dev - Updated the deprecated password strength function.
=> Dev - Replaced Deprecated function with new one

includes/form/views/admin/admin-date.php, includes/functions-ur-core.php, includes/functions-ur-template.php
This PR adds an option to enter placeholder in the Date field.
1. Create a form and add a Date field
2. Enter placeholder text in the field settings tab
3. Go to frontend and see if the placeholder appears or not. Also, register a user and see if the placeholder is displayed in the Edit Profile section too.
> Enhance - Add placeholder option in the Date field
=> Enhance - Add placeholder option in the Date field

templates/form-registration.php
Dependency PR for https://github.com/wpeverest/user-registration-conditional-logic/pull/11
Follow the steps from https://github.com/wpeverest/user-registration-conditional-logic/pull/11
> Fix - Enable/Disable option of conditional logic not working in wp5.5
=> Fix - Enable/Disable option of conditional logic not working in wp5.5

includes/frontend/class-ur-frontend-form-handler.php
This PR is to resolve the issue that the user was getting a successfully registered email but in system, the user was deleted due to payment validation failed. To resolve this issue I have shifted the email sending hook after payment validation.
1. Enable Payment Gateway and do not add Single_Item field in form.
2. Now register a user and check your email you should not get any email because payment validation fails.
3. Shifting hook may fix this issue but arises other issues as well. Need Extensive Testing here.
> Fix - Send an email after payment validation
=> Fix - Send an email after payment validation

templates/myaccount/form-login.php
If user registration is disabled in Wordpress Settings / General, the sign up link should be hidden on the User Registration login form. This commit adds a check using get_option for users_can_register and only displays the sign up link if registration is open.
1. Under WordPress Settings / General, uncheck "Anyone can register" and the sign up link will disappear from the User Registration login form.
Hide signup link on login form if user registration is disabled in WordPress settings.
=> Hide signup link on login form if user registration is not open

assets/js/admin/admin.js, includes/abstracts/abstract-ur-form-field.php, includes/functions-ur-template.php, templates/myaccount/form-edit-profile.php
This PR fixes the issue: min/max options of the `Number` field not working.
1. Create a form and add a `Number` field
2. Set values for the min/max options
3. Reload the page and see if the values are still there and test it in the frontend
> Fix - Number field min/max options
=> Fix - Number field min/max options

includes/admin/class-ur-admin-notices.php, includes/admin/class-ur-admin-user-list-manager.php
This PR hides unrelated admin notices from the User Registration Settings page and only displays our plugin's important notices.
1. After switching to this branch visit the User Registration Settings page.
2. There you can see only our plugin and its addons notices are shown and all other plugins notices are not displayed.
> Tweak - Hide unrelated admin notices from the settings page.
=> Tweak - Hide unrelated admin notices from settings page

assets/js/frontend/user-registration.js, includes/class-ur-frontend-scripts.php
The changes in this PR will override jquery validate custom validation messages for the number field with translatable messages.
Use translation plugins like wpml and check if you can find the validation messages for the number field and try to translate them in other languages.
> Tweak - Number field validation message override and translatable.
=> Tweak - Number field validation message override and translatable

assets/js/frontend/user-registration.js
After the release of v1.9.0, the hide/show icon in the password field stopped working. This PR fixes this issue.
1. Enable hide/show password setting.
2. Navigate to the registration form in the front end and verify whether or not the hide/show icon in the password field is working properly.
> Fix - Hide/Show password conflict with form re-initialization.
=> Fix - Hide/Show password conflict with form re-initialization

includes/admin/class-ur-admin-export-users.php
This PR fixes the form name with ( - ) dash causes export user not working.
1. Create a form with a form name such as "Application - Form ".
2. Now try to export the user with this form. You will notice that the downloaded file is not in CSV format. This issue is fixed in this PR.
> Fix - Export users fail due to form name with a dash.
=> Fix - Export users fails due to form name with dash.

includes/class-ur-email-confirmation.php, templates/myaccount/form-login.php
This PR fixes fatal error after version 1.9.0 release which is resend verification link click occurs fatal error.
Source: https://wordpress.org/support/topic/resend-verification-error/ 
1. Register user with email confirmation login option.
2. Without email confirmation try to login where you will get a resend verification link.
3. Click on the resend verification link here fatal occurs . This PR must fix this. 
> Fix -  Fatal error while resend verification.
=> Fix -  Fatal error while resend verification.

assets/js/frontend/user-registration.js
The jquery validate automatic scroll to the first error message on the form submission is not working properly. This PR fixes this issue.
1. Without filling any fields submit the registration form having one or more required fields.
2. After clicking the submit button, the screen should be scrolled to the first error message position.
> Fix - Scroll to the first error message on form submit.
=> Fix - Scroll to the first error message on form submit

includes/functions-ur-template.php
Previously, in the choice field like radio, select and checkbox field when the option label is set to 1, 2, 3, 4, 5 then it conflicts with the array indexes ( 0, 1, 2, 3, 4 ) we used to display the options in the chosen field. This PR fixes this issue.
1. Use Radio, Select, and Checkbox field with numeric options like 1, 2, 3, 4, and register user.
2. Navigate to the edit-profile section of my account and see if all the options in the respective choice field are displayed and selected properly.
> Fix - Radio, Select and Checkbox label and array index conflict.
=> Fix - Radio, Select and Checkbox label and array index conflict

includes/frontend/class-ur-frontend.php
When we enable prevent core login there we need to provide a my-account page, so how we can redirect to that myaccount page when trying to visit wp-login.php
But, If we use woocommerce myaccount instead of user-registration-myaccount then it will not redirect.
This PR fixes this issue.
1. In our settings Select Login Page with woocommerce my-account shortcode. 
2. Now visit wp-login.php URL here WordPress will redirect to your login page.
Note: Allows on User Registration and Woocommerce my-account shortcodes.
> Tweak - Prevent core login for woocommerce myaccount shortcode
=> Tweak - Prevent core login for woocommerce shortcode

includes/class-ur-form-handler.php
This PR fixes, Form Duplication and Importing Form resulting empty/blank form. This issue occurs when we use anchor tag<a> tag in the description of any fields OR in HTML fields.  
1. Goto Form Builder in the description add a description with the anchor tag and save the form.
2. Now try to duplicate that form and see the result. All Fields must show.
3. Another way to Test this is to export the form and again try to import the same form. All fields must show.
> Fix - Form Duplication issue with an anchor tag
=> Fix - Form Duplication issue with anchor tag

includes/class-ur-ajax.php, includes/class-ur-form-handler.php, includes/frontend/class-ur-frontend-form-handler.php
Previously when the WYSIWYG field value is updated from the edit profile page, the updated values do not reflect the input value. This PR fixes this issue and tends to sanitize HTML elements entered in the WYSIWYG field.
1. Register a user using the WYSIWYG field.
2. Visit the edit profile page and try to update the WYSIWYG field value.
3. After the update check whether the updated values are correct.
> Fix - WYSIWYG field value save and sanitization in edit-profile.
=> Fix - WYSIWYG field value save and sanitization in edit-profile

includes/functions-ur-page.php
Previously, there was a issue when the user click in disable logout confirmation the confirmation message is showing, PR solve the issue when the user click in disable logout confirmation the confirmation message is not showing.
1.Go to Settings > General > My account Section
2.Check the Disable logout confirmation option.
3.Now go to my account page and click on the Logout endpoint. You should be directly logged out.
4.Now uncheck the option
5.Try to logout again. Logout confirmation message should show up.
> Issue- Option to disable logout confirmation
=> Fix - Disable logout confirmation issue with logout endpoint menu

assets/js/frontend/password-strength-meter.js, includes/functions-ur-page.php, templates/myaccount/form-reset-password.php
Previously, there was no weakness validation in password reset field. This  PR provides functionality to check the weakness of password.
1.Click on the Lost password using the my account page.
2.Enter the email to receive the link password reset page
3.Chek your email and click on the link. 
> Enhance-password strength meter in reset
=> Enhance - Password strength meter in reset

assets/js/frontend/user-registration-form-validator.js
Previously when separate login and registration form shortcode used on the same page, then if the page is set as default my account page, then when we try to reset the password then the reset button doesn't work. This PR fixes this issue.
1. Use separate login and registration shortcodes on the same page and set this page as default my account page from settings.
2. Navigate to the page and click on lost password.
3. When the lost password page appears, verify whether or not the reset button is working.
> Fix - Reset password button not working
=> Fix - Reset password button not working

templates/myaccount/form-edit-profile.php
Previously when hide label was enabled it only worked on registration form but not in edit profile section of My Account. This PR fixes this issue
1. Navigate to the form builder. Select on any field and in the field options section enable hide label option.
2. Navigate to the registration form and the label of a specific field will be hidden by default.
3. Now navigate to the edit profile section of my account and see if the label is hidden there as well.
> Fix - Hide label in edit profile.
=> Fix - Hide label in edit profile

includes/class-ur-form-handler.php, templates/myaccount/form-reset-password.php
When we try to reset the password using 'forgot/lost your password?' the same old password is accepted without any notice as well as in the change password of my Account section. 
1. Navigate to my Account section and navigate to forgot/lost your password?.
2. Now you are asked to enter your username/email and click on reset password. 
3. Now you will receive a password reset email in your registered email address and when you click on the click here link.
4. Now Enter new password page appears and when you try to enter the same old password as a new password error message appears your new password must not be the same as the old password.
> Fix - Reset password currently accepts same old password.
=> Fix- Reset password currently accepts same old password

includes/functions-ur-template.php, templates/form-registration.php
In this PR, a reset button is added in UR form in frontend .Which clear the form to set the default values
1. Navigate to User registration Form builder  Form Settings > Extras Setting > Enable Reset Button
2. Fill the UR Form with default values.
3. Click the reset button, the confirmation dialog box will appear to clear the values click Yes and to cancel click in the cancel 
button.
> Enhance - Reset Button in UR Form
=> Enhance - Reset Button in UR Form

includes/abstracts/abstract-ur-form-field.php, templates/myaccount/form-edit-profile.php
Previously, There were no option to use range as a payment slider for payment method. This PR provides an option to use range as a payment slider.
1. Navigate to the form builder and drag and drop the range field.
2. In the Advance setting of field options of range field there will be option labelled as enable payment slider , enable the option.
3. Navigate to the registration form and verify whether range field working as payment slider or not.
4.  Also check if range is used as payment slider it will not visible in edit profile.
https://github.com/wpeverest/user-registration-advanced-fields/pull/23
https://github.com/wpeverest/user-registration-stripe/pull/8
https://github.com/wpeverest/user-registration-payments/pull/8
> Enhance - Payment slider in range field
=> Enhance - Payment slider  in range field

templates/myaccount/form-edit-profile.php
Previously, when the users Translate the fields option (like checkbox, radio, select) in any other languages using polylang in the edit profile the string changes will not appear. This PR solve this issue
1.  Navigate to the form builder and drag and drop the checkbox field.
2.  Install the Polylang Plugin and translate the string like( first choice).
3. Now, check whether the string is translated or not in edit profile.
> Fix - String translation in edit profile
=> Fix - String translation in edit profile

assets/js/admin/gutenberg/form-block.build.js, assets/js/admin/gutenberg/form-block.js, includes/class-ur-form-block.php, includes/functions-ur-core.php, includes/functions-ur-template.php
Previously when we use Gutenberg block shortcode for my account page the profile picture field is visible in the edit profile of my account. This PR will fix this issue.
1. First Navigate to pages and add a new page then add a block ie (+) sign and search for user registration.
2. then choose the log-in form option and select My Account shortcode then publish the page.
3. then navigate to User Registration settings then navigate to my account section of the General tab.
4. then select my account page which you have created using Gutenberg in step 1.
5. then drag and drop the profile picture field in the form builder and save the form.
6. then navigate to edit profile of my account dashboard and see if the profile picture field is visible or not.
> Fix - Profile picture field visible in …
=> Fix - Profile picture field visible in edit-profile when gutenberg myaccount shortcode used

assets/js/admin/form-builder.js, includes/form/settings/class-ur-setting-checkbox.php, includes/form/settings/class-ur-setting-country.php, includes/form/settings/class-ur-setting-date.php, includes/form/settings/class-ur-setting-description.php, includes/form/settings/class-ur-setting-display_name.php, includes/form/settings/class-ur-setting-email.php, includes/form/settings/class-ur-setting-first_name.php, includes/form/settings/class-ur-setting-last_name.php, includes/form/settings/class-ur-setting-nickname.php, includes/form/settings/class-ur-setting-number.php, includes/form/settings/class-ur-setting-password.php, includes/form/settings/class-ur-setting-radio.php, includes/form/settings/class-ur-setting-select.php, includes/form/settings/class-ur-setting-text.php, includes/form/settings/class-ur-setting-textarea.php, includes/form/settings/class-ur-setting-user_confirm_email.php, includes/form/settings/class-ur-setting-user_confirm_password.php, includes/form/settings/class-ur-setting-user_email.php, includes/form/settings/class-ur-setting-user_login.php, includes/form/settings/class-ur-setting-user_pass.php, includes/form/settings/class-ur-setting-user_url.php
Query string allows you to append information with a given URL. You just have to append the parameter and it automatically populates the related field. This PR will allow users to pass multiple variables as a parameter with value and use a single form of varieties of events of creation.
1. Navigate to the Form Builder.
2. Select a particular field and navigate to field options.
3. Go to the Advanced section and make **allow fields to be dynamically populated** as yes. and give the parameter name for that field.
4. Create any post or page with extra parameters as field values like param1=value1&param2=value2.
5. In this way, passing values to various pages or posts as a parameter for the same form can be used.
>  Hooks for custom advance setting.
=> UR-100 Dev - Hooks for custom advance setting

includes/class-ur-user-approval.php
Previously when a user is registered through the email confirmation option and tries to login with his unverified account, then a Resend Verification error message is shown to him, and when clicked he is sent a verification email which was working properly in case of normal login process but was not working if login ajax was enabled. This PR fixes this issue.
1. First of all check to verify if a verification email is being sent in case of normal login submission.
2. Now enable ajax login and verify if the above-mentioned issue is solved or not.
> Fix - Resend verification not working when ajax login is enabled.
=> UR-189 Fix - Resend verification not working when ajax login is enabled

includes/class-ur-ajax.php, includes/class-ur-form-handler.php, templates/myaccount/form-edit-profile.php
When removing and saving changes in the edit profile, the old image is still appearing i.e was not removed completely, and also users were unable to update new images due to wrong escaping used. This PR fixes these issues.
1. Verify if profile picture remove, save and update are working properly on the edit profile page.
> Fix - Profile picture remove, update and save on the edit profile page.
=> UR-205 Fix - Profile picture remove, update and save on the edit profile page

templates/myaccount/form-edit-profile.php
Previously we do not have hooks for changing the name of the save button and profile details heading in the edit profile. This  PR will introduce a hook for both.
1. Add filter named **user_registation_profile_detail_title** and **user_registration_profile_update_btn** in the current active themes of your site and verify if it's working or not.
>Dev -Hooks for save btn in profile details.
=> Dev -Hooks for save btn in profile details

includes/functions-ur-core.php
Previously when the ReCaptcha v2 script was localized using the `wp_localize_script()` function, it was not being localized in Twenty Twenty Two theme cause now script localization outside of default enqueue script hooks are not supported, so ReCaptcha was not loaded on the user's form. This PR solves this issue.
1. Activate Twenty Twenty Two Theme.
2. Enable v2 ReCaptcha on a form and visit the form, Verify if ReCaptcha is working properly there.
3. Verify if ReCaptcha is working in other default themes as well and on themes of your preferences.
> Fix - Recaptcha script localization.
=> Fix - Recaptcha script localization

assets/js/frontend/user-registration.js, includes/admin/class-ur-admin-settings.php, includes/class-ur-ajax.php, includes/class-ur-form-handler.php, templates/form-registration.php
After the release of v2.1.4, we have found multiple issues related to wrong phpcs fixes. The issues are
1. Go to Settings-> Email and open any email, click on save changes, the email contents will appear inline stripping html tags.
2. Conditional logic in fields not working.
3. Multi select2 value not being saved in edit profile.
4. Multiple profiles updated email to admin
This PR fixes these issues.
1. Go to Settings-> Email and open any email, click on save changes, verify if email contents appear inline or not.
2. Check if conditional logic in fields is working properly.
3. Check if multi select2 values are being saved in the edit profile.
4. Check if multiple emails are being received or not when the user updates profile details.
5. Check if all field values are being saved or not in …
=> Fix - Issues due to wrong phpcs fix

includes/class-ur-form-handler.php
Previously, When field visibility is set to read only in user email and the submission type is POST then when the user used to update the profile details the email field value. This PR will resolve these issues.
1. First Navigate to form builder and go to field option of user email and enable field visibility read-only to profile details. 
2. then navigate user registration settings and disable ajax submission on edit profile.
3. then login and update the profile and verify whether it is working as expected or not.
> Fix - Email field empty when field visibility is readonly after profile update.
=> UR-239 Fix - Email field empty when field visibility is readonly after profile update

includes/admin/settings/class-ur-settings-email.php
Previously we do not have a way to show active/inactive status on the User Registration -> Settings -> Emails table. This PR provides this feature.
1. Navigate to User Registration -> Settings -> Emails.
2. Active or Inactive status will be shown for each table in the status column.
> Enhance - Active status on emails settings.
=> UR-265 Enhance - Active status on emails settings

includes/admin/class-ur-admin-user-list-manager.php, includes/admin/class-ur-admin-user-manager.php
When the **user login option** is set to **Email confirmation after Registration** and a user register via the registration form and somehow the user didn't receive an email confirmation. If an admin tries to approve the user manually from the wp users table then it works but if we visit the user profile and try to change the approval status to approved and save it. It defaults back to pending. This PR will fix this issue.
1. Navigate to user registration form builder and then form setting.
2. In the general tab, select the user login option as **Email confirmation after registration** and update the form.
3. then do register via the registration form and then navigate to the wp users table and visit the user profile then change the approval status and save it.
4. verify whether it is …
=> UR-247 Fix- Admin approval keeps switching to pending from user profile

.eslintrc, assets/js/admin/form-builder.js, includes/admin/class-ur-admin-assets.php
Previously there was no keyboard shortcut in the form builder to preview and view users for that form. This PR enhances this feature.
1. Go to the form builder.
2. Ctrl + P: Open the form preview in a new browser tab.
3. Ctrl + U: View users for the form in a new browser tab.
> Enhance - Keyboard shortcut in the form builder.
=> UR-274 Enhance - Keyboard shortcut in form builder

includes/admin/views/html-notice-key-activated.php, templates/myaccount/form-edit-profile.php
Previously when we update the profile by making changes to other details but not the profile details themselves then after the update the profile picture is removed. This PR fixes this issue.
1. Verify the above changes.
> Fix - Profile Picture removed when profile updated.
=> UR-335 Fix - Profile Picture removed when profile updated

includes/class-ur-ajax.php, includes/class-ur-form-handler.php
Previously for some users the file upload directory `uploads/user_registration_uploads` was not created for some reason and when they tried to upload a file the upload path permission denied error appeared due to the non-existent upload file directory. This PR tries to fix this issue by checking if the directory exists and if not then creates one before uploading a file.
1. Replicate the issue for the profile picture and file upload field.
2. Switch to this branch and check if the issue is resolved.
> Fix - File upload path permission denied due to non-existent file upload directory.
=> UR-352 Fix - File upload path permission denied due to non-existent file upload directory.

includes/functions-ur-core.php
This change is related to Content Restriction. In content restriction  *During* access rule, the users registered on end date were not getting access to the content. This pull request solves it.
Closes # .
1. Create a *During* access rule with end date set to today's date.
2. Register a new user and check if the new user can access the restricted content.
=> Fix - Date Range not accepting end date

includes/class-ur-ajax.php, includes/class-ur-form-handler.php, includes/functions-ur-core.php
The custom code that was used to increment file name was not working for some users so need to use the WordPress-provided `wp_unique_filename` function to make it more reliable.
1. Check if duplicate files are renamed correctly.
> Tweak - Replace incremental file name function with WordPress default.
=> UR-392 Tweak - Replace incremental file name function with wordpress default

templates/myaccount/form-edit-profile.php
I uploaded the file using file upload and deleted the file from the media library. Still getting text.png file or error on file upload (edit profile). For more clarification, check this screenshot [Screenshot](https://prnt.sc/r94Ru8rDC3ZJ)
This PR fixes this issue.
1. Do the testing according to the issue described and check if no error is thrown and verify other files can be uploaded.
> Fix - Error thrown when uploaded file is not found in upload directory.
=> UR-373 Fix - Error thrown when uploaded file is not found in upload directory

includes/functions-ur-template.php
When registration form is embed using our gutenberg block then the following code is not firing when user is logged in. i.e Must redirect to google when user tries to visit registration page while logged into the system.
`add_filter( 'user_registration_redirect_from_registration_page', function( $redirect_url, $current_user ) {
$redirect_url = 'https://www.google.com';
return $redirect_url;
}, 10, 2 );`
1. Switch to this branch and check if issue is resolved.
> Fix - Redirection after registration not working with block.
=> UR-390 Fix - Redirection after registration not working with block

includes/functions-ur-template.php
This is a dependency PR that changes the order of display of Required icon(<code>*</code>) and Tooltip icon in the frontend field labels.
1. Test if any error occurs due to the changes.
> Tweak - Frontend Tooltip Dependency
=> Fix - Show Tooltip after required icon

includes/form/class-ur-form-field-checkbox.php, includes/form/class-ur-form-field-country.php, includes/form/class-ur-form-field-date.php, includes/form/class-ur-form-field-description.php, includes/form/class-ur-form-field-display-name.php, includes/form/class-ur-form-field-email.php, includes/form/class-ur-form-field-first-name.php, includes/form/class-ur-form-field-last-name.php, includes/form/class-ur-form-field-nickname.php, includes/form/class-ur-form-field-number.php, includes/form/class-ur-form-field-password.php, includes/form/class-ur-form-field-privacy-policy.php, includes/form/class-ur-form-field-radio.php, includes/form/class-ur-form-field-select.php, includes/form/class-ur-form-field-text.php, includes/form/class-ur-form-field-textarea.php, includes/form/class-ur-form-field-user-confirm-email.php, includes/form/class-ur-form-field-user-confirm-password.php, includes/form/class-ur-form-field-user-email.php, includes/form/class-ur-form-field-user-login.php, includes/form/class-ur-form-field-user-pass.php, includes/form/class-ur-form-field-user-url.php
Previously, When we apply conditional logic to any required field and in frontend if we bypass the  client side required validation from browser console. then it was submitting the form instead server side validation. This issue has been fixed in this PR.
1. Create a form with required field and conditional logic enabled.
2. Goto frontend Form Show that required field and goto inspect element and remove the **required="required"**.
3. Submit the form without entering any value in that field. It should validate from server side.
>  Fix - Required field not working when conditional logic enabled.
=> UR-378 Fix - Required field not working when conditional logic enabled.

uninstall.php
Previously when uninstall option enabled and plugin deleted then it only deleted the global settings and unassigned the user but it was not deleting the forms from post table.
1. Enable uninstall option from Misc Tab of Settings.
2. Goto Plugin Section and deactivate and delete the user registration plugin.
3. Again Install the user registration plugin and check whether all settings and forms are deleted or not.
> Fix - Delete forms while uninstall plugin.
=> UR-408 Fix - Delete forms while uninstall plugin

includes/admin/class-ur-admin-import-export-forms.php
Previously, When the form name has a special character and when we try to export the form. the form is not exporting in JSON format. This PR fixes this issue
1. Create a form name with a special character like(&#).
2. Go to Settings>Import/Export.
3. Export the form and verify it is working or not.
> Fix - Form export issue when the form name has a special character.
=> Fix - Form export issue when the form name has a special character.

includes/admin/settings/emails/class-ur-settings-email-confirmation.php
Previously, When User Approval and Login Option is set to Auto Approval After Email Confirmation then Verification link was plain text. This PR will fix this issues.
1. Navigate to Form builder then form settings.
2. then set User Approval and Login option to Auto Approval After Email Confirmation and update the form.
3.  then make registration and verify whether email verification link is sent as link or not.
> Fix - Email verification plain text to link.
=> UR-501 Fix - Email verification plain text to link

assets/js/admin/form-builder.js
If the form builder has fields, dragging and dropping the new field always append to the end of the fields list. If I wanted to drop it between the fields then it is not possible. This Pr fixes this issue.
1. Create a new form that has some fields.
2. Click and drag the new field and try to place it between the area of the field's droppable zone.
3. verify, whether the new dragged field is moved to the end of the list or not.
> Fix - Field not appended in the droppable zone.
=> Fix - Field not appended in the droppable zone

includes/admin/class-ur-admin-export-users.php
Previously, When the form name has special character and when you try to export users then it will give error this page isn't working. This PR will this issue.
1. Create a form name with all possible special characters in it.
2. then Go to Settings > Import/Export.
3. then try to exports users of this form name and verify whether it is working or not.
> Fix - User export issue when form name has special characters.
=> UR-547 Fix - User export issue when form name has special characters

assets/js/frontend/user-registration.js
Previously, the Show password icon is not working in the Password field. This PR will fix this issue.
1. Navigate to form builder and drag and drop the password field from the extra fields section.
2. then update the form and also make sure that enable hide/show password is enabled from General tab of User registration settings.
3. then verify whether it is working as expected or not.
> Fix - Show Password icon in Password Field.
=> UR-504 Fix - Show Password icon in Password Field

assets/js/admin/form-builder.js, includes/abstracts/abstract-ur-form-field.php
Previously, When the field is dragged and opened all the accordions were kept open. This Pr solves this issue.
1. Goto the form builder.
2. Drag and drop the field.
3. verify whether only the general setting block is open or not.
> Fix - Accordion issue in form builder..
=> Fix - Accordion issue in form builder.

includes/functions-ur-core.php
Previously My Account Page selection notice appears when my account shortcode not exits in selected page, but even though shortcode is exits in the page inside the Gutenberg nested group, columns and reusable block the my account page selection notice was still showing. This issue fixed in the PR.
1. Create My Account Page with our shortcode in combination of nested group, columns and reuasble blocks.
2. Select that page as My Account Page.
3. Check whether My Account selection notice appears or not.
> Fix - Gutenberg compatibility issue with my account.
=> UR-555 Fix - Gutenberg compatibility issue with my account

includes/abstracts/abstract-ur-form-field.php
Previously, there was missing escaping on the general settings fields (like Name, Placeholder and others) of Field Options. And, this PR applies proper escaping for general settings fields field options to prevent XSS attacks.
1. Create a form.
5. Put "autofocus onfocus=alert(/XSS/)// on placeholder option username field.
5. And verify alert popup modal is open or not after clicking on that field.
> Fix - Apply proper escaping for general settings fields to prevent XSS attacks.
=> Fix - Apply proper escaping for general settings fields to prevent XSS attacks.

includes/class-ur-email-confirmation.php, includes/class-ur-emailer.php
Previously, Success Registered Email sent only when manual login or auto-login login option selected but in this release after email confirmation done by user then Successful Registered Email Sent to User.
1. Create a Form with Email Confirmation login option and then register the user.
2. You will receive an email confirmation link in email then click on that link.
3. Once confirmation process passed then user will received successful registered email.
> Enhance - Trigger Successful Registration email after email confirmation done by user.
=> UR-496 Enhance - Trigger Successful Registration email after email confirmation done by user.

includes/admin/class-ur-admin-import-export-forms.php
Previously, When importing the form it shows the message only. This PR enhances view form link in message.
1. Go to global setting  
2. Click the import/export tab and go to import/export form 
3. Import the form and verify the feature is working or not 
> Enhancement - View Form Link After Importing.
=> Enhancement - View Form Link After Importing

includes/class-ur-form-handler.php
Previously, When permalink structure is Plain and when you update the profile details from myaccount page then it is redirected to homepage instead of same page. This PR will fix these issues.
1. First go to Settings>Permalinks then choose Plain and save it.
2. Now go to frontend myaccount page and try to update profile details.
3.  verify whether it is working as expected or not with all possible scenario.
> UR-729 Fix - UR myaccount redirection issue on plain permalink structure
=> UR-729 Fix - UR myaccount redirection issue on plain permalink structure

assets/js/admin/admin.js, assets/js/admin/form-builder.js, includes/admin/class-ur-admin-form-templates.php, includes/admin/views/html-admin-page-form-templates.php, includes/admin/views/html-admin-page-forms.php, includes/functions-ur-page.php
Previously, while clicking on the field option in form builder it was not clickable if  no any field is selected. Now it is clickable even when no field is selected.
1.Go to all forms then 
2.Edit any form
3.Click on Field option tab
> Field option is clickable even when no any field is selected
=> Tweak - Field option should be clickable even when no any field is selected.

assets/js/frontend/ur-login.js, includes/class-ur-form-handler.php, includes/shortcodes/class-ur-shortcode-login.php, includes/shortcodes/class-ur-shortcode-my-account.php
Previously, When Password is reset and  you try to login then if password you entered is incorrect then both password reset message and incorrect password message visible at same time. This PR will this issue.
1. First Go to Login Form and perform lost your password.
2. then After you reset your password and try to login with incorrect password.
3. then verify whether this issue has been fixed or not.
>Fix - Reset and incorrect password message appears at same time.
=> UR-536 Fix - Reset and incorrect password message appears at same time

assets/js/admin/form-builder.js
Previously, When the email content is changed in the builder setting with the email templates addon. The content is not updated.
1. Create a form with an email template addon.
2.  Go to Form Setting > Email templates.
3. Try to change the content and verify the content are updating or not
> Fix - Email content override not working.
=> Fix - Email content override not working.

assets/js/admin/form-builder.js
Previously, User registration field visibility addon setting is not saved in the safari browser. This PR will this issue.
1. Go to the form builder then field option of any field.
2. then try to change the visibility settings of advanced settings and update the form.
3. verify whether it is working properly or not.
> UR-716 Fix - Field Visibility Setting value not saving in safari.
=> UR-716 Fix - Field Visibility Setting value not saving in safari

includes/admin/class-ur-admin-import-export-forms.php, includes/admin/views/html-admin-page-import-export-forms.php
Previously, while exporting or importing form, we were able to import or export only one form at a time. Now this PR enhance the Import/Export functionality, we can choose one or multiple form at a time and can export these form. Also we can import one or multiple form at time.
1. First go to setting > Import/Export Forms tab
2. Try to select multiple forms and Click on Export
3. After Exporting the selected form, Try to import these form file > click on import and see imported form in All Forms
> Tweak - Multiple form import export at a time
=> Tweak - Multiple form import export at a time

assets/js/admin/admin.js, assets/js/admin/settings.js, includes/admin/class-ur-admin-assets.php, includes/admin/settings/class-ur-settings-email.php, includes/class-ur-ajax.php
Previously, In the email notification table, status of email was active and inactive message only. Now this PR is changing the those status by toggle button. These toggle button are functional. We can enable or disable email sent using toggle button. No need go particular configuration to enable or disable the email sent.
Closes # .
1.First go to Settings > Emails tab
2. Now, email status active/inactive message is replace by toggle button
3.Verify toggle button is also working.
> Ur 665 Enhancement - Enable disable email from email list table global email setting
=> UR-665 Enhancement - Enable disable email from email list table global email setting

assets/js/admin/form-builder.js
Previously, When the Min-max option of the Date field is enabled then the Year is not showing in it. This PR Will solve this issue.
1. Enable the min-max option and check whether a year is showing or not while selecting the min-max date.
> Fix - Year not displayed on min max date field option.
=> UR-752 Fix - Year not displayed on min max date field option

assets/js/admin/deactivation-feedback.js
This PR makes the description required if the user has chosen the other option in deactivation popup.
Closes [UR-788](https://themegrill.atlassian.net/browse/UR-788) .
1. Verify if the deactivation form is being submitted with empty description for other option.
> UR-788 Tweak - Make reason required for other option
[UR-788]: https://themegrill.atlassian.net/browse/UR-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UR-788 Tweak - Make reason required for other option

includes/functions-ur-core.php
Previously, When a profile picture is uploaded then the uploaded picture is not recognized by the media library i.e it is not previewable. This PR will fix this issue.
1. Upload the profile picture from the registration form then submit the form and verify whether the uploaded picture is showing in the media library or not.
> Fix - Profile picture not recognized by media library.
=> UR-736 Fix - Profile picture not recognized by media library

assets/js/admin/admin.js, assets/js/admin/form-builder.js
This PR adds a lock for those fields whose setup is not set upped correctly.
1. Edit or Add a form.
2. Do not set up for field stripe, learn dash, and invite code. And check on click on the field -> modal is coming or not.
3. And also check after setup the field's required setup.
> Enhancement - Lock disable field if integration not setup.
=> Enhancement - Lock disable field if integration not setup

includes/admin/class-ur-admin-profile.php
Previously, when click on the date field of extra information of the user in the edit user page, it shows chosen date but when we click on it, it checkout to the default date value field. It is applicable only to those date fields that have default values as YES in the registration form. This PR fixes this issue.
1. Create a registration form with a date field -> set its value to default value as YES from the advanced setting.
2. Try to register one user-> fill in all fields -> change the date field value to another date then submit.
3. Go to users -> edit user-> click on date field -> check if it changed to a default value or not.
> Tweak - Incorrect default date displayed in date field while editing the user
=> Tweak - Incorrect default date displayed in date field while editing the user

assets/js/admin/form-builder.js, assets/js/admin/form-modal.js, includes/abstracts/abstract-ur-field-settings.php, includes/admin/class-ur-admin-form-modal.php, includes/class-ur-emailer.php, includes/class-ur-shortcodes.php, includes/class-ur-smart-tags.php, user-registration.php
This PR is adding a button that gives the list of smart tags in the email content section and also in the customize my account section. With the click of any smart tag, It will be added to the editor.
1. For Email -> Go to setting -> Email -> Configure  || For Customize my account -> Activate customize my account addon -> Go to Setting -> click Customize My Account tab
2. Then click on the Add Smart Tag button, 
3. It will show the list of smart tags and on the click it will be added to editor.
> Enhancement - List of smart tags in email content.
=> Enhancement - List of smart tags in email content

includes/admin/class-ur-admin.php, includes/admin/views/html-notice-php-deprecation.php, includes/class-ur-ajax.php
This PR adds a php deprecation notice shown in the admin panel if the website is running on PHP below version 7.2.
The notice is dismissible and is shown up to 3 times with the interval of one day.
1. Verify if the notice is displayed properly, is dismissible, and is displayed only 3 times.
> Feature - PHP Deprecation notice
=> Feature - PHP Deprecation notice

assets/js/admin/form-builder.js, includes/admin/settings/class-ur-settings-general.php, includes/class-ur-ajax.php
Previously, When captcha keys are not setup properly, then it lets to save the form. This PR will not allow to save the form if captcha keys are not setup and captcha is enabled in the form.
1. setup the captcha form with captcha keys and without keys and verify whether it is working as expected or not. 
> Tweak - Check captcha keys while setting up the captcha for form.
=> Tweak - Check captcha keys while setting up captcha for form

includes/class-ur-ajax.php, includes/class-ur-install.php, includes/functions-ur-core.php, user-registration.php
Previously, the upload folder path and URL were hardcoded where required. It caused issues in cases where the user had used a custom upload location instead of /uploads/ folder. So, In this PR, constants **UR_UPLOAD_PATH** and **UR_UPLOAD_URL** are created and replaced in places where the upload path and URLs were hardcoded.
1. Review the code.
2. Verify that all the upload functionalities are working properly or not.
> UR-929 Refactor - Create global constant for upload dir path and url
=> UR-929 Refactor - Create global constant for upload dir path and url

assets/js/admin/admin.js, assets/js/admin/form-builder.js, includes/admin/class-ur-admin-assets.php
Previously when a user tries to drag already dragged one-time draggable fields that can be used only once in the form then it was only disabled, users were not given any hint that why they are not being able to drag those fields. This PR provides a message when a user tries to drag those fields.
1. Verify the above mentioned fix.
> Enhance - One time draggable field locked message.
=> UR-978 Enhance - One time draggable field locked message

includes/functions-ur-core.php
Previously, if we tried to off the toggle which is by default checked then the toggle would not go off. This PR fixes this issue.
1. Goto Global setting. 
2. Try to check off the toggle which has been checked by default.
3. Try to save and verify.
> Tweak - Allow search engine indexing wont turn off
=> Tweak - Allow search engine indexing wont turn off

assets/js/admin/form-builder.js
Previously the max upload size option in the profile picture field accepted non-numeric, negative, and 0 as values. This Pr fixes this issue. Also in the file upload there was code to handle this, I have removed that code and added in core to handle both addons.
1. Check if the max upload size option accepts non-numeric, negative, and 0 as values. 
> Fix -Max upload size option accepting  non-numeric, negative, and 0 as values
=> UR-946 Fix -Max upload size option accepting  non-numeric, negative, and 0 as values

includes/validation/class-ur-validation.php
When we submit the form by entering 0 in the number field. Then it gives the error Number field is required. This PR this issue.
1. Drag a number field in the form
2. Try to submit the form by entering 0 in the number field.
3. Verify whether the number field required error message is showing or not.
> Fix - Required validation when entering 0 in number field.
=> Fix - Required validation when entering 0 in number field

includes/class-ur-ajax.php, includes/functions-ur-template.php
Previously, When the range field is used as a payment field and Ajax submission is enabled on the profile update then validation error is thrown. This PR will fix this issue.
1. Make the range field as payment field and make sure Ajax submission is enabled on the profile update.
2. Verify whether it is working as expected or not while saving profile details.
> Fix - Validation error when range is used as payment field.
=> Fix - Validation error when range is used as payment field

includes/class-ur-smart-tags.php, includes/frontend/class-ur-frontend-form-handler.php
When the admin approves the user, our plugin sends the approval email according to the default language. If the admin switches the dashboard language using the plugin language switcher and approves the user still, the default email will send instead of translated email. To resolve this issue in this PR we are storing the current language while user registration and also we can map the current language in the field via smart tag.
1. Register an user and check in the database usermeta table where you can see new meta key called **ur_registered_language** 
2. Goto form builder and in input box field in field option select smart tag called Current Language in the default box.
3. check whether current language is set in that field or not.
> Feature - User registered language with smart tag.
=> UR-989 Feature - User registered language with smart tag.

assets/css/user-registration.scss, assets/js/frontend/user-registration-form-validator.js
This PR is adding the input box highlighting feature. If the error message triggers, the input box will be highlighted by red border color; if the input is valid, the input box will be highlighted by green border color. 
1. Create a form and check some field as required.
2. Try to summit without filling and verify if the error comes then the input border will be highlighted as red.
3. Try filling in with valid input and verifying the input border color.
> Tweak - Input box highlighting.
=> Tweak - Input box highlighting

assets/js/admin/ur-setup.js
Previously, When you add a new form and click on scratch and enter any name and cancel the process then the state has been created. This PR fixes this issue.
1. Goto add form.
2. Click on scratch and enter any name
3. Then cancel the pop and verify form is created or not.
> Fix - Add new form and click on scratch and enter any name and cancel the process the form will be created..
=> Fix - Add new form and click on scratch and enter any name and cancel

includes/frontend/class-ur-frontend.php, includes/functions-ur-core.php
Previously, We were using preg match to find shortcode in the post content but by doing that not all editors was compatible such as oxygen editor. This oxygen editor is not saving data in the post content it saves in the post meta table. This PR will make all editors compatible.
1. Enter Shortcode by edit with oxygen builder.
2. Disable Wordpress Default Login.( Prevent core login ) enable this option and select the my account page.
3. Verify whether the Wordpress default login was redirect to myaccount page or not.
> Fix - Make login shortcode compatible with all editors.
=> UR-1083 Fix - Make login shortcode compatible with all editors

includes/functions-ur-page.php
When WPML plugin is not installed and TranslatePress plugin activated then got undefined function error. Issue occurs due to previously we were checking wpml installed or not using has_filter but the same filter was used by the TranslatePress then our plugin detect that wpml is installed and it called icl function which is in the wpml plugin and since wpml plugin is not installed then it throws error. This PR fixes this issue.
1. Install TranslatePress plugin and then translate myaccount page
2. Try to open myaccount page in different language and validate whether you are not getting any error.
> Fix - Conflict with TranslatePress.
=> UR-1121 Fix - Conflict with TranslatePress

includes/functions-ur-page.php
When we request for lost password via different language then Reset Password link in email is valid but when you click on that link it say's invalid key and it will not allow to reset new password. This issue is fixed in this PR.
1. Translate My Account Page and Request for Reset password.
2. You will get reset password link in email.
3. when you click on that link then you should allow to reset new password page.
> Fix - Lost Password not working for translated myaccount page.
=> UR-1116 Fix - Lost Password not working for translated myaccount page.

assets/css/admin.scss, assets/js/admin/form-builder.js, includes/abstracts/abstract-ur-field-settings.php, includes/class-ur-emailer.php, includes/class-ur-smart-tags.php
Previously, We don't have the option to add custom regular expression validation for the field to validate it. The PR will introduce this feature.
1. Go to form builder then advanced settings of field options.
2. Enable Pattern validation and select a predefined regular expression or input a custom regular expression.
3. update the form and verify whether it is working fine or not.
> UR-573 Feature - Pattern validation for input fields.
=> UR-573 Feature - Pattern validation for input fields

assets/js/admin/admin.js, includes/frontend/class-ur-frontend-form-handler.php, includes/functions-ur-core.php
This PR adds a form setting to set hold period before redirecting the user to another page. By default, the hold period is set to 2 seconds.
1.  Without making any changes to the setting, check how many seconds the user is held before redirecting the user.
2. Now, change the setting to any value you like and see if the user is being held for the specified period.
3. Test for cases of Autologin, Redirection after Registration, and Paypal Payment.
> UR-1052 Enhance - Custom hold time before redirection after registration
=> UR-1052 Enhance - Custom hold time before redirection after registration

includes/frontend/class-ur-frontend-form-handler.php, includes/functions-ur-core.php
Previously, When the field is hidden conditionally though hidden field value is submitted while registering the user. This PR will fix this issue. 
1. Go to the form builder and apply conditional logic to the field and update the form.
2. Make registration and verify whether the conditionally hidden field value is submitted or not.
> UR-818 Fix - Submitting issue for conditionally hidden fields.
=> UR-818 Fix - Submitting issue for conditionally hidden fields

includes/abstracts/abstract-ur-form-field.php, templates/myaccount/form-edit-profile.php
This PR provides compatibility for enabling/disabling taking picture from webcam in the profile picture field.
1. Checkout this branch and profile picture enable disable branch in the advanced field and test whether the taking picture from webcam feature is being disabled/enabled properly.
> Dev - Compatibility for enabling/disabling taking picture from the webcam.
=> UR-821 Dev - Compatibility for enabling/disabling taking picture from the webcam.

includes/admin/class-ur-admin-user-list-manager.php, includes/admin/class-ur-admin-user-manager.php
Previously, there was an issue with the counting of pending users. When the pending user was denied, the pending notice still showed the same number of pending users. This PR fixes that and filters pending users properly. Also, a new label '**_Awaiting Email Confirmation'_** is added for users who have not confirmed their email instead of just _**Pending.**_
1. Test the above-mentioned changes with different login options.
2. Make sure that the reported issues are fixed.
> UR-1130 Fix - Incorrect filtering of pending users
=> UR-1130 Fix - Incorrect filtering of pending users

assets/js/admin/settings.js, assets/js/frontend/ur-login.js, assets/js/frontend/user-registration-recaptcha.js, assets/js/frontend/user-registration.js, includes/admin/settings/class-ur-settings-captcha.php, includes/class-ur-ajax.php, includes/class-ur-form-handler.php, includes/class-ur-frontend-scripts.php, includes/functions-ur-core.php
This PR will add Cloudflare Turnstile captcha integration to the captcha setting menu.
1. Go to Settings > Captcha then choose Cloudflare Turnstile.
2. Add Site and Secret Keys then choose theme mode.
3. then save the settings and verify whether it is working properly or not.
Note: For Testing Keys please Refer to the documentation https://developers.cloudflare.com/turnstile/reference/testing/ or create an account for site and secret keys.
> UR-1036 Feature - Cloudflare turnstile captcha integration.
=> UR-1036 Feature - Cloudflare turnstile captcha integration

includes/functions-ur-core.php
This PR fixes a bug due to which the field values for registered users was not being saved.
1. Register a user using any user registration form.
2. Verify if all the input values are being saved.
3. Also verify that the values are being saved during edit profile action.
> UR-1170 Fix - User fields not saving
=> UR-1170 Fix - User fields not saving

templates/form-registration.php
Previously, the redirect URL does not escape properly. This PR solves this issue.
1. Click "Add Form" under the plugin options.
2. Once the form is created, navigate to the form settings, and in the "Redirect URL" field, inject the following payload: javascript:alert(document.domain) and then click "Update Form."
3. Copy the shortcode generated for the form, go to the "Page" tab, create a new page, paste the shortcode, publish the page, and visit it.
4. Now, fill out the form with any dummy data and click "Submit."
5. This will create a new user and trigger the XSS vulnerability.
> Fix - Escaping issue in redirect URL.
=> Fix - Escaping issue in redirect URL.

assets/css/settings.scss, assets/js/admin/settings.js, includes/admin/class-ur-admin-assets.php, includes/admin/class-ur-admin-settings.php, includes/admin/settings/class-ur-settings-captcha.php
This PR introduces a feature that enables testing of the working of all captchas from the captcha settings page.
This feature aims to prevent the issue where the admins would set the captcha incorrectly and get locked out of system due to a captcha error.
1. Input valid and invalid keys in the captcha settings and test the captcha for all available captchas.
2. Check if the feature is handling errors and displaying errors properly.
> UR-870 Enhance - Test captcha from settings
=> UR-870 Enhance - Test captcha from settings

assets/js/admin/settings.js
Previously, when we collapse the sidebar of global settings, the state of sidebar changes when we reload the setting page. This PR fixes this issue. 
1. Go to User Registration > Settings > Collapse.
2. Click on the Collapse button > Click on some link above the Collapse button.
3. Verify whether the sidebar remains collapsed when the page reloads.
> Fix - UR Settings collapsible header issue.
=> UR-1201 Fix - UR Settings collapsible header issue.

.github/sync-file-list.yml, .github/workflows/sync.yml, includes/class-ur-ajax.php, includes/class-ur-form-handler.php, includes/functions-ur-form.php, includes/validation/class-ur-form-validation.php, user-registration.php
This PR merges the two duplicate validation methods for update profile ( AJAX and POST ). 
- https://github.com/wpeverest/user-registration-pro/pull/249
1. Create a form with all possible fields.
2. Play with all the field settings and verify if the invalid submissions are rejected and reported properly.
3. Also test other validations like whitelisting domain, etc.
4. Test with both ajax submission and post submisssion.
> UR-749 Dev - Merge two duplicate methods on form validation
=> UR-749 Dev - Merge two duplicate methods on form validation

assets/js/frontend/user-registration-form-validator.js, includes/functions-ur-template.php
This PR introduces a new feature where users can sync the user registration form field on the wocommerence product page which is used to collect the extra information of the product.
1. User registration woocommerce ( Form validation) -> https://github.com/wpeverest/user-registration-woocommerce/pull/33
2. Conditional logic (Conditional logic compatible) -> https://github.com/wpeverest/user-registration-conditional-logic/pull/32
1. I have mentioned on the card. Please follow the link https://themegrill.atlassian.net/browse/UR-986
>Feature - UR form fields integration on woo commerce product page.
=> Feature - UR form fields integration on woo commerce product page.

assets/js/admin/form-settings.js, includes/admin/class-ur-admin-assets.php, templates/form-registration.php
This PR adds an image uploader module for admin settings.
Also, some hooks have been added to add content before and after field content.
1. This is a compatibility PR for User Registration Conversational Forms. Switch to this branch while testing the addon.
> UR-1200 Feature - Admin image uploader module
=> UR-1200 Feature - Admin image uploader module

includes/class-ur-emailer.php, includes/functions-ur-core.php
In Multisite website when we try to assign user role conditionally it was not working , So this PR fixes this issue.
1. Goto Multisite and Enable Assign user role conditionally.
2. Set Country field in the condition to assign user role.
3. Register new user with the country for assign respected role.
4. Check that user role gets the assign role or not.
> Fix - Assign user role conditionally not working in multisite.
=> UR-1219 Fix - Assign user role conditionally not working in multisite

includes/functions-ur-account.php, includes/functions-ur-template.php
Previously, logout_redirect attribute on my_account shortcode used to work on "page slug" within the site. But now it will also work on external url as well.
1. Go to Edit Page for My Account Page.
2. Enter logout_redirect = "custom_url" within the my_account shortcode . 
3. Check whether it is redirected to entered url on logout through My Account page.
> Enhancement - My account logout redirection to external url.
=> UR-1237 Enhancement - My account logout redirection to external url.

assets/js/frontend/user-registration.js, includes/functions-ur-core.php
Previously the user registration notification was shown below the form. Now, We have shown the notification by removing the form on it.
1. Create a form
2. Perform user registration with correct data
3. Perform user registration by incorrect data(For eg: Creating user with same email address) 
4. Verify the notification message
> Tweak - Improve success message after registration
=> UR-1057 Tweak - Improve success message after registration

includes/admin/class-ur-admin-menus.php
Previously, To use stripe addon user have to install payments addon to use payments fields and global settings, Now we decided to remove it's dependency and move all payments fields to PRO and it will be visible only if the PayPal or stripe addon activated. 
Please verify whether all payments functionality works individually and Combinedly.
1. Test all payments functionality individually activating addon paypal and stripe.
2. Test all payments functionality by activating both addon paypal and stripe.
> UR-1091 Refactor -Remove payments addon dependency form stripe.
=> UR-1091 Refactor -Remove payments addon dependency form stripe.

includes/admin/functions-ur-admin.php
If the registered number of users is big then a very heavy manual counting of users registered in day, week, and month will run in the dashboard analytics widget. This PR is replacing the manual user counting with a raw SQL query to optimize the performance. 
1. Check if the total users before and after the branch switch are the same.
2. Check if the total users registered in day, week and month before and after the branch switch are the same.
> Tweak - Manual user counting replaced with SQL query
=> UR-1238 Tweak - Manual user counting replaced with SQL query

includes/shortcodes/class-ur-shortcode-my-account.php
Previously, in rp_login variable instead of username it's returning user_id due to that wordpress default function was unable to identify the user and returning Invalid Key error message. In This this issue resolved.
1. Check Lost Password functionality working properly.
>  Lost password page redirecting to login page.
=> UR-1240 Lost password page redirecting to login page.

includes/class-ur-ajax.php, includes/class-ur-form-handler.php
Previously, Email change confirmation does not include email template design. This PR will fix this issue.
1. Switch to this branch and verify whether it is working properly or not.
> UR-1304 Fix - Send email change confirmation with templates
=> UR-1304 Fix - Send email change confirmation with templates

templates/myaccount/form-edit-profile.php
In this PR, we deprecated `user_registration_before_edit_profile_form` and introduce new hook with arguments `user_registration_before_edit_profile_form_data`.
1. Check profile completeness addon working properly or not.
> Fix - Profile completeness hook mismatch issue.
=> UR-1307 Fix - Profile completeness hook mismatch issue

assets/js/admin/form-builder.js, assets/js/frontend/user-registration.js, includes/admin/class-ur-admin-assets.php, includes/form/class-ur-form-field-country.php, includes/form/settings/class-ur-setting-country.php, includes/functions-ur-template.php
Previously, When the user wanted to select no default value of country there was no option for that. This PR gives those fixes.
1. Drag a country field.
2. Fill in the placeholder and verify the new option in the default value.
3. Also check if the field is a required case.
> Fix - Placeholder is not working in the country field.
=> Fix - Placeholder is not working in the country field

assets/js/admin/form-builder.js
Previously, when we updated the option of select field. And if we choose that select field in the assigned role conditionally from the form setting without refreshing the page then the value of that updated option didn't come. This PR fixes that issue.
1. Edit the form and Change the select field option.
2. Form setting > enable assign role conditionally > choose select field
3. Verify its value.
> Fix - Select field option not changing instantly.
=> Fix - Select field option not changing instantly

includes/admin/class-ur-admin-user-manager.php, includes/admin/settings/emails/class-ur-settings-approval-link-email.php, includes/class-ur-email-approval.php, includes/class-ur-emailer.php, includes/class-ur-smart-tags.php, includes/functions-ur-core.php
Previously, there was no link sent to Admin to "Deny" user directly through "Admin Approval" and "Admin Approval after Email Confirmation". This PR introduces "{{denial_link}}" smart tag similar to "{{approval_link}}".
Closes # .
1. Switch to this PR and Goto Form settings of a Form.
2. Set to "Admin Approval" or "Admin Approval after Email Confirmation" for User Approval and Login Option.
3. Register a user, test if "Deny Now" Link works on admin email for denying user for both test cases.
4. Keep in mind the use of {{denail_link}} smart tag on admin email in User Registration > Settings > Email.
> Feature - Deny Smart Tag in Admin Approval.
=> Feature - Deny Smart Tag in Admin Approval.

assets/js/admin/form-builder.js
Previously, when we updated the option of select2 and multi-select field. And if we choose that select2 and multi-select field in the assigned role conditionally or condition redirection from the form setting without refreshing the page then the value of that updated option didn't come. This PR fixes that issue.
1. Edit the form and Change the select2 and multi-select field option.
2. Form setting > enable assign role conditionally > choose select2 and multi-select field
3. Verify its value.
> Fix - Fields select 2 and multi select option not changing instantly in builder setting area
=> Fix - Fields select 2 and multi select option not changing instantly in builder setting area

includes/form/class-ur-form-field-country.php, includes/functions-ur-template.php
Previously, when we select default value of Country field to 'None', the field on the frontend was showing 'Afghanistan' (first country) as default. This PR fixes this issue.
Closes # .
1. Drag a country field in your form.
2. Erase the placeholder (empty) and select default value as 'None'.
3. Check on the frontend. (Also try entering a placeholder value and verify if it is working properly or not).
> Fix - Country Field default value none Frontend Issue.
=> Fix - Country Field default value none Frontend Issue.

includes/class-ur-emailer.php
Previously, the password was visible in the mail if  extra password field was used in the form. If user updates the detail on form having extra password field and the email enabled for the admin account.
Closes # .
1. Go to UR Settings > Emails
2. Enable toggle for Profile Details Changed Admin Email
3. Create a form using an extra password field
4. Register a user using the newly created form
5. Go to Edit profile page of the user account
6. And update the user details
7. Now, go to admin email mail box
8. And check where the password is visible on the user detail or not.
> Fix - Remove extra password field value in mail
=>  Fix - Remove extra password field value in mail

includes/class-ur-smart-tags.php
There was no option to add {{form_name}} as the smart tag. This PR introduces the {{form_name}} smart tag.
Closes # .
1. Go to UR>Settings>Emails
2. Click on any email settings option
3. Click on Add Smart Tags button. It now includes Form Name on the list.
4. Add it on the email content
5. Register a user enabling the modified email content.
6. Now, verify if it is working accordingly or not.
> Tweak - Introduce form name smart tag in user registration
=> Tweak - Introduce form name smart tag in user registration

includes/functions-ur-core.php, includes/functions-ur-template.php
This PR introduces the **Previous page** option in the redirection after registration which redirect back to previous page URL after registration
1. Create a form
2. Goto to form settings >General > choose the previous page in redirection after the registration section
3. Verify.
> Tweak  - Redirection back to previous page after registration
=> Tweak  - Redirection back to previous page after registration

includes/class-ur-shortcodes.php
Previously, Escaping was missing for display name which leads to injecting malicious code. This PR will fix this issue.
1. Create a form with display name.
2. Register a user with this form and make sure you inject malicious code in display name while register.
3. Now Login that user and redirect to registration form and verify whether malicious code execute or not.
> Fix - Escaping missing for display name.
=> UR-1399 Fix - Escaping missing for display name.

includes/admin/class-ur-admin-user-manager.php, includes/class-ur-user-approval.php
Previously wrong message was shown when a user registered from forms created with login option `auto approval after email confirmation`  tried to login after they have been denied by the admin. This PR fixes the issue along with the issue where the deny option kept showing on the user's list even after the user was denied by the admin.
Closes # .
1. Create a form with `auto approval after email confirmation` login option under form settings.
2. Register a user using that specific form.
3. Do not confirm from the link provided in the mail instead deny the user from the users list page.
4. Now try to logIn.
5. Correct message i.e. `ERROR: Your account has been denied. ` must appear instead of  `ERROR: Your account is still pending approval. Verify your email by clicking on the link sent to …
=> UR 1462 Fix - Denied is not working when email confirmation is enabled.

includes/frontend/class-ur-frontend-form-handler.php
PR dependency on https://github.com/wpeverest/user-registration-woocommerce/compare/master...UR-1020-woocommerce-my-account-edit-profile-support
Previously UR MyAccount->edit profile an WooCommerce MyAccount->edit profile was not sync. This PR makes sure that both are synced.
Note: while making form make a website field and see if its value is retrieved
1.Register user in WooCommerce with UR form. Login and check if edit profile in both WooCommerce and UR edit profile are synced.
2.Register user in WooCommerce with UR form while checkout. Login and check if edit profile in both WooCommerce and UR edit profile are synced.
> Dev Compatibility - WooCommerce My-Account Edit Profile sync.
=> UR-1020 Fix - Woocommerce my account edit profile sync.

includes/admin/class-ur-admin.php, includes/functions-ur-core.php
PR Dependency :  https://github.com/wpeverest/user-registration-pro/pull/330/files
Previously Avatar/profile pictures files are left behind in /wp-content/uploads/user_registration_uploads/profile-pictures/. even if the user is deleted (with higher resolution pictures). This PR resolve that bug
Note: use higher resolution pictures or disable crop for profile pictures
Case I:
1.Register user with profile picture.
2.Remove user from user registration pro->users->delete.\
Case II:
1.Register user with profile picture again.
2.Remove user from users->delete (default users of wp).
After Case I or Case II:
check  folder /wp-content/uploads/user_registration_uploads/profile-pictures/ recently deleted users all image should be removed and from wp_postmeta _wp_attached_file and …
=> UR-1218  Fix- Avatar files are left behind after deleting user.

assets/js/frontend/user-registration.js
Previously, during registration, the checkbox field with single option will not be saved on the database even if checked. This PR fixes this issue.
1. Drag a checkbox field and keep only one option. 
2. Register a user by checking that option. 
3. Verify whether the value is saved or not.
> Fix - Checkbox values are not being saved when there is a single option.
=> Fix - Checkbox values are not being saved when there is a single option.

includes/form/settings/class-ur-setting-text.php, includes/form/settings/class-ur-setting-textarea.php, includes/form/settings/class-ur-setting-user_login.php
This PR fixes the tooltip message for Length Settings of Username, Input and Textarea fields.
Closes # .
1. Goto Form Builder and drag Username, Input and Textarea Fields.
2. Goto advance setttings and verify tooltip message for Length Settings.
> Tweak - Tooltip message for Username, Text and Textarea of Length Advance Settings.
=> Tweak - Tooltip message for Username, Text and Textarea of Length Advance Settings.

includes/form/class-ur-form-field-number.php, includes/validation/class-ur-validation.php
When File Upload and other required fields whose post value on submission was not a string but array gave error on form submission. This PR fixes this issue.
1. Drag a file upload field and make it required.
2. Submit the form and see whether the submission is smooth or not.
> Fix - Form doesn't work when File Upload is required.
=> Fix - Form doesn't work when File Upload is required.

includes/admin/class-ur-admin-assets.php
Previously, our `JS` and `CSS` files were enqueued outside our screens. This pull request ensures that all `JS` and `CSS` files are now enqueued only within our screens
**PR Dependency:** https://github.com/wpeverest/user-registration-pro/pull/370
1. `Activate UR Plugin` -> inspect source (ensure you are not in UR screens).
2. Only **Dashboard-related** JS and CSS should be enqueued.
3. Check if JS and CSS are working in UR screens.
> Fix - Enquing style and script only to UR screens.
=> UR-1499 Fix - Enquing style and script only to UR screens.

assets/js/admin/form-builder.js, includes/admin/class-ur-admin-assets.php, includes/class-ur-ajax.php
Changes in this PR include code to fetch submit data from the form restriction add-ons for newly added QNA verification.
Closes # .
1. Testing depends on changes pushed from [this PR](https://github.com/wpeverest/user-registration-form-restriction/pull/5) 
2. Test accordingly to the above-mentioned PR's `How to test section`
> UR 1471 Enhancement - Q&A based form access in form restriction.
=> Sync changes with pro for qna verification type

includes/admin/class-ur-admin-user-list-manager.php, includes/class-ur-install.php, includes/class-ur-session-handler.php
Database table not found query errors throws in multi site. This PR fixes this issue.
1. Create multiple site and open subdomain site, Here you can see db error when pending users notice throws.
2. Check db issue fixed or not. 
> Fix - Query error on multisites.
=> UR-1429 Fix - Query error on multisites.

includes/admin/class-ur-admin-profile.php, includes/admin/class-ur-admin-settings.php, includes/admin/settings/class-ur-settings-license.php, includes/admin/views/html-license-form.php, includes/class-ur-plugin-updater.php
While license activation and deactivation we were not checking capability and nonce. This PR handles this by checking nonce and capability.
Note : Our license activation and deactivation code was written in user-registration, But Since now we have pro addon these code are no longer needed for user-registration, we need to move this code to pro. 
1. 'plugin_requests' this function will not trigger any case from user-registration, so you have test this in User Registration Pro Addon. 
2. License Activation from plugin list and Global Settings-> License. Check license activated properly or not.
3. License  Deactivation from plugin list and Global Settings-> License. Check license deactivated properly or not.
> Fix - Add Capability and nonce for license activation and deactivation.
=> UR-1578 Fix - Add Capability and nonce for license activation and deactivation.

includes/class-ur-email-confirmation.php, includes/functions-ur-core.php
When there was automatic user login after email confirmation, the login redirect conditions such as (Role based redirection after login). This PR fixes this issue.
Closes # .
1. Goto User Registration > Misc > Settings and apply Roles based Redirection on Login.
2. Set the form settings login option to email confirmation.
3. Register user and Confirm email and verify whether redirection works properly.
> Fix - Login Redirection complete after email confirmation.
=> Fix - Login Redirection complete after email confirmation.

includes/class-ur-smart-tags.php
{{page_id}}, {{page_url}}, {{page_title}} smart tags were not working for certain emails such as forgot password, passwordless login, user registered successfully (etc.) (test yourself). 
1. Place above three smart tags on every emails.
2. Test and verify whether the smart tags are working properly or not.
> Fix - page_id, page_url, page_title smart tags not working on certain emails.
=> Fix - page_id, page_url, page_title smart tags not working on certain emails.

assets/js/admin/form-builder.js, includes/class-ur-ajax.php
Previously when the auto-generated password was enabled the password field was hidden in the frontend form but users were not able to delete the password field from the form builder. This PR fixes this inconsistency.
1. Test this PR of pro https://github.com/wpeverest/user-registration-pro/pull/386 and review this PR.
> Dev - Compatibility for not being able to delete password field even if auto password generation is enabled.
=> UR-874 Dev - Compatibility for not being able to delete password field even if auto password generation is enabled.

includes/class-ur-form-handler.php, includes/functions-ur-core.php, includes/functions-ur-page.php
Previously, The function ur_find_my_account_in_page is called multiple times. This PR optimizes this performance and calls the function once whenever it is needed.
https://i.imgur.com/dzqtXnH.png
1. Install Query Monitor and search for this ur_find_my_account_in_page  in the Database Queries section. 
2. Check whether it calls only when it needed and whether it calls once or more.
**Note**: These changes might cause issues for translating my-account page, Please test extensively. 
> Fix - Avoid multiple query for the same info.
=> UR-1564 Fix - Avoid multiple query for the same info

assets/js/admin/form-builder.js, includes/abstracts/abstract-ur-form-field.php
Previously there was no option for admin to set a particular date for subscription to end. This PR introduce a feature to set a subscription expiry date while registration.
1. Test this PR of pro https://github.com/wpeverest/user-registration-pro/pull/402 and review this PR.
* [] Enhancement (modification of the currently available functionality)
> Dev - Compatibility for feature request set exact date for subscription to end
=> UR-851 Dev - Compatibility for feature request set exact date for subscription to end.

assets/js/frontend/user-registration.js, includes/class-ur-emailer.php, includes/frontend/class-ur-frontend-form-handler.php, includes/functions-ur-core.php, templates/form-registration.php
Previously we tried to fix email translation from backend current language, which was wrong approach we need to know user while registration which language registration form opened. Also user translate their string in different domain, so handle those domain too. 
In this PR, I have fixed Email Translation issue.
1. Translate Emails using WPML.
2. In frontend switch the language and register user. 
3. Check user email where translate according to user registered language. 
4. Check by approving and denied user too.
>  Fix - The email content translation issues with WPML plugin.
=> UR-1693 Fix - The email content translation issues with WPML plugin.

includes/admin/class-ur-admin-settings.php, includes/functions-ur-core.php
Closes # Previously when `Disable Default WordPress Login Screen` is enabled but `Redirect Default WordPress Login To` is not selected settings were saved. This PR solves this issue.
1.Go to `settings`>>`Login Options`
2.Enable `Disable Default WordPress Login Screen` and don't select any page at `Redirect Default WordPress Login To` 
3.Now verify form is not submitted and error message is displayed.
4.Also verify when selected redirection page login page is redirected.
> Fix - Diable default wordpress login not working.
=> UR-1605 Fix - Disable default wordpress login not working.

includes/blocks/block-types/class-ur-block-login-form.php, includes/blocks/block-types/class-ur-block-myaccount.php, includes/blocks/block-types/class-ur-block-registration-form.php, includes/class-ur-shortcodes.php, includes/shortcodes/class-ur-shortcode-login.php, src/blocks/blocks/login-form/Edit.js, src/blocks/blocks/login-form/block.json, src/blocks/blocks/myaccount/Edit.js, src/blocks/blocks/myaccount/block.json, src/blocks/blocks/registration-form/Edit.js, src/blocks/blocks/registration-form/block.json
Previously when admin viewed the login form block it showed already logged In now it should show according to the state.
Added user-logged In state feature, on blocks such as user login and user registration , also added access or restrict state for content restrictions as well.
Closes # .
1. Go to any page editor and add Blocks user-registration-form, user login, content restriction and my account
2. Change the newly added state settings on the block settings section.
3. Everything should work fine.
> Login block should show login form.
=> Dependency for login block

includes/functions-ur-core.php
Previously when Anyone can register option is enabled and saved and Really Simple SSL plugin was activated then “Disable ‘anyone can register'” setting is enabled, the “Anyone can register” option is blocked from being enabled in Settings -> General by your plugin code. This is an issue that is to be fixed by Really Simple SSL Plugin. I have raised a thread in their support https://wordpress.org/support/topic/conflict-with-disable-anyone-can-register/#new-topic-0.
Apart from not being able to save the enabled setting of Anyone can register, its previous saved enabled value was not abled to be fetched by our plugin, so even though it was previously enabled, the conflict caused by the Really Simple SSL plugin with WordPress core functionality, always sent the option value to be false …
=> UR-1658 Fix - Anyone can register option not working due to conflict with Really Simple SSL plugin

assets/js/admin/settings.js, includes/admin/class-ur-admin-settings.php, includes/admin/settings/class-ur-settings-general.php, templates/myaccount/form-edit-profile.php
Previously, when the option to disable the profile picture was enabled, it wasn’t applied if the form had advanced fields for the profile picture. This pull request fixes the issue by ensuring that the profile picture is always shown when advanced fields are present, regardless of the disable option.
1.Go to `Settings >> General >> Disable Profile Picture` enable
2. If advanced field is activate 'Sync Profile Picture ' option should be shown and when enabled profile edit should be shown even `Disable Profile Picture ` is enabled
>   Enhancement-P profile picture sync with registration form
=> UR-1444 Enhance - Profile picture sync with registration form

assets/js/frontend/user-registration.js
On form submission, when we enable separate shipping to that of billing. Shipping address also saved same billing address.
Closes # .
1. Drag all billing and shipping fields.
2. Register a user enabling "Ship to different address"
3. Login and In Address tab of My Account verify the values.
> Fix - Issue in saving shipping address different to billing in woocommerce.
=> Fix - Issue in saving shipping address different to billing in woocommerce

assets/js/admin/form-builder.js, includes/admin/class-ur-admin-assets.php, includes/functions-ur-core.php
Previously, the field used within Conditional Settings of some fields and on Form Settings could have been deleted easily without user knowing they have been used. This PR warns the user about the use of such fields on Conditional Logic.
Please test this on Pro using this branch: **UR-816-fix/urcl-field-delete-warning**
1. Drag a few fields and enable conditional logic addon.
2. Apply conditional settings for some fields and also in form settings (conditional redirection, assign role).
3. Try to delete the field used in those logics and Verify.
> Enhance - Warning for field deletion used in Conditional Logic
=> Enhance - Warning for field deletion used in Conditional Logic

includes/class-ur-ajax.php, includes/class-ur-form-handler.php, includes/functions-ur-core.php, includes/functions-ur-template.php, includes/validation/class-ur-form-validation.php
Sync changes for free files related to [Feature to edit user by admin](https://github.com/wpeverest/user-registration-pro/pull/461)
Closes # .
1. Follow steps shown on this [PR](https://github.com/wpeverest/user-registration-pro/pull/461)
Feature - User edit feature for admin.
=> Ur-1678 Feature - User edit feature for admin. (Sync)

assets/js/frontend/user-registration.js, includes/class-ur-user-approval.php
This was not replicated on our side but only on users side. But when a user registered from woocommerce tried to use a coupon code with one use per user limit, the checkout process was not carried out. Because although the user was not from our side the admin_approval global login_option (deprecated in previous versions) conflicted with the coupon code process and halted the checkout process.
1. Register a user from woocommerce registration (dont enable our user-registration-woocommerce)
2. Create a coupon code with one use per user limit from Marketting > Coupon.
3. Use the coupon code using one user and again register a user and try using coupon code during the checkout process.
4. Make sure "user_registration_general_setting_login_options" is set to "admin_approval" in options table …
=> Fix - Hide Unapproved Users action run for users not from our source

includes/class-ur-ajax.php, includes/functions-ur-core.php
Previously, when a new form was created and tried to enable captcha support and save form, it gave error. This PR fixes the issue.
Closes # .
1. Create a new form after setting up captcha from User Registration > Settings > Captcha.
2. Enable Captcha Support from Form Settings and try saving form.
3. Check if the form save and other captcha functionality on frontend works properly or not.
> Fix - Form save action not working for initial form publish captcha setting
=> Fix - Form save action not working for initial form publish captcha setting

includes/class-ur-smart-tags.php
The links and endpoints gave issue for navigation after wpml translation of slugs. This PR fixes this issue.
Zips: https://themegrill.atlassian.net/browse/UR-1945?focusedCommentId=24167 
Closes # .
1. Translate our plugin using WPML String translation.
2. Translate slugs for my account endpoints and links.
3. In frontend check whether or not everything is working properly or not.
> Fix - Slug translation issue on my account links.
=> Fix - Slug translation issue on my account links

includes/frontend/class-ur-frontend-form-handler.php
wp_insert_user threw error object when default fields validation from wordpress was not met. This PR fixes this issue.
1. Drag user_url (website) field.
2. While submitting form, insert more than 100 characters in website field.
3. Please see whether error handling works properly or not.
> Fix - Error handling when wp_insert_user throws error.
=> Fix - Error handling when wp_insert_user throws error.

includes/class-ur-preview.php
This PR fixes the issue for admin email mismatch on User Email verified.
1. Put login option on Admin Approval after Email Confirmation
2. Register a user and verify the email.
3. Check if admin email is sent according to the Email in User Registration Settings > Emails section. (Change the email and verify)
4. Also check on email preview section.
> Fix - Email content mismatch on Verified Email
=> Fix - Email content mismatch on Verified Email

assets/js/frontend/password-strength-meter.js, assets/js/frontend/user-registration.js, includes/class-ur-frontend-scripts.php
Custom password was working only during preview but not on actual form, this issue fixes it.
Closes # .
1. Select a form -> Form Settings -> General -> Enable Strong Password -> Custom Password
2. Check if the validation works correctly on preview and on actual form.
Bug - Undefined issue on custom password
=> UR-1974 Bug - Undefined issue on custom password

includes/functions-ur-core.php
This PR fixes the issue of having the null value passed in the strpos deprecated.
Closes # .
1. Go to other pages except the Login, My Account or Woocommerce Page and it might replicate with PHP version PHP 8.1.
> Fix - Strpos deprecated warning.
=> Fix - Strpos deprecated warning.

templates/myaccount/form-edit-profile.php
Previously, In our User registration profile edit page the size of profile picture upload was the server file upload size multiplied by 1024. This PR fixes this profile picture upload size message in the edit profile page
Closes # .
1. Go to the Edit profile Page and check the max capacity for the profile picture.
2. Check whether the size is according to the server size or not.
> Fix - File size upload in the edit profile according to server size.
=> Fix - File size upload in the edit profile according to server size.

templates/myaccount/form-login.php
This PR fixes the issue of having the slash while entering the ' in the Registration Label for the Login Form.
Closes # .
1. Go to URM > Login Form > General
2. Enter the test with ' such as Don't have an account for the **Registration label**
3. Click on the Update form button.
4. Now go to my account login page and check the registration label.
> Fix- Stripslashes for the registration label in login form.
=> Fix- Stripslashes for the registration label in login form.

includes/class-ur-emailer.php
Previously, in our User registration email template was not working for the password rest email while sending the email from Admin Dashboard from that specific user's detail page.
Closes # .
1. Register a user from our form and select the email template for that form.
2. Now Go to User Registration > Users > View any user
3. Click on the Send Password Reset Email from the leftmost menu of the User's Detail Page
4. Finally, verify whether the password reset email is send or not accordingly with the expected email template and email contents.
> Fix - Email template for reset password from the admin dashboard.
=> Fix - Email template for reset password from the admin dashboard.

assets/css/user-registration.scss
Previously, while customizing the error message styling from the Style customizer it was not reflecting on the frontent while was working fine in the preview. This PR fixes this issue.
Closes # .
1. Go to User registration > Settings > Login Forms and click on the Paint brush
2. After that, it will be redirected to the Customizer.
3. Go to Messages > Enable the Show Error Message
4. Now check whether it is working accordingly or not.
[Style customizer PR dependency](https://github.com/wpeverest/user-registration-style-customizer/pull/15)
> Fix - Error message styling not changing from style customizer.
=> Fix - Error message styling not changing from style customizer.

assets/js/admin/admin.js, assets/js/admin/settings.js, includes/admin/class-ur-admin-menus.php, includes/admin/class-ur-admin-settings.php, includes/class-ur-ajax.php, includes/functions-ur-account.php, includes/functions-ur-core.php
This PR adds the option to select the lost password page  from the login options settings.
Closes # .
1. Create a Lost Password page using [user_registration_lost_password] shortcode.
2. Go to URM > Login Form
3. Click on **General > Enable Lost Password >  Select the Lost Password page from the dropdown**
4. Click on the **Update Form**
5. Check this in the backward compatibility and in the woocommerce whether the **Lost Password Page** is working or not.
> Enhance - Option to select lost password page.
=> Enhance - Option to select lost password page.

includes/admin/class-ur-admin-assets.php
This PR fixes the issue for plugin conflict while using the form analytics of Everest Forms and User Registration at same time.
Closes # .
1. Enable the Form Analytics from User registration and Everest Forms.
2. Check whether the chart for User registration analytics is displayed or not.
> Fix - Conflict while using analytics for UR and EVF at a same time.
=> Fix - Conflict while using analytics for UR and EVF at a same time.

templates/myaccount/form-edit-profile.php
Previously, while using row conditional logic setting, it was not working accordingly on the Profile page. This PR fixes the conditional logic issue.
Closes # .
1. Enable the Conditional logic addon.
2. Use the row setting conditional logic and perform the entry.
3. Now login as the recent entries user and check if the conditional logic is working accordingly or not.
> Fix- Row settings conditional logic not working on profile edit.
=> Fix- Row settings conditional logic not working on profile edit.

assets/js/admin/settings.js, includes/admin/class-ur-admin-menus.php, includes/class-ur-ajax.php
This PR fixes the issue while no page is selected on enabling the **Disable Default WordPress Login Screen**
Closes # .
1. Go to URM > Settings > Login Forms > General > Enable **Disable Default WordPress Login Screen**
2. Do not select the page from the **Redirect Default WordPress login To** dropdown.
3. And check whether the validation message is shown or not.
4. Also check whether it is allowing to save the setting while not selecting any page.
> Fix - Validation on the disabling default WordPress page setting.
=> Fix - Validation on the disabling default WordPress page setting.

includes/admin/class-ur-admin-export-users.php
The lambda expression was not supported by the PHP version less than 7.4. There was use of one in the export setting. This PR makes it compatible with PHP less than 7.4.
Closes # .
1. Use the PHP version 7.4
2. Check the export entries setting.
> Fix - Lambda expression not supported in php version less than 7 4.
=> Fix - Lambda expression not supported in php version less than 7 4.

includes/frontend/class-ur-frontend-form-handler.php, modules/membership/includes/AJAX.php, modules/membership/includes/Admin/Services/MembersService.php, modules/membership/includes/Admin/Services/Paypal/PaypalService.php, modules/membership/includes/Admin/Services/Stripe/StripeService.php
The vulnerability reported is an authentication bypass which we consider to be a high risk due to unauthenticated users being able to login as any users (including admin) by providing the user ID. We confirmed the issue in the current version, 4.1.1.
This fix fixes the issue by adding a user_meta `urm_user_just_created`  when creating the user and checking it  during the ajax request. The meta gets deleted after the check is completed.
Closes # .
1. Refer to [this comment](https://themegrill.atlassian.net/browse/UR-2264?focusedCommentId=26028) to recreate this issue. 
Security - Vulnurability fix for auto_login after registration.
=> UR 2264 Security - Vulnurability fix for auto_login after registration.

assets/extensions-json/all-features.json, includes/RestApi/controllers/version1/class-ur-modules.php, package-lock.json, package.json, src/context/dashboardContext.js, src/dashboard/screens/Modules/Modules.js, src/dashboard/screens/Modules/components/ModuleItem.js, webpack.config.js
Previously when activating Paypal module, the payment history module used to activate but the toggle did not auto enable this PR fixes the issue along with few minor bugs.
Closes # .
1. Checkout to this branch in pro > enable PayPal from Dashboard > Features
2. See if the payment history module activates too (Also check with stripe and authorize.net)
Bug - Auto enable Payment history when enabling payment
=> UR-2277  Bug - Auto enable Payment history when enabling payment addons.

includes/class-ur-smart-tags.php
USA Zip code validation fixed for 5 and 9 digit code
1. Apply Pattern validation from advanced fields
2. 5 digit and 9 digit zip code is now validated (xxxxx and xxxxx-xxxx)
=> UR-2339 : Updated regex for USA zip code validation

src/form-templates/components/Main.js
Previously, when the user selects a new category template in URM Dashboard Templates Page, the scrollbar remains at the previous state. In this PR, the scroll bar is moved to top on category selection each time it changes. 
1. Go to URM Dashboard > Create a Registration Form
2. Select a category from Template
3. Notice, the scrollbar is moved to top.
Enhance - Scrollbar move to top on category selection on form template page
=> UR-2281 Enhance - Scroll to top on category selection on form template page

includes/functions-ur-account.php
Closes #
1. Go to URM > All Form > Login
2. Add a custom message for invalid username "Invalid username"
3. Go to login page, try logging in with non existing username, the error doesn't show the lost your password?
Before Fix:
After Fix:
Fix - Remove lost your password link from login error messages
=> UR-2211 Fix - Remove unnecessary lost your password link from error message

assets/js/admin/live-user-notice.js
When opening the two dashboard on same browser simultaneously and logging out from one tab, the Login Form modal is displayed, after the login process it redirects to the dashboard and opens for the long time. This PR fixes this issue.
Closes # .
1. Open the admin dashboard in two tabs simultaneously.
2. Logout from one tab and go to the another, a login form popup must be open, after login the popup must close in few secs.
3. Check if it closes automatically after login or not.
> Fix - Opening the lightbox for long duration after login in admin dashboard.
=> Fix - Opening the lightbox for long duration after login in admin dashboard.

includes/class-ur-smart-tags.php
Closes #.
Previously when registering from preview the username smarttag used to show logged in user's username this PR fixes that issue.
1. Preview a form logged in as admin
2. Fill in the form and verify if the email show correct username.
> Fix - Username smart-tag shows logged in user's username in form preview.
=> UR-2375 Fix - Username smart-tag shows logged in user's username in form preview.

includes/functions-ur-template.php, includes/validation/class-ur-validation.php
There was the typo error while the validation was made for the textarea with max character count and even-though the max character count and the textarea character was error the error message was showing. This PR fixes this issue.
Closes # .
1. Drag and drop the text area field, add the validation of the max count.
2. Now check the frontend of the form whether the character count is adding the additional test user-registration or not
3. Enter exactly 1000 characters suppose you have made the max count 1000 and check whether the validation message is shown or not.
> Fix - Textarea validation and character count message typo error.
=> Fix - Textarea validation and character count message typo error.

assets/js/frontend/user-registration.js
While using Hello Elementor theme, Year dropdown is not displayed in the date time picker field. This PR fixes this issue.
Closes # .
1. Drag and drop date time picker field.
2. Install and activate Hello Elementor theme.
3. In the frontend section, check whether the year drop down is displayed or not in date picker field.
> Fix - Datetime field conflict with hello elementor theme.
=> Fix - Datetime field conflict with hello elementor theme.

modules/content-restriction/class-urcr-shortcodes.php
While using the partial content restriction, restriction message was not modified according to the global restriction message. This PR fixes this issue.
Closes # .
1. Refer to this docs [Partial restriction](https://docs.wpuserregistration.com/docs/content-restriction/#7-toc-title)
2. Change the message in Global restriction setting.
3. Check whether the global restriction message is displayed or not.
> Fix - Partial content restriction message Modification.
=> Fix - Partial content restriction message Modification.

assets/js/admin/admin.js
Previously the enable toggle was triggering the override global PayPal settings switch; this PR fixes this.
1. Edit Form
2.  Go to Form Settings > Paypal Settings
3. Toggle Enable paypal switch and see if it is still toggling payapl override switch.
>  Fix - Enable Paypal in form setting triggers override global paypal settings
=> UR 2545  Fix - Enable Paypal in form setting triggers override global paypal settings

includes/RestApi/controllers/version1/class-ur-plugin-status.php
When creating a PayPal Event Registration Form, the required add-ons are not properly recognized. After publishing the form, attempting to edit it from the “All Forms” section causes a warning to be encountered.
Closes # .
1. Go to URM > All Forms > Add New.
2. Go to Payments Form > Select PayPal Event Registration Form and click on Get Started.
3. Check whether the Paypal is installed, activated and the form with Paypal is created or not.
> Fix - Failure of Paypal form creation.
=> UR-2547 Fix - Failure of paypal form creation.

includes/admin/views/html-admin-page-export-users.php
If there are no forms and the users, in import users the Select Form option was shown even though  the forms were not available for exporting. This PR fixes this issue.
Closes # .
1. Delete all users and forms.
2. Go to URM >  Settings > Import/ Export > Export Users
3.  Check whether the Select form option is displayed or not if no forms were there.
> Fix - Export users page issue in settings.
=> UR 2622 Fix - Export users page issue in settings.

includes/abstracts/abstract-ur-form-field.php, wpml-config.xml
Submit button label and html content was not translatable in WPML. This PR fixes this issue.
Closes # .
1. Create a form using the html content.
2. Make the submit button text and HTML content translatable in WPML.
3. Check whether it is translated or not in multiple language site.
> Fix - Submit button label and html content not translatable in WPML.
=> Fix - Submit button label and html content not translatable in WPML.

includes/class-ur-smart-tags.php
There was fatal error while sending the payment successful email without creating the membership form or simply not activating membership plugin.
Closes # .
1. Create a subscription plan using subscription plan field.
2. Add stripe payment field.
3. Submit the form and check whether the fatal error is thrown or not.
You can also use this form for reference: 
[teacher-2025-06-27_01_10_50.json](https://github.com/user-attachments/files/20944686/teacher-2025-06-27_01_10_50.json)
> Fix - Fatal error while sending payment successful email without membership.
=> UR-2617/Fix - Fatal error while sending payment successful email without membership.

includes/class-ur-emailer.php
This PR fixes the issue listed in the ticket and sends an email to both the user and the admin when a user's profile is updated via the admin panel through **URM > Users > Edit** .
Email is sent similar to how user updates their profile via my account page.
1. Go to **URM > Users** in the WordPress admin panel.
2. Edit any user details and save changes.
3. Ensure both the user and the admin receive appropriate email notifications with updated content.
> Email notification to user on profile update by admin.
=> UR 2400 - Email notification to user on admin profile update.

includes/functions-ur-core.php
Closes # .
1. After 3 failed email send attempt, you will get the admin notice saying email is not delivered.
> Tweak - Reduce the threshold for email delivery failure to 3.
=> UR-2767 Email delivery failure notice threshold.

modules/membership/includes/Admin/Members/Members.php
---
This PR fixes an issue where an undefined error message appears while creating a member. The change ensures that only defined and meaningful messages are displayed to the user.
Closes #
---
1. Go to the URM > Membership > Members.
2. Attempt to create a member with invalid or incomplete data.
3. Verify that no “undefined” error message is shown, and only valid error messages shown.
---
---
---
> Fix – Remove “undefined” error message displayed during member creation.
=> UR-2717 Fix - Error message displayed while creating member.

includes/admin/class-ur-admin-profile.php
While using the membership field and selecting it in the frontend listing it was not displaying in the profile detail for frontend list. This PR displays the membership plan in profile details page.
Closes # .
1. Create a form using membership field and create a frontend list select membership field for profile listing and profile detail for frontend listing
2. Check whether the membership is displayed or not.
> Tweak - Display membership plan in profile detail for frontend listing.
=> UR-2896 Tweak - Display membership plan in profile detail for frontend listing

assets/js/admin/form-builder.js, assets/js/modules/membership/admin/membership-groups.js
Fixes the bug which is replicated as follows:
* Enable form title and description from **Form settings > General** while disabling all the payment methods, notice the membership field is locked saying it cannot be used alongside the payment fields.
Closes # .
1. Confirm the bug mentioned above is not replicated with this changes.
> Fix - Membership locked even when payment method is not enabled.
=> Fix membership field locked even when payment method is not enabled.

includes/functions-ur-core.php
While using the polylang translation for field label, it was repeating specific field name for all fields in the translated version after form submission.
Closes # .
1. Use polylang translation plugin
2. Translate the page and fields in polylang
3. Go to the translated version of the page
4. Submit the form and reload the page check if the accurate translated field names are displayed or not.
> Fix - Field Label translation in polylang.
=> UR-2934 Fix - Field Label translation in polylang

assets/js/modules/content-restriction/admin/urcr-custom.js
In the page if override global setting is enabled then in the page reload the setting under override global setting is not displayed. This PR fixes this issue.
Closes # .
1. Go to page
2. Enable override global setting and save the page
3. Reload the page and check if the settings under override global settings is displayed or not.
> Fix - Override global setting retain in page reload.
=> UR-2822 Fix - Override global setting retain in page reload

includes/admin/notifications/class-ur-admin-notices.php
Closes # .
While we don't want to use the URM my account page such as in case of buddy press the my account selection message was displaying. This PR adds the filter to hide this notiifcation conditionally.
1. Do not select my account page in setting and check whether the my account selection notice is displayed or not after using this filter.
> Dev - Filter to hide my account page selection notice.
=> UR-2663 Dev - Filter to hide my account page selection notice

modules/content-restriction/class-urcr-frontend.php
The Inner page content restriction is displayed even-though override global setting is disabled in Post. This PR fixes this issue.
Closes # .
1. Go to Page > Edit the content for override global settings
2. Disable override global setting 
3. Check tick on the Restrict Page or post checkbox.
4. Click on Save button
5. Now check the page in logged out mode and check the message whether it is from global setting or from inner page.
> Fix - Inner page restriction message displayed even though override global setting is disabled.
=> UR-3047 Fix - Inner page restriction message displayed even though override global setting is disabled

includes/admin/settings/class-ur-users-list-table.php, includes/admin/settings/class-ur-users-menu.php
While assigning the custom capability **manage_user_registration** for roles such editors, author or some other roles. Users tab was not displaying. This PR fixes this issue.
Closes # .
1. Use **User Role Editor** plugin to assign capability **manage_user_registration** for non-administrator roles.
2. Now login into the WP dashboard with that non-admin role and check whether the URM> Users listing is displayed or not?
> Fix - Manage_user_registration capability not working for users tab in custom role.
=> UR-2643 Fix - Manage_user_registration capability not working for users tab in custom role

assets/js/admin/ur-notice.js, includes/admin/class-ur-admin-assets.php, includes/admin/class-ur-admin-user-list-manager.php, includes/admin/class-ur-admin.php, includes/admin/functions-ur-admin.php, includes/class-ur-ajax.php
An admin notice was displayed previously for 5 or more users registered from other than URM forms, which kept showing even if the user closed it intentionally, impacting user experience.  
Now when the admin user closes it:  
- On first close, it will disappear for 24 hours.  
- On second close, if dismissed within the past 48 hours, it will be dismissed permanently.
- If dismissal is not within 48 hours, it just resets the admin notices close count and hides for 24 hours only.
Closes # .
1. Register 5 or more users from outside URM forms.
2. Confirm that the admin notice appears in UR pages.
3. Close the notice once → it should disappear for 24 hours.
4. Close the notice again within 48 hours → it should disappear permanently.
> Enhance – Persistent dismissal of non-URM users admin …
=> UR-3057 Enhance - Persistent dismissal of non urm users admin notices in UR pages.

modules/content-restriction/class-urcr-frontend.php, modules/content-restriction/class-urcr-shortcodes.php
---
Previously, **content restriction** was **not applied** to members whose membership status was **no longer active**.  
With this update:
- If content is allowed only for a **specific membership plan**, members without an active subscription for that plan will be **restricted**.
Closes # .
---
1. Go to **URM > Membership** and create a membership plan.
2. Test for content restrictions for membership:
- Global content restriction.
- Content restriction to pages/posts.
- Content restriction via shortcodes.
3. Verify that only membership with active status can access the restricted content but members with other status or non-members cannot access the restricted content.
---
---
---
> Enhance – Content restriction applied to members whose membership is not active.
=> UR-2984 Enhance - Content restriction for membership status not active.

modules/membership/includes/AJAX.php
This PR fixes the delay of the updated plan details on the change plan.
Closes # .
1. Follow the steps on this issue to recreate and test.
2. https://themegrill.atlassian.net/browse/UR-2826
> Fix - Reflect updated plan type in change plan
=> UR 2826 Fix - Reflect updated plan type in change plan

includes/admin/class-ur-admin-settings.php
This PR fixes the invalid image shown, in the upload header section when no header image is selected.
Closes # .
1.Settings > PDF Submission
2. Remove header value if already has one and see if any invalid img is shown.
> Fix - Pdf form submission invalid image on empty src
=> Fixed pdf form header empty issue.
