wpeverest/user-registration

- includes/class-ur-install.php
This PR adds a transient lock to ensure we are only running this once.
> lock install routine to only allow for one execution

- includes/class-ur-emailer.php
- readme.txt
Some enhancements in email and readme
> Some enhancements on emails

- includes/abstracts/abstract-ur-form-field.php
- includes/admin/class-ur-admin-profile.php
- includes/form/class-ur-privacy-policy.php
- includes/form/views/admin/admin-privacy-policy.php
- includes/functions-ur-core.php
- includes/functions-ur-template.php
- templates/myaccount/form-edit-profile.php
We could use single checkbox for this case, but the issue is that single checkbox can later be edited from admin user profile and my account page by user. This feature can be used for privacy policy and terms and conditions types.
> Add a privacy policy drag and drop

- templates/myaccount/form-login.php
Check for empty option to fix fatal error in PHP v<5.5
> Compatibility for PHP v5.4 #20

- includes/admin/settings/emails/class-ur-settings-email-confirmation.php
- includes/class-ur-email-confirmation.php
- templates/form-registration.php
- templates/myaccount/form-login.php
This PR allows users to redirect to custom page after the user registration via email confirmation.
> Redirect to custom page via email

- includes/admin/class-ur-admin-profile.php
- includes/class-ur-form-handler.php
- includes/frontend/class-ur-frontend-form-handler.php
- includes/functions-ur-template.php
- templates/myaccount/form-edit-profile.php
Previoulsy, the checkbox values are stored in json format. Now saved in serialized array format, and display accordingly.
> Refactor how the checkboxes are stored in db

- includes/functions-ur-update.php
According to change in it's data serialization, this is needed for migration script.
> Refactor checkbox and optimize query

- includes/class-ur-install.php
- includes/functions-ur-update.php
@sanzeeb3 This stuffs are related to usermeta so lets cover all the queries in a single function. Needs tests :)
> Refactor update and delete usermeta in single function

- includes/admin/class-ur-admin-menus.php
- includes/admin/class-ur-admin-registrations-table-list.php
- uninstall.php
This PR purposes rename of list table class and autoload list table class on demand to reduce memory consumption.
CC @sanzeeb3
>  Fix - list table autoload call on demand to reduce memory consumption

- includes/admin/class-ur-admin-profile.php
In previous version privacy policy appeared from the user meta, now with refactored it appears to be the value stored in user meta which is 1 if checked, so displaying from form. Also, privacy policy should never be edited so disabled.
> Privacy policy display from form

- includes/admin/class-ur-admin-user-list-manager.php
- includes/class-ur-user-approval.php
Displays a notice to admin if the users are awaiting admin approval via admin notices.
> Admin notice for admin approval

- includes/class-ur-autoloader.php
- includes/class-ur-emailer.php
This PR introduces the feature to include all user filled information in the email.
> User form filled information in email

- includes/admin/settings/class-ur-settings-general.php
- includes/class-ur-frontend-scripts.php
- templates/myaccount/form-login.php
This PR introduces a feature to customize the messages seen on frontend.
> Custom frontend messages

- includes/class-ur-ajax.php
- includes/form/class-ur-user-username.php
- includes/form/views/admin/admin-user-username.php
- includes/frontend/class-ur-frontend-form-handler.php
- includes/functions-ur-core.php
- templates/myaccount/form-login.php
This PR introduces the feature to allow registration without username. Since username is a required field for wordpress, if the username is not used in registration it will be generated randomly.
> Username optional

- assets/js/admin/admin.js
- includes/abstracts/abstract-ur-form-field.php
- includes/admin/class-ur-admin-menus.php
- includes/class-ur-ajax.php
- includes/functions-ur-core.php
- includes/functions-ur-template.php
This PR introduces the hide label feature, so that registration with only placeholder looks appropriate. Also, the description for each field is on focus, which allows a link in privacy policy.
> Hide label

- includes/class-ur-email-confirmation.php
- includes/class-ur-emailer.php
This PR introduces the feature to resend email verification link if user by somehow didn't received the email.
> Resend email

- includes/class-ur-install.php
This PR includes the logic to run the updater to only versions 1.2.2, 1.2.3 and 1.2.4
> Migration tweak

- includes/class-ur-email-confirmation.php
add the $user_id and a new variable $user_reg_successful as arguments to the action “user_registration_check_token_complete“,
would be useful for developers to check the status on user verification
> enhance "user_registration_check_token_complete"

- includes/admin/settings/emails/class-ur-settings-admin-email.php
- includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
- includes/admin/settings/emails/class-ur-settings-email-confirmation.php
- includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
- includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
- includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
- includes/admin/settings/emails/class-ur-settings-reset-password-email.php
- includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
This PR fixes the emails contents to be translation ready.
> Making all email contents translation ready

- includes/admin/settings/emails/class-ur-settings-admin-email.php
- includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
- includes/admin/settings/emails/class-ur-settings-email-confirmation.php
- includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
- includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
- includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
- includes/admin/settings/emails/class-ur-settings-reset-password-email.php
- includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
- includes/form/class-ur-country.php
This PR includes the minor fixes and changes.
> Fixes and minor changes

- includes/admin/settings/emails/class-ur-settings-admin-email.php
- includes/class-ur-emailer.php
This includes a feature to customize admin email along with multiple recipients for the email.
> Custom admin email

- includes/functions-ur-core.php
- templates/form-registration.php
This includes a feature to add custom class to registration form.
> Custom class on admin/frontend side

- includes/class-ur-shortcodes.php
- templates/form-registration.php
Display recaptcha node only if enabled.
> Display recaptcha node only if enabled

- includes/class-ur-emailer.php
This PR enhances the smart tags options to status change emails including custom fields smart tags. Further information about smart tags: https://docs.wpeverest.com/docs/user-registration/email-settings/smart-tags/
> Enhancing smart tags to status change emails

- assets/js/admin/admin.js
- assets/js/frontend/password-strength-meter.js
- includes/class-ur-frontend-scripts.php
- includes/class-ur-shortcodes.php
- includes/functions-ur-core.php
- templates/form-registration.php
Introduces the customizable password strength meter along with displaying password strength messages to the password field rather than confirmation password field.
> Customizable Password Strength Meter

- includes/class-ur-frontend-scripts.php
- includes/class-ur-shortcodes.php
- includes/functions-ur-core.php
- includes/shortcodes/class-ur-shortcode-my-account.php
Loads the flatpickr js and css only if the form contains the date field.
> Conditionally load flatpickr js and css

- includes/class-ur-form-handler.php
- templates/myaccount/form-edit-password.php
-Added filter for change password field in form handler to bypass current password validation and check.
-Added filter for change password field in my account's change password tab. This filter is used to hide and show this field.
> Social connect change password

- includes/abstracts/abstract-ur-form-field.php
- includes/class-ur-form-handler.php
- includes/class-ur-shortcodes.php
- includes/functions-ur-template.php
Filter hook added to be used in new setting type.
> General setting new hook introduced

- includes/form/settings/class-ur-setting-date.php
- includes/form/settings/class-ur-setting-description.php
- includes/form/settings/class-ur-setting-display_name.php
- includes/form/settings/class-ur-setting-first_name.php
- includes/form/settings/class-ur-setting-last_name.php
- includes/form/settings/class-ur-setting-nickname.php
- includes/form/settings/class-ur-setting-user_confirm_password.php
- includes/form/settings/class-ur-setting-user_email.php
- includes/form/settings/class-ur-setting-user_login.php
- includes/form/settings/class-ur-setting-user_pass.php
- includes/form/settings/class-ur-setting-user_url.php
Added Advanced setting Custom CSS for all Default Fields.
> Custom css for default field issue fixed, Closes #100

- includes/admin/class-ur-admin.php
Issue fixed for dashboard access issue.
> Prevent Dashboard access issue fixed, Closes #109

- includes/class-ur-ajax.php
Removed filter that sanitizes post content in the builder.
> Removed filter that sanitizes post content in builder, Closes #105

- templates/myaccount/form-edit-profile.php
Gravatar message was always shown even if the custom image was selected by the user. Which will create confusion, whether to change the custom image or change it from gravatar? If a user changes their gravatar image it won't have any effect in the custom profile picture.
> Gravatar message hide when custom picture selected 

- includes/admin/class-ur-admin-menus.php
- includes/admin/class-ur-admin-registrations-table-list.php
- includes/admin/views/html-admin-page-forms.php
- includes/class-ur-preview.php
- user-registration.php
Form preview option added in the Registration form listing.
> Form preview

- assets/js/frontend/user-registration.js
- includes/admin/settings/class-ur-settings-general.php
- includes/class-ur-frontend-scripts.php
- includes/class-ur-install.php
- includes/functions-ur-core.php
- includes/functions-ur-template.php
- includes/functions-ur-update.php
- templates/form-registration.php
This PR introduces the Feature Request in #96. Includes:
> Form wise redirection

- includes/admin/settings/class-ur-settings-general.php
- includes/class-ur-frontend-scripts.php
- includes/form/class-ur-form-field-user-confirm-email.php
- includes/form/settings/class-ur-setting-user_confirm_email.php
- includes/form/views/admin/admin-user-confirm-email.php
- includes/frontend/class-ur-frontend-form-handler.php
- includes/functions-ur-core.php
Email Confirmation Field introduced. And also new frontend message to display on email confirmation error.
> Added Email confirmation field. Closes #98

- includes/admin/class-ur-admin-menus.php
- includes/class-ur-query.php
- includes/functions-ur-core.php
- includes/shortcodes/class-ur-shortcode-login.php
- includes/shortcodes/class-ur-shortcode-my-account.php
This fixes Lost password endpoint conflict with WooCommerce. Just adding prefix ur resolves the issue. Luckily, migration script is not needed :)
> Fix - Lost Password Endpoint conflict with WooCommerce

- includes/class-ur-preview.php
Modified edit link in registration form preview using edit_post_link filter.
> Tweak - change edit registration link in form preview

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/-----security-issue.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Enhancement.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Support.md
- .github/PULL_REQUEST_TEMPLATE.md
Contribution template files for creating an issue and pull requests implemented.
> Contributing templates

- includes/class-ur-emailer.php
From header was missing in Lost Password Email trigger.
> Lost password Email headers issue

- includes/shortcodes/class-ur-shortcode-my-account.php
> Only enqueue media scripts in edit profile page. Previously it was enqueued in Whole My Account page.
> Fix - enqueue script

- templates/form-registration.php
Action hooks added for a Registration form at start and end.
> Form end hook

- includes/shortcodes/class-ur-shortcode-my-account.php
Feature request from the user. This PR adds the feature to accept redirect_to parameter from URL which adds the ability for various plugins to redirect back to their page.
https://wordpress.org/support/topic/is-redirect_to-supported/
1. Go to the login page.
2. Add `redirect_to=<page full url>` parameter in URL.
3. Login to check if it redirects to the page.
> Feature - Accept redirect_to parameter in the login page.
> Add - Accept redirect_to get parameter in login page

- includes/admin/settings/emails/class-ur-settings-admin-email.php
- includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
- includes/admin/settings/emails/class-ur-settings-email-confirmation.php
- includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
- includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
- includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
- includes/admin/settings/emails/class-ur-settings-reset-password-email.php
- includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
When admin do not save email format at that time email format was disturbed. so I fixed that by add some tag in code.
1. Do not save any email setting.
2. Do user registration or any activity where email goes to admin or user.
3. Check email format.
> fix email format when admin do not save email settings.
> Fix - Email format issue

- includes/functions-ur-core.php
This PR updates the ur_get_template() function to locate add-ons template file. Needed for add-ons like 2FA TOTP. 
> Tweak - Template file update to locate add-on's file
> Tweak - Template file update to locate add-ons file

- includes/class-ur-emailer.php
- includes/frontend/class-ur-frontend-form-handler.php
Updated password error message to more suitable message so that users won't get confused.
1. On registration form enter username and password same.
2. Or enter email address and password same.
> Fix - Password Validation Message.
> Fix - Password validation message

- includes/functions-ur-template.php
A new parameter logout_redirect was introduced in my_account shortcode that redirects to a page with specific slug after logout.
1. In My Account Edit page include a logout_redirect parameter inside the shortcode section of user_registration_my_account with the slug of the page that user wants to redirect to.
2. Login to the system, and in my account page click on logout section and click on confirmation, the user will be redirected to a the specific page with the slug specified in the logout_redirect parameter.
> Tweak - Redirect url after logout.
> Redirect url after logout

- assets/css/jquery-ui/jq-smoothness.css
- includes/admin/class-ur-admin-assets.php
Simply downloaded the exact styling being fetched from the cdn, then registering/enqueuing it to the user registration after including it as part of plugin fs.
1. Switched css styling from cdn to local
> Replacing CDN registered script with local file for jq-smoothness.
> Replacing CDN registered script with local file for jq-smoothness

- assets/js/admin/admin.js
This pull request will fix the assigning role issues to the registered user according to the conditional settings set.
1. Navigate to form setting section's general settings section.
2. An Enable Assign User Role Conditionally field will be seen at the bottom, on enabling the option, the user will be able to set the conditions and specific roles to be assigned if the conditions are met.
3. Now, Any user registered through the form will be able to login to the system with the role assigned if any of the conditions are met.
> Fix - Conditional user role settings.
> Fix- Conditional user role settings.

- includes/abstracts/abstract-ur-form-field.php
There were specific cases where the translations for WPML weren't being made for UR's dropdown/multi choice field types. This PR aims to fix so for core UR plugin.
Closes #199  .
1. Allows compatibility with WPML's translation feature.
> 665ee1f Fix: WPML on multiple choice options
> Fix: WPML on multiple choice options

- includes/functions-ur-core.php
- templates/form-registration.php
- templates/myaccount/form-edit-profile.php
Currently, custom css for the submit button has to be done programmatically by using the filter `user_registration_form_submit_btn_class`. This PR implements an option for a custom button css class which the user can easily modify. The final input from this class is then merged with the filter output and imploded into as class attributes.
1. Navigate to general settings for the form builder.
2. Enter a custom css for the submit button.
3. Observe that the css is being reflected in the frontend.
> Enhance - custom CSS button.
> Enhance - Custom class for submit button

- includes/frontend/class-ur-frontend-form-handler.php
- templates/myaccount/form-edit-password.php
This PR will now add extra validation for the fields that were deleted by inspecting the form.
1. Navigate to the registration form, inspect it and delete one or more of the required fields.
2.  Submit the form then the specific field is required message will appear and the form will not be submitted.
> Fix - Form field validation for missing required fields.
> Fix - Form field validation for missing required fields

- includes/admin/class-ur-admin-user-list-manager.php
This PR will add a new Registered At column to the User's table in the admin panel to display the date and time at which a user is registered into the system.
1. Navigate to the Users table of the admin panel and observe the Registered At column.
2.  The date and time at which a user is registered into the system will be displayed.
> Enhance - Registered At column to display registered log.
> Enhance - Registered At column to display registered log.

- includes/admin/class-ur-admin-user-list-manager.php
- includes/admin/class-ur-admin-user-manager.php
- includes/class-ur-email-confirmation.php
- includes/class-ur-user-approval.php
This PR now will be able to display the correct approval status of a user in the User's table of the admin panel.
1. Register multiple users with different login options.
2. Navigate to the Users table of the admin panel and observe the Status column.
3. Try Approving/Denying the user registered with the admin approval option and try Verifying/Unverifying he user registered with email confirmation, Correct approval status of a user will be displayed.
> Fix - User approval status.
> Fix - User approval status.

- includes/admin/class-ur-admin-profile.php
- includes/functions-ur-core.php
Mailchimp Enhancement - Corresponding changes like leave hook for after admin update user profile. which help in syncing into the MailChimp. And Add one function called ur_get_post_content($formid) which is a common function that can be reusable by another repository.
1. Test Admin side user profile edit process without MailChimp.
2. Test this PR with Mailchimp PR "https://github.com/wpeverest/user-registration-mailchimp/pull/4"
> Dev - MailChimp add-on compatibility changes.
> Dev - MailChimp add-on compatibility changes.

- assets/js/frontend/password-strength-meter.js
- assets/js/frontend/user-registration.js
- includes/class-ur-shortcodes.php
- includes/frontend/class-ur-frontend-form-handler.php
Previously rendering and submission of multiple registration forms within a single page was prone to errors and was impossible. This PR tends to make loading and submission of multiple registration forms within a single page error-free.
1. Create multiple registration forms with any combination of fields and use their shortcodes in a single page.
2. Navigate to the page on the frontend and try to submit all forms.
3. All forms will be submitted without any errors.
> Fix - Multiple forms load and submit.
>  Fix - Multiple forms load and submit.

- assets/js/frontend/my-account.js
- includes/functions-ur-template.php
1. Create a form and add a date field
2. Register a user with the form (make sure to fill the date field)
3. Login using the registered user and go to the profile details section
4. Now save the form without changing anything
5. After a refresh the value from the date field should disappear
Date field value disappears when you save profile details without changing anything in the date field. This PR fixes the issue.
1. Follow the above steps to reproduce the issue then switch to this branch
2. Now try to do the same thing and see if the issue remains
> Fix - `Date` field value disappearing from the `Profile Details` section
> Fix - Date field value disappearing from the Profile Details section

- includes/admin/class-ur-admin-user-list-manager.php
- includes/admin/class-ur-admin-user-manager.php
Previously in the user edit section in wp-admin, the admin was not able to change approval status and the approval status filter in the users table was unable to filter users registered with email confirmation. This PR fixes these issues.
1. Navigate to users table in wp-admin.
2. Choose a status filter for eg. Approved status, All the list of approved ( Approved by admin ) and verified ( Verified through email confirmation ) users will be shown in the table
3. Click on a user registered through the email confirmation, the user's approval status will now be able to be changed from verified to pending and vice-versa.
> Fix - User approval status change and filter.
> Fix - User approval status change and filter.

- CHANGELOG.txt
- includes/class-ur-shortcodes.php
- includes/functions-ur-template.php
- includes/shortcodes/class-ur-shortcode-my-account.php
- readme.txt
1. Create a page and put my account shortcode in it
2. Provide `redirect_url` argument to the shortcode
3. Save the page
4. Now open the page with Elementor
5. Change something and save.
6. Try to login. Now the login redirection should stop working.
7. Then go to edit the page with Elementor
Now the the shortcode should be gone
This PR fixes issue with the redirection in my account shortcode.
1. After reproducing the issue, switch to this branch
2. Now see if the issue still exists
> Fix - My account shortocde with Elementor
> Fix - My account shortocde with Elementor

- includes/admin/settings/class-ur-settings-general.php
- includes/class-ur-form-handler.php
- templates/myaccount/form-login.php
- wpml-config.xml
This PR adds options to customize the login form. Options to edit labels, messages, input placeholders have been added. Also, an option to hide field labels has been introduced.
1. Go to **Settings > General > Login Options**
2. There you should see 3 sections below the *Login Options* section i.e. **Labels**, **Placeholders** and **Messages**. Mess with them however you want and see if everything works fine
3. There is also an option **Hide Field Labels** in the Login *Options section*. Try that option too.
> Enhance - Login form customization
> Enhance - Login form customization

- includes/functions-ur-account.php
- includes/functions-ur-page.php
Previously when user registration my account shortcode was used on the home page, the lost password link there will redirect to a 404 page not found error. Also, log in to the system and click on my account endpoints tabs from the home page, it will also redirect to the 404 page not found. This PR purposes the fix for this issue.
1. Use the user registration my account shortcode on the home page.
2. Try clicking on the lost password section from the login page shown on the home page.
3. After the click, check whether or not the user will be redirected to the lost password page.
4. Log in to the system and check whether or not the user will be able to surf endpoint tabs from home page.
> Fix - My account endpoint URLs on the home page.
> Fix - My account endpoint URLs on the home page.

- includes/admin/class-ur-admin-user-list-manager.php
This PR adds a new filter in the user's table which filters user lists based on the selected user registration form and approval status.
1. Navigate to the user's table, observe the top and bottom of the table there will be a new filter which enables the user to select specific UR forms.
2. Set an approval status in the approval status filter and select a specific form. i.e if you want to get lists of all users with approved status registered from a specific form, then select approve status in approval status filter and specific form in specific form filter and click the button filter 
3. Observe if the displayed list after filtration is valid.
> Enhance - Filter Users with approval status and specific UR forms.
> Enhance - Filter Users with approval status and specific UR forms.

- uninstall.php
This PR fix invite codes, MailChimp data was not deleted after uninstalling with enable option to delete data on uninstall.
Dependency : User-Registration-Invite-Codes -> tweak/delete-invite-code-on-uninstall
1. Enable option Delete Data on Uninstall from settings
2. Create invite codes and Integrate Mailchimp API.
3. Now deactivate and delete the Core Plugin. It will delete all data. Check it works or not.
> Tweak - Delete UR data on uninstall
> Tweak - Delete UR data on uninstall

- templates/myaccount/form-edit-profile.php
Fixes the Conditional Logic not working in the my account page issue.
This PR is a dependency for https://github.com/wpeverest/user-registration-conditional-logic/pull/15
Follow this PR: https://github.com/wpeverest/user-registration-conditional-logic/pull/15
> Fix - Conditional Logic in my account
> Fix - Conditional Logic in my account

- includes/frontend/class-ur-frontend-form-handler.php
1. Create a form and setup Conditional Logic
2. Go to frontend and fill up the form so that one required field is hidden by Conditional Logic and has no value
3. Now submit the form. You should see a message saying the hidden field is required.
This PR fixes the above issue.
1. Checkout to this branch and see if the above issue is fixed
> Fix - Conditional Logic and Required fields conflict
> Fix - Conditional Logic and Required fields conflict

- includes/functions-ur-core.php
This PR creates a common function that returns user data in specific format which can be used in different addons like zapier, mailchimp etc.
1. Pull this PR and Test Zapier Addon.
> Dev - Zapier addon Compatibility.
> Dev - Zapier addon compatibility.

- assets/js/admin/admin.js
- assets/js/frontend/user-registration.js
This PR fixes form creation and updation issues that occur after updating WordPress v5.6.
1. Upgrade WordPress version to 5.6
2. Try to create a form or update the existing form.
3. This PR must create a form and update the existing form.
> Fix - WordPress 5.6 Compatibility issues.
> Fix - WordPress 5.6 Compatibility Issues

- includes/abstracts/abstract-ur-form-field.php
- includes/frontend/class-ur-frontend-form-handler.php
- includes/functions-ur-core.php
This PR is to make compatible with learndash new feature learndash course field.
Dependency PR : https://github.com/wpeverest/user-registration-learndash/pull/2
1. Checkout above dependency PR and follow How to test from the PR.
> Dev - Learndash Compatibility
> Dev - Learndash Compatibility

- includes/class-ur-email-confirmation.php
- includes/class-ur-user-approval.php
In this PR, Added a new action button **Resend Verification** in the Users table on the backend. Which sends an email to the respective user with a new verification link. 
Also, There was no expiry time for verification, Now we have set 24 hours of expiry of the verification link. 
1. Register user with login option **Email Confirmation**.
2. Now for Testing purposes change the system date to tomorrow's date.
3. Now try to verify your verification. You will get the error message **Token Expired !!**.
4. Now go to the admin user's table and click on the **Resend Verification** action button. 
5. After clicking resend verification button user will receive an email with a new verification link.
6. Now try to verify the user by clicking the link. The user should verify successfully.
> Enhance …
> Enhance - Resend Verification Email to User from Admin

- assets/js/admin/admin.js
- assets/js/admin/backbone-modal.js
- assets/js/admin/settings.js
- assets/js/admin/ur-copy.js
- assets/js/frontend/my-account.js
- assets/js/frontend/password-strength-meter.js
- assets/js/frontend/user-registration.js
- assets/js/ur-components/ur-components.js
- includes/admin/class-ur-admin.php
Since WordPress 5.7 removing JQuery Migrate so need to replace deprecated functions and events from the js file. This PR removed deprecated functions and event to make compatible with WordPress 5.7.
1. Whole Feature Testing needed.
> Tweak - WordPress 5.7 compatibility
> Tweak - WordPress 5.7 compatibility

- assets/js/frontend/user-registration-form-validator.js
- includes/abstracts/abstract-ur-form-field.php
- includes/admin/settings/class-ur-settings-general.php
- includes/class-ur-frontend-scripts.php
- includes/form/settings/class-ur-setting-user_login.php
- includes/frontend/class-ur-frontend-form-handler.php
- includes/functions-ur-core.php
- includes/functions-ur-template.php
Previously, There was no validation method to ensure the validity of special characters in username field. This PR provides an option to disallow special characters in username field.
1. Navigate to the form builder and drag and drop the username field.
2. In the Advance setting of field options of username field there will be option labelled as disallow special characters, enable the option.
3. Navigate to the registration form and verify whether special characters are allowed in username field or not .
> Enhance -  Disallow special characters in username field
> Enhance -  Disallow special characters in username field

- includes/class-ur-emailer.php
- includes/functions-ur-core.php
Previously when the smart tags like {{first_name}}, {{all_fields}}, etc were used in addons emails like payment success, pending, the auto password generated, and delete account emails then these smart tags were not parsed. This PR provides a base for fixing this issue.
1. Switch to the respective branches for the fix in payments, stripe, and extras addon.
2. Use almost all of the smart tags listed in the following link in the addons emails like payment success, pending, the auto password generated, and delete account emails.
https://docs.wpeverest.com/user-registration/docs/smart-tags/
3. Now register users to see if the emails received contains parsed value of respective smart tags.
> Tweak - Global function for smart tag name_value parser.
> Tweak - Global function for smart tag name_value parser

- assets/js/frontend/user-registration.js
- includes/admin/settings/class-ur-settings-general.php
- includes/class-ur-ajax.php
- includes/class-ur-form-handler.php
- templates/myaccount/dashboard.php
- templates/myaccount/form-edit-profile.php
This PR will add a feature to disable profile picture in the My Account section.
1. Navigate to the User Registration settings and navigate to the general options.
2. Check to disable the profile picture and the profile picture of the user will be hidden in the My Account section.
3. Now navigate to the My Account section and see if the profile picture is hidden there as well in the dashboard and edit profile menu.
> Feature/disable profile picture in my account section.
> Feature - Disable profile picture in my account

- includes/class-ur-email-confirmation.php
- includes/class-ur-user-approval.php
When the user selects user login option as email confirmation to login or admin approval to login in form setting and when the user tries to login with social connect then email should be disabled.
1. Navigate to User Registration and select one of the forms. 
2. Click on the form setting and choose the user login option as email confirmation to login or admin approval to login.
3. Now go to the frontend and navigate to the User Registration form and login with any social connect and you will not receive any confirmation or admin approval email.
> Fix - Disable email confirmation login using social connect
> Fix - Disable email confirmation login using social connect

- assets/js/frontend/ur-login.js
- assets/js/frontend/user-registration.js
- includes/class-ur-ajax.php
- includes/class-ur-shortcodes.php
- templates/form-registration.php
Previously when ajax login is enabled, Recaptcha v2 and v3 didn't work properly on the login and registration shortcode page. This PR fixes this issue.
1. Enable the Ajax Login option from User Registration -> Settings -> General -> Login Options.
2. Create a login and registration form on the same page using our shortcode `[user_registration_my_account form_id="id"]`.
3. Enable ReCaptcha on both the login and registration form.
4. Now verify whether both Recaptcha's are working properly or not.
> Fix - Recaptcha issue on login and registration shortcode page.
> Fix - Recaptcha issue on login and registration shortcode page

- includes/class-ur-emailer.php
Previously when these two filters `user_registration_add_smart_tags` and `user_registration_smart_tags` were used to create a new smart tag, the content of the created smart tag was not rendered properly. This PR purposes to change the placement of the filters and the process to extract respective smart tag content in order to fix the above inconsistency
1. Use the `user_registration_add_smart_tags` filter to add new smart tag and its respective value/content.
2. Use the `user_registration_smart_tags` filter to add the above generated smart tag to lists of smart tags.
3. Use your newly created smart tag in your emails, and verify if they work properly.
4. Try to use all of the smart tags available in https://docs.wpeverest.com/user-registration/docs/smart-tags/ and verify if they are …
> Tweak - Placement of smart tag filter and content mapping

- includes/frontend/class-ur-frontend.php
Closes #343 
New: Filter for the redirect URL for disable core login redirect option.
> Add filter for the redirect URL for disable core login redirect

- assets/js/admin/admin.js
- includes/admin/class-ur-admin-assets.php
- includes/admin/settings/class-ur-settings-email.php
- includes/class-ur-ajax.php
1. Navigate to User Registration settings.
2. then navigate to the **Emails** tab and you can see the **email sender option** section.
3. there you can configure the email address and name to which you want to send a test email.
https://github.com/wpeverest/user-registration-email-templates/pull/3
> Feature - Send test email.
> Feature  Send test email

- includes/frontend/class-ur-frontend-form-handler.php
- includes/functions-ur-core.php
When the User chooses the login option as auto-login after registration and the payment method is enabled then the user is directly redirected to my account instead of showing the payment method first.
1. Navigate to User Registration and select any one of the forms.
2. then Navigate to the form setting and then navigate to the general settings.
3. there you can see the user login option then select auto login after registration as a user login option and update the form.
https://github.com/wpeverest/user-registration-payments/pull/9
> Fix - Auto login conflicts with payment.
> Fix - Auto login conflicts with payment

- includes/admin/settings/class-ur-settings-general.php
- includes/class-ur-ajax.php
- includes/class-ur-form-handler.php
- includes/functions-ur-core.php
Previously, There was no login the only option is available. This PR provides the login only option.
1.  Navigate to User registration Form builder Form Settings >Login Option > Select the login only option
2.  Fill the login form with username or email and password
3.  The form should be login with chosen option only.
> Feature - Login only option
> Feature - Login only option

- includes/class-ur-ajax.php
- includes/class-ur-form-handler.php
In this PR we have fixed security issues like Authenticated XSS which will inject any script which will cause a major problems for the site owner. We have found the loopholes and fixed them.
Due to this is regarding security issue. I will DM you the replicating steps.
> Security - Authenticated XSS issue
> Security - Authenticated xss issue

- includes/frontend/class-ur-frontend.php
Previously when we use Gutenberg block shortcode for my account page then prevent the core login option is not working. This PR will fix this issue.
1. First Navigate to pages and add a new page then add a block ie (+) sign and search for user registration.
2. then choose the log-in form option and select My Account shortcode then publish the page.
3. then navigate to User Registration settings then navigate to login options of General tab.
4. then enable prevent core login option and choose redirect to the login page which you have created using Gutenberg in step 1.
5. then navigate to the frontend and type home_url with wp-admin like (localhost/wordpress/wp-admin) and see it's redirecting to that page or not. 
> Fix - Prevent core login in gutenberg login form
> Fix - Prevent core login in gutenberg login form

- includes/class-ur-ajax.php
Previously only user with administration capability were able to create users through our form and even user with `create_users` capability was not able to create users through our form which is inappropriate. This PR enhances user creation capability check while registering users.
1. Login to the system with any user with `create_users` capability.
2. Go to the registration form.
3. Try to register user, you should be able to register users.
4. Check same process for user with no `create_users` capability and administration capability.
> Enhance - User creation capability check while registering users.
> Enhance - User creation capability check while registering users

- includes/abstracts/abstract-ur-form-field.php
- includes/functions-ur-template.php
- templates/myaccount/form-edit-profile.php
Time Picker Field Enhancement - Min-Max Time, Set Current time , Time Interval Picker .
1. In Admin Side create a form with the Time picker field and it's field setting goto advance setting.
2. Select  Set the Min Max time , Set current time  and Choose the time interval.
3. In front end test Time Picker field is working according to settings or not.
https://github.com/wpeverest/user-registration-advanced-fields/pull/27
>Enhancement - Time Picker Field
> Enhancement - Time Picker Field

- includes/frontend/class-ur-frontend.php
Previously when the classic editor plugin is used then prevent core login feature is not working. This PR will fix this issue.
1. First install the Classic Editor plugin.
2. then Navigate to User Registration settings and navigate to the General tab.
3. then go to login options and enable prevent core login and save the settings.
4. then go to the frontend page and verify prevent core login feature is working or not.
> Tweak - Prevent core login
> Tweak - Prevent core login 

- includes/functions-ur-core.php
- includes/functions-ur-template.php
When WordPress version below 5.0 is running then it gives an error call to undefined parse_blocks(). This  PR will fix these issues.
1. Navigate to **https://tastewp.com/** URL and set up a new WordPress instance.
2. then install the WP Downgrade plugin and activate it.
3. then navigate to WP Downgrade of settings and enter WP target version as 4.9.18 and save changes and update core WP.
3. then ignore the deprecated function of core WordPress and install the user registration plugin.
4. then navigate to the frontend page and verify if any undefined parse_blocks() function error is showing or not.
> Tweak - Parse block compatibility before wp5.0
> Tweak - Parse block compatibility before wp5.0

- includes/class-ur-emailer.php
- includes/functions-ur-core.php
Previously, when we use the **{{all_fields}}** smart tags. file upload data is not updated after we update profile details in profile changed email. This issue will fix this PR.
1. Navigate to form builder then drag and drop file upload field.
2. then navigate to User registration settings then click the emails tab.
3. then use **{{all_fields}}** smart tags in successfully registered and profile changed email configuration.
4. then register user and then update profile details then check email file upload field details match or not. (note: for profile changed email check admin email).
> Fix - File upload data not updated in profile details changed email
> UR-192 Fix - File upload data not updated in profile details changed email

- assets/js/admin/settings.js
- assets/js/frontend/ur-login.js
- assets/js/frontend/user-registration-recaptcha.js
- assets/js/frontend/user-registration.js
- includes/admin/settings/class-ur-settings-general.php
- includes/admin/settings/class-ur-settings-integration.php
- includes/class-ur-ajax.php
- includes/class-ur-form-handler.php
- includes/class-ur-frontend-scripts.php
- includes/functions-ur-core.php
- templates/form-registration.php
- templates/myaccount/form-login.php
Introducing hCaptcha, Which helps to make more secure bots as Google ReCaptcha.
1. Goto Integration and select recaptcha type hCaptcha and enter site key and secret Key and then save settings.
2. Enable recaptcha in Login OR Registration Form
3. Visit Login Page and you will see the hCaptcha.
4. Test validation error messages and Ajax Login too.
> Feature - Introducing hCaptcha
> UR-233 Feature - hCaptcha

- includes/admin/class-ur-admin.php
- includes/frontend/class-ur-frontend.php
Previously, Prevent dashboard access feature is not working. also hide admin bar not working. This PR fix this issues. 
1. Go to the Dashborad >> User Registration >> settings >> General >> Prevent dashboard access >> choose role for example (Editor) then try to access the dashboard using the editor role users.
> UR-151 Fix - Prevent Dashboard Access
> UR-151 Fix - Prevent Dashboard Access

- includes/class-ur-ajax.php
Previously, while sending a test email the Email sender option section value like From Address and Email are not showing instead WordPress core address and email is showing in reply. This PR will fix this issue.
1. Navigate to the User Registration settings and then to the Emails tab.
2. You can see the Email sender options and provide the desired "From" name and Address.
3. then In the Send Test Email to which address you want to send a test email. 
4. verify that the test email is from the saved email sender options in your received email address.
> Fix- Email sender option value while sending a test email.
> Fix- Email sender option value while sending a test email

- includes/abstracts/abstract-ur-form-field.php
- includes/class-ur-preview.php
- includes/class-ur-shortcodes.php
- includes/frontend/class-ur-frontend-form-handler.php
- includes/frontend/class-ur-frontend.php
- includes/functions-ur-core.php
- includes/shortcodes/class-ur-shortcode-login.php
- includes/shortcodes/class-ur-shortcode-my-account.php
This PR fixes issues arise after switching to PHP 8.0 from PHP 7.4.
1. Verify all features are working on supported PHP versions or not.
> Fix - PHP 8.0 compatibility.
> UR-221 Fix - PHP 8.0 compatibility

- includes/admin/class-ur-admin-user-list-manager.php
- includes/functions-ur-core.php
- templates/myaccount/navigation.php
Previously, When Customize my Account addon activated, My Account Translation of Menu and content not working. This PR fixes this issue.
1. Activate Customize my account addon.
2. Translate My Account Menu using WPML
3. Visit My Account in Frontend and change language check whether menu language translate or not.
> Fix - My Account translation issue.
> UR-195 Fix - My Account translation issue

- includes/class-ur-emailer.php
- includes/class-ur-form-handler.php
- templates/myaccount/form-edit-profile.php
When we enable conditional logic in profile pic in edit profile the profile picture can not uploaded. This issue has been fixed in this PR.
1. Goto form builder drag profile picture field. and save form.
2. After registration of user goto edit profile and try to change profile picture and click button save changes.
3. Here you can see the issue that uploaded picture not saved. this issue fixed in this PR.
> Fix - Profile Pic upload issue from edit profile.
> UR-243 Fix - Profile Pic upload issue from edit profile.

- includes/frontend/class-ur-frontend.php
Previously, When the user enable prevent core login and try to register or login from the LearnDash page then it did not register the user also not login.  It's redirecting to user registration myaccount page. This issue fixed in this PR.
1. Goto Learndash Settings and enable login and registration.
2. Goto User Registration settings and enable prevent core login.
3. Now go to the course and click on take this course button it will open the learndash model  login and registration.
4.  Try to login or register it should register or login. Previously it was redirecting to myaccount. This issue must fixed here.
> Fix - Learndash Login conflict with prevent core login feature.
> Fix - Learndash Login conflict with prevent core login feature.

- includes/class-ur-email-confirmation.php
- includes/class-ur-user-approval.php
- includes/functions-ur-template.php
This PR is dependency PR for https://github.com/wpeverest/user-registration-social-connect/pull/13 which introduce new feature social connect with login option.
1. Test this PR with  https://github.com/wpeverest/user-registration-social-connect/pull/13
> Dev - Social connect with login option.
> UR-298 Dev - Social connect with login option

- includes/admin/updater/class-ur-addon-updater.php
This PR fixes two issues:
1. Previously when we click on the view details link on the plugin row actions of our User Registration Plugin's addons from the plugins page then we would see a popup in which a plugin not found error was shown. This PR fixes this issue and displays the addon's information and Changelogs.
2. When we visit the add new plugin page then an error with the undefined Std::class $plugin appears which seems to be from WordPress core but was triggered by our incomplete configuration of addon updater using EDD. This PR also fixes this issue.
1. Activate our plugin using a valid license key.
2. Check to verify if the view details link in plugins row action for all addons is working as expected.
3. Check to verify if the undefined Std::class $plugin is not present on the …
> UR-325 Fix - View details link in plugins row action broken for addons

- assets/js/admin/form-builder.js
- assets/js/frontend/user-registration.js
This PR aims to introduce "Validate as unique" field settings for the first name, last name, email, URL, phone, and input fields currently.
1. Create a form.
2. Go to field settings and enable validate as unique.
3. Register the form and again try to Register it with a duplicate value. It will show the error message.
> Dev - Validate unique field compatibility.
> UR-272 Dev - Validate unique field compatibility

- assets/css/admin.scss
- assets/css/metabox.scss
- includes/abstracts/abstract-ur-meta-boxes.php
This PR provides the compatibility of the toggle option in the frontend listing custom post meta box.
1. Checkout to the branch of the frontend listing advance filter in the addon.
2. Verify if the toggle option is working properly.
> Dev - Frontend listing advanced filters compatibility.
> UR-315 Dev - Frontend listing advanced filters compatibility.

- .github/workflows/sync.yml
- includes/functions-ur-template.php
This PR refactors the existing code to remove the code to display field icons in frontend.
1. Create a form in **User Registration Pro** and enable field icons.
2. Revert back to **User Registration** and preview the form.
> Refactor - Remove field icon code
> UR-358 Refactor - Remove field icon code

- includes/frontend/class-ur-frontend-form-handler.php
- includes/functions-ur-account.php
This is a compatibility PR for Quantity Field. It adds a hook to insert values into the form data array.
Closes # .
1. Switch to this branch while testing Quantity Field PR.
> Tweak - add field data hook
> Tweak - Add field data hook

- includes/class-ur-email-confirmation.php
Previously, when the login option is set to admin_approval_after_email_confirmation, after the user confirms his email, the user was not being listed in the users table pending users list. This pr fixes the issue.
1. Set up login option and test.
> Fix - pending user not listed
> UR-418 Fix - Pending user not listed

- assets/js/admin/admin.js
- assets/js/frontend/user-registration.js
Previously, When validate unique field is enabled in the multipart form then validate unique field error message is not navigating to which part of the form occurred. This PR will fix this issue.
1. Navigate to the form builder and enable multipart and validate the unique field then update the form.
2. then go to the registration form and submit the form.
3. then verify whether validate unique field error message is navigating to the error message part of the form or not.
> Dev - Compatibility of validating unique field issues in multipart.
> UR-402 Dev - Compatibility of validate unique field issue in multipart

- assets/js/admin/form-builder.js
This is a dependency PR for Frontend Tooltip PR to add **_ur_field_removed_** trigger when a field is removed.
- https://github.com/wpeverest/user-registration-payments/pull/22
1. Switch to this branch when testing main PR.
> Fix - add field removed trigger
> UR-405 Fix - Add field removed trigger

- assets/js/frontend/user-registration-form-validator.js
In some theme quantity field is allowing to enter alphabets and it showing the error message that the value is invalid but the error message should be shown just below the quantity field but it's showing in new column.
1. Create a form with quantity field and preview form with twenty twenty theme.
2. Try to enter alphabets in the quantity field
3. check the validation message displayed in proper place or not.
> Fix - Misplaced error message for Quantity field.
> UR-409 Fix - Misplaced error message for Quantity field.

- assets/css/admin.scss
- assets/js/admin/admin.js
- assets/js/admin/settings.js
- includes/RestApi/class-ur-rest-api.php
- includes/abstracts/abstract-ur-form-field.php
- includes/admin/class-ur-admin-assets.php
- includes/admin/settings/class-ur-settings-email.php
- includes/admin/settings/class-ur-settings-general.php
- includes/admin/settings/class-ur-settings-integration.php
- includes/admin/views/html-admin-page-forms.php
- includes/form/settings/class-ur-setting-checkbox.php
- includes/functions-ur-core.php
Previously we have some text typos mistakes in our plugin. This PR will fix these mistakes.
1. Checkout to this branch and verify whether all the changes are reflected or not according to the change documents.
**Note**: Refer to the change documents for this.
> Dev - Change text typos and grammatical mistakes.
> UR-413 Dev - Change text typo and grammatical mistake

- includes/admin/class-ur-admin-menus.php
- includes/admin/class-ur-admin-notices.php
- includes/admin/class-ur-admin-welcome.php
- includes/admin/views/html-notice-custom.php
- includes/admin/views/html-notice-install.php
- includes/class-ur-install.php
- includes/functions-ur-core.php
- user-registration.php
When a new user skips onboarding, he has no other way to automatically create registration and my account pages, so we saw many users got confused here so we have to now revert back the install pages notice in a way that it will be only displayed to the users who have skipped onboarding. Also when a user selects other pages as my account instead of a page with our log in or my account shortcode or WooCommerce my account page, a notice should be displayed. This PR does this.
1. Create a new site or check on uninstall option in User Registration -> Settings -> Misc and uninstall the plugin and install it again.
2. Switch to this branch and Perform `npm run build` to build the getting started files in localhost.
3. Now once you activate the plugin you will be redirected to the getting …
> UR-419 Tweak- Install pages notice when onboarding skipped

- includes/class-ur-form-handler.php
When conditional logic applied to the required field and the field is hidden and when we try to save changes via post submission inn edit profile instead updating success it was throwing an error that the field is required. This issue is fixed in this PR.
https://github.com/wpeverest/user-registration-conditional-logic/pull/24
1. Disable Ajax submission on edit profile if enabled.
2. Create a form with required field and enable conditional logic to that field.
3. Register the user with that form and login.
4. In edit profile hide the required field via conditional logic and click the save changes button.
5. Check whether profile updated successfully or not.
> Fix - Post Submission issue in edit profile when conditional logic applied to required field.
> UR-397 Fix - Post Submission issue in edit profile when conditional logic applied to required field

- includes/shortcodes/class-ur-shortcode-my-account.php
This is a compatibility PR for two factor authentication addon. This PR adds hooks to render custom contents in the login or my-account shortcode.
1. Switch to this branch while testing Two Factor Authentication Addon.
> UR-430 Dev - Add hooks to render custom content
> UR-430 Dev - Add hooks to render custom content

- includes/admin/class-ur-admin-notices.php
- includes/class-ur-form-handler.php
- includes/functions-ur-core.php
This PR fixes the recent issue where a critical error was occurring while trying to approve a user by admin.
1. Test this PR with PHP below 8 and WordPress below 5.9 versions.
2. Register a user with admin approval as login option.
3. Try to approve the user from users page.
4. Also check if other user process are working properly.
> UR-537 Fix - Error when approving user
> UR-537 Fix - Error when approving user

- includes/admin/class-ur-admin-welcome.php
- includes/admin/class-ur-admin.php
- src/components/App.js
In Development Environment the Getting Started Page was getting stuck while onboarding process. This PR fixes this issue
1. In your development environment install and activate a fresh user registration plugin.
2. Click on Getting Started Button and verify whether all process are working or not.
> Fix - Getting Started Page not working in development environment.
> UR-477 Fix - Getting Started Page not working in dev environment.

- includes/admin/class-ur-admin-export-users.php
When User Registered with the field checkbox or multiselect2 and admin tries to export the user's data in CSV. it downloads CSV with error message. This PR fixes this issue. 
1. Register user with checkbox and multi-select2 fields.
2. Export User from Settings and verify whether CSV file having proper data or not.
>  Fix - User CSV export issue while checkbox or multi select2 exists in the form.
> UR-541 Fix - User CSV export issue while checkbox or multi select2 exists

- assets/css/admin.scss
Previously, delete popup modal was large, now this PR fixed this design issue.
1. Create a form.
2. Drag and drop the field.
3. Click the delete field button and verify the issue is fixed or not.
> UR-544 Fix - Delete popup modal for field design.
> UR-544 Fix - Delete popup modal for field design.

- assets/css/admin-rtl.css
- assets/css/admin.css
- assets/css/components/_modal.scss
- assets/css/user-registration-rtl.css
- assets/css/user-registration.css
1. Change cursor to pointer when hover over popup link in menu.
2. Fix popup modal top margin issue.
3. Position modal in center horizontally in small devices.
1. Create popup and add it to menu.
2. Verify whether popups are being displayed properly in all cases.
Since, popups are available only in **_user-registration-pro_**, switch to the following clone branch to test:
https://github.com/wpeverest/user-registration-pro/tree/fix/popup-design-issue-in-menu
> UR-507 Fix - Popup design issue in menu
> UR-507 Fix - Popup design issue in menu

- includes/abstracts/abstract-ur-list-table.php
Previously, When Form is created or updated then it is listed at the bottom of the table instead of first one. This PR will fix this issues.
1. Create a new form or update the existing the form.
2. then verify whether new created or updated form is sorted by updated date or not in the All forms table.
> Fix - Forms table sorting by latest update.
> UR-502 Fix - Forms table sorting by latest update 

- includes/functions-ur-core.php
This PR introduces tweaks on Submit Button Class, Submit Button Text and Form Class label and tooltip text.
1. Go to Form Settings, and verify whether these tweaks are valid or not.
> Tweak - Submit Button Class, Submit Button Text and Form Class label and tooltip text.
> Tweak - Submit Button Class, Submit Button Text and Form Class label and tooltip text.

- includes/class-ur-ajax.php
- includes/class-ur-form-handler.php
- includes/class-ur-frontend-scripts.php
- includes/form/class-ur-form-field-user-login.php
Previously, Settings > General > Login Options > Messages > 'Unknown Email' and 
Settings > General > Frontend Messages > ERROR MESSAGES > 'Special Character Validation in Username' messages were not working. This PR fixes this issue.
1. Verify 'Unknown Email'  message is working or not by submitting the login form.
3. Verify, 'Special Character Validation in Username' message working or not by submitting the form.
> Fix - 'Special Character Validation in Username' and 'Unknown Email' messages not working.
> Fix - 'Special Character Validation in Username' and 'Unknown Email' messages not working.

- includes/admin/class-ur-admin-notices.php
- includes/admin/class-ur-admin-settings.php
- includes/admin/class-ur-admin-status.php
- includes/functions-ur-page.php
Previously there is some error notice in PHP version 8.1.This PR fixes this isssue.
1. Test whether the User registration form is working properly or not.
> Fix - PHP 8.1 Compatibility issue.
> Fix - PHP 8.1 Compatibility issue

- assets/js/admin/form-builder.js
- assets/js/frontend/user-registration.js
- includes/admin/class-ur-admin-profile.php
- includes/functions-ur-template.php
Previously, there was flatpickr error in the console of the front-end form and profile details as well while selecting a date in the Date field. This PR fixes this issue.
1. Verify, there is no console error in the front end while selecting the date in the date field.
> Fix - Flatpickr throwing an error in console.
> Fix - Flatpickr throwing an error in console.

- includes/admin/class-ur-admin-export-users.php
- includes/admin/class-ur-admin-form-templates.php
- includes/functions-ur-core.php
- templates/myaccount/form-edit-profile.php
Previously, We have implemented Smart tags for all individual fields but there was issue in file upload field so this PR fixes this issue.
1. Drag File upload field in form and copy field_name and paste in any email which executes after registration such as admin email or successful registered email.
2. Now Register one user and check email whether uploaded file link is show over the smart tag or not.
> Smart tag issue for file in emails.
> UR-715 Smart tag issue for file in emails.

- assets/js/admin/form-builder.js
Previously, we do support the only currency supported by Paypal. This PR will support some extra currency. 
1.  Checkout out this branch and test all possible cases whether payment is working fine or not by changing the currency from global settings..
> Dev - Compatibility for unsupported currency validation message.
> UR-172 Dev - Compatibility for unsupported currency validation message

- assets/js/admin/form-builder.js
- includes/abstracts/abstract-ur-form-field.php
Previously, When the required option is set to yes then it required icon is not displaying properly. This PR will solve this issue.
1. Verify whether the required icon is working properly or not.
> Fix - Required icon not displaying properly.
> UR-792 Fix - Required icon not displaying properly.

- assets/js/admin/admin.js
- includes/admin/class-ur-admin-assets.php
- includes/class-ur-ajax.php
- includes/functions-ur-core.php
- includes/functions-ur-template.php
Previously, any level of users are able to send test email and unserialize functions below php v7.1 can cause PHP Object injection. This PR will this issue.
1. Verify only privileged users are able to send test email and that PHP Object Injection is prevented while updating the profile details.
> Fix - Vulnerability PHP Object injection and send test email by non privileged user.
> UR-798 Fix - Vulnerability PHP Object injection and send test email by non privileged user.

- includes/functions-ur-core.php
Previously, When fields are added or removed then conditional rules fields are not rendered dynamically we have to update the form in order to work and fields like radio, and checkbox fields option are also not rendering. This PR will fix these issues.
1. Create a new form or edit the existing form.
2. then go to form settings > Paypal standard or stripe payment then enable conditional logic.
3. add or remove form fields and field changes when fields are added or removed.
> UR-735 Fix - Strip Unwanted fields from conditional rules field.
> UR-735 Fix - Strip Unwanted fields from conditional rules field

- includes/stats/class-ur-stats.php
This PR adds setting keys to the stats file.
Closes https://themegrill.atlassian.net/browse/UR-719
Verify if data are being processed properly.
> UR-719 Enhance - Add global settings
> UR-719 Add - Global Settings

- assets/js/admin/form-builder.js
- assets/js/frontend/user-registration.js
- templates/form-registration.php
This is a dependency PR for the [PR](https://github.com/wpeverest/user-registration-conditional-logic/pull/27).
> Dev - Dependency for conditional logic for the submit button.
> Dev - Dependency for conditional logic for the submit button.

- assets/js/admin/form-builder.js
- includes/admin/class-ur-admin-assets.php
- includes/class-ur-ajax.php
- templates/myaccount/form-edit-profile.php
This is the dependency PR for [Profile Completeness](https://github.com/wpeverest/user-registration-profile-completeness/) Addon.
> Dev - Dependency for Profile Completeness.
> Dev - Dependency for Profile Completeness

- includes/admin/class-ur-admin-export-users.php
This PR has fixed the missing user id while exporting users.
1.  Goto settings
2.  Goto export/import
3. Try to import the user and check the additional fields.
>Fix - Missing user id in export user
> Fix - Missing user id in export user

- includes/class-ur-form-handler.php
Previously there was no filter to change the recaptcha URL. This Pr adds the filter to add the URL.
1.  Create a form with recaptcha.
Please add the code in the function.php 
add_filter('user_registration_recaptcha_domain', 'recaptcha_domain_change');
function recaptcha_domain_change($url)
{
$url = '"https://www.recaptcha.net/recaptcha';
return $url;
}
2.  Verify the recaptcha is working properly or not
> Tweak - Filter added for recaptcha url.
> Tweak - Filter added for recaptcha url.

- assets/js/frontend/password-strength-meter.js
- includes/admin/class-ur-admin-assets.php
- includes/class-ur-frontend-scripts.php
Previously the password strength criteria for a strong password should have been 9 characters instead of 8 characters and in the case of weak, medium, and strong passwords there shouldn't be any repetitive words or common words if there were any then even if our criteria for strong password meet it was still a weak password. So the description text has been tweaked a little bit in this PR to clarify users more on the criteria.
for eg. Passwords like Happy@123 meet our criteria for strong passwords i.e. Minimum of one uppercase, a number, a special character, and must be 9 characters but since Happy is a common word it is not accepted as a strong password. Instead, Happay@12 is a strong password because Happay is not a common word. 
1. Check if the password hint description has been …
> UR-975 Tweak - Password strength meter hint text

- includes/functions-ur-template.php
This PR changes the way redirection works for autologin. Previously, if autologin is set as the login method, redirection methods would not work. Now, all the redirection after registration methods will work.
1. Test all redirection options.
> Tweak - Redirection for autologin registration
> UR-972 Tweak - Redirection for autologin registration

- includes/abstracts/abstract-ur-session.php
- includes/admin/class-ur-admin-import-export-forms.php
- includes/admin/functions-ur-admin.php
- includes/admin/updater/class-ur-addon-updater.php
- includes/class-ur-ajax.php
- includes/class-ur-session-handler.php
- includes/functions-ur-core.php
- templates/form-registration.php
Previously, Arbitrary files are being uploaded which leads to injecting malicious code. This PR will fix this issue.
1. Create an arbitrary file and test all possible ways to prevent vulnerability in the plugin.
For reference: Please go through the video shared in our internal team.
> Fix - Vulnerability issue to arbitrary file upload
> Fix - Vulnerability issue to arbitrary file upload

- includes/functions-ur-template.php
This PR fixes the redirection while revisiting the registration and login page (by using shortcode user_registration_login) after the login or registration.
1.Check the all the possible options of  redirection after login and after registration.
> Fix - Registration page getting redirected.
> Fix - Registration page getting redirected

- includes/class-ur-smart-tags.php
This PR is adding a Unique id {{unique_id}} smart tag.
1. Create a form
2. Drag the input field and insert a unique ID smart tag as the default value or Insert a unique ID in the email content from the email global setting
3. Verify it.
> Enhancement - Unique id smart tag.
> Enhancement - Unique id smart tag

- assets/css/deactivation-feedback.scss
- includes/admin/class-ur-admin-deactivation-feedback.php
- includes/admin/views/html-deactivation-popup.php
This PR will enhance the deactivation item list with feedbear link and contact support and documentation.
1. Switch to this PR and verify whether links are redirecting properly.
> Tweak - Revamp deactivation pop items
> UR-903 Tweak - Revamp deactivation pop items

- includes/class-ur-emailer.php
- includes/class-ur-form-handler.php
- includes/functions-ur-page.php
The Login link now redirects to the first post on the main page rather than the login page. It worked before the v3.0.3 update.
Here is the code snippet.
https://docs.wpuserregistration.com/docs/how-to-add-login-logout-link-in-navigation-menu-programmatically/ 
1. Add this code snippet and check whether the code snippet works properly or not.
> Fix - Invalid Myaccount link for its endpoints.
> UR-1132 Fix - Invalid Myaccount link for it's endpoints .

- includes/functions-ur-core.php
This PR adds two links in the admin bar menu.
1. New Form -> Add new form page link
2. Edit Form -> Edit the current page form link
1. Test if the links are working properly on different conditions.
> UR-1059 Enhance - Links in admin bar menu
> UR-1059 Enhance - Links in admin bar menu

- assets/js/admin/form-modal.js
- includes/admin/class-ur-admin-menus.php
This PR fixes a bug where the Select All link in **User Registration Endpoints** section in Menus page was not working.
1. Check if the issue is fixed.
> UR-576 Fix - Select All button not working in Nav Menus
> UR-576 Fix - Select All button not working in Nav Menus

- assets/js/admin/admin.js
- includes/class-ur-email-approval.php
- includes/class-ur-emailer.php
Previously, there was no option for "Send User Approval Link in Email" on individual form settings that did not allow the sending of email with approve link to admin after user registration.
1. Go to User Registration > All Forms > Individual Form > Form Settings.
2. Select "Admin approval after email confirmation" option under 'User Approval and Login Option' and toggle "Send User Approval Link in Email".
3. Check whether both Confirmation email is sent to user and email with Approval link is sent to Admin after registration.
> Enhance - Send user approval link also in admin approval after email confirmation
> UR-1174 Enhance - Send user approval link also in admin approval after email confirmation

- includes/admin/class-ur-admin-menus.php
- includes/admin/class-ur-admin-status.php
- includes/admin/views/html-admin-page-status-logs.php
- includes/functions-ur-core.php
- includes/log-handlers/class-ur-log-handler-file.php
- user-registration.php
Previously, if any fatal error occurs we have debug every plugin file to find the issue. Now we any fatal error occurs it will log in log file and we can view it in log tab. also delete all logs button will be there which delete the all log files.
1. Make any syntax error in code which throws the fatal error.
2. Go to Tools->log tab check whether fatal error is listed in the file or not.
3. Check Delete All logs button working properly or not.
> Enhance - log all fatal errors and delete all logs option
> UR-805 Enhance - log all fatal errors and delete all logs option

- includes/form/class-ur-form-field-checkbox.php
- includes/form/class-ur-form-field-country.php
- includes/form/class-ur-form-field-date.php
- includes/form/class-ur-form-field-number.php
- includes/form/class-ur-form-field-password.php
- includes/form/class-ur-form-field-radio.php
- includes/form/class-ur-form-field-text.php
- includes/form/class-ur-form-field-user-email.php
- includes/form/class-ur-form-field-user-login.php
Previously, Backend validation of field error message is shown at the top of the form. This PR will enhance the validation error message to the bottom of individual fields.
1. Check out this branch and verify whether the backend validation is showing at the bottom of individual fields or not.
> Tweak - Validation error message in fields.
> Tweak - Validation error message in fields.

- assets/js/admin/form-builder.js
- includes/class-ur-shortcodes.php
This is dependency PR for the form restriction addon. Form restriction addon gives new features to restrict the form before loading on the basis of some rules.
1. User registration pro > switch UR-1031-dev/form-restriction-addon (this branch is also in pro)
2. Clone the user-registration-form-restriction addon https://github.com/wpeverest/user-registration-form-restriction, install and active
3. Go to form settings set conditions and verify accordingly.
Follow the Jira ticket -> https://themegrill.atlassian.net/browse/UR-1032
> Dev - Form restriction addon.
> Dev - Form restriction addon

- assets/js/frontend/user-registration.js
This PR is compatibility for Displaying payment status in detailed in or new Users details sections. 
Stripe - https://github.com/wpeverest/user-registration-stripe/pull/32
Payments - https://github.com/wpeverest/user-registration-payments/pull/34
Pro - https://github.com/wpeverest/user-registration-pro/pull/289
1. Test above dependency PR's 
> Enhance - Display payment status in detailed.
> UR-1235 Enhance - Display payment status in detailed.

- assets/js/admin/admin.js
- includes/admin/class-ur-admin-assets.php
- includes/admin/class-ur-admin-registrations-table-list.php
- includes/class-ur-ajax.php
This PR adds a Locate feature that lists the pages where a particular form is used.
1. User Registration > All Forms.
2. Click the Locate link under Form Name.
3. Check whether correct pages where the particular form is located is given.
> Feature - Form Locate.
> UR-1045 Feature - Form Locate.

- includes/admin/settings/class-ur-settings-email.php
- includes/admin/settings/emails/class-ur-settings-admin-email.php
- includes/admin/settings/emails/class-ur-settings-approval-link-email.php
- includes/class-ur-emailer.php
- includes/class-ur-preview.php
Previously, the approval link was not sent on the email when some changes is done of the email body section and pressed the save changes button. Now, we have added the field for enabling or disabling the approval link being sent on email where we can attach the approval link on our email being sent on user registration to the admin. 
1. Create a user registration form
2. Go to (UR) Settings->Email
3. Enable the toggle for **Admin Approval Request Email with Approval Link** and click on **configure**
4. Modify the text for the Email Content 
5. Click on Save Changes button
6. Register a user
7. Check if approval is being sent on your/admin email address for new user registration
8. Disable the Send User Approval Link in Email on Form Setting and check whether the approval link is being …
> UR-1228 Tweak - Need enhancement in send user approval link in email option

- includes/class-ur-emailer.php
- includes/class-ur-smart-tags.php
Previously {{approval_link}} smart tag was only working with Admin Approval Request Email and Admin Approval Request Email with Approval Link but not with Email Verified - Awaiting Admin Approval Email. As this email is also sent to admin after the user verifies the email, the {{approval_link}} should work here as well. This PR provides this feature. 
1. Check whether or not {{approval_link}} smart tag is being parsed properly in  Email Verified - Awaiting Admin Approval Email.
> Tweak - Parse approval link smart tag properly
> UR-1306 Tweak - Parse approval link smart tag properly

- includes/admin/class-ur-admin-user-list-manager.php
If the registered number of users is big then a very heavy query will run for fetching pending users which has affected the performance of the site for some users. This PR is replacing WordPress user query with a raw SQL query to optimize the performance. 
1. Check if pending users before and after the branch switch are the same.
2. Check if the pending user query performs well.
> Tweak - Pending users meta query optimization.
> UR-1286 Tweak - Pending users meta query optimization

- includes/admin/class-ur-admin-user-list-manager.php
Previously, When User Profile details were updated by the admin then approved email was sent. This PR will this issue.
1. switch to this branch and update the profile details of user from users table.
2. verify whether it is working properly or not.
> Fix - Welcome email sent when profile details updated by admin.
> Fix - Welcome email sent when profile details updated by admin

- assets/js/admin/form-builder.js
- assets/js/frontend/user-registration-form-validator.js
- includes/validation/class-ur-form-validation.php
Previously, Number field does not support decimal values. This PR will fix this issue.
1. switch to this branch and verify whether it is working as expected or not.
> UR-1296 Fix - Support decimal value in the number field.
> UR-1296 Fix - Support decimal value in number field

- includes/class-ur-smart-tags.php
- includes/functions-ur-core.php
- templates/myaccount/dashboard.php
Previously smart tag was not parsable in our endpoint contents. Now this PR provides this support also dashboard content has been converted into combination of texts and smart tags.
1. Switch to this branch and go to the dashboard endpoint of my account.
2. Verify if dashboard endpoint content is being displayed properly.
3. Also verify if our other endpoint contents like edit-profile form, change-password form are unhindered by this PR.
> Enhance - Smart tags parseable endpoint content
> UR-1302 Enhance - Smart tags parseable endpoint content

- includes/functions-ur-template.php
- includes/interfaces/class-ur-log-handler-interface.php
- includes/shortcodes/class-ur-shortcode-login.php
- includes/shortcodes/class-ur-shortcode-my-account.php
- includes/stats/class-ur-stats.php
This PR will enhance the code comments more descriptively and provide more information about the action and filter is about.
1. Just check if the comments are relevant for the functions, actions, and filters or not.
> Tweak - Code comments made more descriptive.
> Tweak - Code comments made more descriptive

- includes/validation/class-ur-form-validation.php
Closes # .
1. Go to form builder apply field visibility on fields and update the form.
2. Register and login the registered user and try to update the profile.
3. verify whether it is working properly or not.
> Fix - Validation error while profile update if field visibility is applied on fields.
> Fix - Validation error while profile update if field visiblity is applied on fields.

- includes/class-ur-emailer.php
Previously, default WordPress email was sent on the Reset Password Email. Now, we have added the feature to send the reset password email according to the email template selected and the email content according to our UR email. 
Closes # .
1. Switch to this branch
2. Go to User Registration > Settings from the Admin dashboard menu
3. Go to Emails
4. Enable the toggle button for Reset Password Email
5. Click on the settings wheel option if you want to modify the Email Subject and Email Content
6. Click on Save Changes button
8. Now, go to Users from Admin dashboard menu
9. Click on Send password reset link
10. Finally, verify if the email subject and content is correct or not. And if you have selected some email template then verfiy if it is working fine or not.
11. Also to check this …
> Tweak - Send user registration email template while sending reset password email from admin area

- includes/class-ur-user-approval.php
- includes/functions-ur-core.php
Previously, when user registered with Paypal subscription and not completed payment, then while login it throws critical error.
1. Register user with Paypal subscription and don't complete payment.
2. Now login option is Payment before login. User should not login and user should get error message.
3. Verify it working or not.
> Fix - Critical error while trying to login when using payment before login option.
> UR-1389 Fix - Critical error while trying to login when using payment before login option

- assets/js/admin/form-builder.js
Previously there is not available of the enable trail period in each of the subscription plan. This PR ensures that there is availability of the trail period in which user can give trail period as necessary.
UR Stripe Dependency - https://github.com/wpeverest/user-registration-stripe/pull/41 
UR Pro Dependency - https://github.com/wpeverest/user-registration-pro/pull/352
1. Activate the stripe addon. Enable the stripe payment and recurring subscription payments from form settings.
2. Add the subscription plan and stripe gateway field.
3. Enable the trail period for any plan in options of general setting.
4. Register user with one of the subscription plan to which trail period is enabled.
5. In another window, login that user, check whether trail period is enabled or not in payment …
> Added - Dev Compatibility for Subscription Plan trail period.

- assets/js/frontend/user-registration.js
PR Dependency: https://github.com/wpeverest/user-registration-woocommerce/pull/43 and https://github.com/wpeverest/user-registration-advanced-fields/pull/70
Previously there was no option in general setting to make  billing phone smart. This PR introduce option to make it smart
1.Add a billing phone filed in a form and go to filed option
2.if advanced filed is activated you should see a Select Format in general setting else option should not be shown
> Dev Compatibility - Added smart phone number in billing phone number.
> UR-1273 Feature - Added smart phone number in billing phone number.

- includes/admin/class-ur-admin-user-list-manager.php
Previouly, there is All UR Forms which shows all users. This PR ensures that All Sources show all users and All UR Forms show user registered from user registration plugin.
Closes # .
1. Open your Wordpress dashboard.
2.  Go to Users menu.
3.  There is filter at right corner.
4.  Select All UR form from dropdown then apply filter.
5.  It will show all the users registered from User registration plugin.
>  Change the 'All UR Forms' filter name to 'All Users' at Users > All Users
> UR-1412 Fix  Change the 'All UR Forms' filter name to 'All Users' at Users > All Users

- includes/functions-ur-page.php
Previously, the function "ur_get_my_account_url" returned my-account url without a trailing slash when custom permalink without a trailing slash was saved. This PR fixes this issue. 
Closes # .
1. Go to Settings > Permalink > Custom Structure > Remove trailing slash and save.
2. Go to Profile Details and Update the email for normal user.
3. Check the email and verify whether the email is changed and redirected to my-account/edit-profile.
> Fixed - My Account URL issue on custom permalink.
> Fixed - My Account URL issue on custom permalink.

- includes/class-ur-email-confirmation.php
- includes/functions-ur-core.php
- includes/shortcodes/class-ur-shortcode-my-account.php
This PR introduces a new feature to automatically login users after email confirmation and reset password actions.
1. Register a user using Auto approval and Email Confirmation Form Setting.
2. Confirm the email and verify if the user is logged in and redirected to My Account page.
3. Further, Logout the user and during login Click 'Lost your Password'.
4. Change your password and verify if the user is logged in and redirected to My Account page.
5. Note: Auto Login is default for Email Confirmation but snippet should be added for Reset Password. 
6. Use this code snippet for login on reset-password: https://snipsave.com/user/ranjankhanal/snippet/9KyEFY6WxTjnUFE97n/
> Feature - Automatic user login after email confirmation and reset password.
> Feature - Automatic user login after email confirmation and reset password.

- assets/js/frontend/user-registration-form-validator.js
Previously, when a required field was hidden conditionally, the form showed error message and was not submitted. This PR fixes  the issue.
1. Drag any of fields and make it required.
2. Apply conditional logic on those fields.
3. See if the form is submitted smoothly.
> Fix - Required Field error message for conditionally hidden fields.
> Fix - Required Field error message for conditionally hidden fields.

- includes/class-ur-emailer.php
- includes/functions-ur-core.php
Previously, When email sent to user through the admin action such as approval, denied, pending etc. In these email content was sent with admin set default language no matters from which language user is registered. 
In this PR, We are sending email content on the basis of language selected user while registration.
1. Translate Emails in different languages using polylang or WPML.
2. Register user ( eg. Hindi Langauge ) user email will be in the Hindi language.
3. Goto Admin-> Users list. Now approve this user. Email content to the user should be in Hindi Language.  
> Enhance - WPML email translation with user-selected language.
> UR-1526 Enhance - WPML email translation with user selected language.

- assets/js/admin/form-builder.js
- includes/admin/class-ur-admin-assets.php
- includes/class-ur-email-confirmation.php
1. `for document refer `https://docs.everestforms.net/docs/google-sheets/
2.`redirect url` should be till integration tab i.e s https://example.com/integration/
>Dev -Dependency for google sheets
> UR-1454 Dev -Dependency for google sheets

- assets/css/admin-rtl.css
- assets/css/admin.css
- assets/css/admin.scss
- assets/js/admin/admin.js
- includes/frontend/class-ur-frontend-form-handler.php
- includes/functions-ur-core.php
This PR introduces the new spam dictation using Aksmet feature.
1.`Install` and `Activate` aksmet plugin
2.Configure aksmet api in aksmet plugin 
3.`form-settings` => `General` enable `Activate Spam Protection By Akismet`
4.Register a form 
[`Note`: for spam content refer `https://akismet.com/support/getting-started/confirm/`]
> Feature - Akismet  integration
> UR-1483 Feature - Akismet  integration

- includes/admin/class-ur-admin-assets.php
- includes/admin/functions-ur-admin.php
- includes/class-ur-frontend-scripts.php
Optimization of styles and script by enquing  only to the required files and tabs. 
1.Activate and verify styles and scripts are only enqueed in required files or tabs. 
> Optimization-Scripts and styles optimization.
> UR -1552 Optimization -Script and styles optimization.

- includes/validation/class-ur-setting-validation.php
- includes/validation/class-ur-validation.php
- templates/myaccount/form-login.php
.**Previously only absolute URL was accepted in Registration URL . This PR ensures relative URL support if page exists**
1. **Navigate to the Settings Page:**   
- Click on **Settings > General > Login Option**.  
- Locate the **Registration URL** field.
2. **Verify the URL in the Registration URL Field:**
- **Absolute URL:** Ensure that the URL entered is a valid absolute URL. If the URL is not valid, display an error message and prevent the settings from being saved.
- **Relative Path:** If a relative path  is entered, ensure that the path corresponds to an existing page . If the relative path does not exist, display an error message and prevent the settings from being saved.
> Feature - Support relative URL
> UR- 960 Enhance - Support relative URL 

- includes/admin/functions-ur-admin.php
- includes/admin/notifications/class-ur-admin-notices.php
Previously we implemented the custom notices with different conditions but there were such cases where we needed to call the function instead database query. In this PR I have implemented this to handle common functions with different operators Also Dynamic link in the button suppose you want to show the admin URL in the button now it's possible.
1. Change the notice in a specific format and check whether your condition matches or not the notice is displayed properly.
> Dev - Handle common functions and dynamic links for custom notices.
> UR-1756 Dev - Handle common functions and dynamic links for custom notices.

- includes/frontend/class-ur-frontend-form-handler.php
- includes/validation/class-ur-form-validation.php
Fields were in random order when using the smart tag {{all_fields}} during registration. Fixed this issue in this PR.
Closes # .
1. Add the {{all_fields}} smart_tag in the registration email template.
2 Check if the form fields appear in respective order.
- Bug - Fix for random order in email of form inputs during user registration
> UR 1879  Bug - Fix for random order in email of form inputs during user registration

- assets/css/user-registration.scss
- includes/3rd-party/oxygen/class-ur-oxygen.php
- includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-editpassword.php
- includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-editprofile.php
- includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-login.php
- includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-myaccount.php
- includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-popup.php
- includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-profile-details.php
- includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-registration.php
- includes/3rd-party/oxygen/widgets/class-ur-oxygen-widgets.php
- user-registration.php
Closes # .
Dependency for https://github.com/wpeverest/user-registration-pro/pull/505
> Dev - Page builder compatibility oxygen
> UR-1864 Dev - Page builder compatibility oxygen

- includes/class-ur-form-handler.php
1.Login into different browser with same account and change password form one and verify all connected accounts are logged out.
> Feature -Force user logout on password change
> UR - 1590 Feature -Force user logout on password change

- assets/js/frontend/user-registration-form-validator.js
- includes/form/class-ur-form-field-user-login.php
- includes/form/settings/class-ur-setting-user_login.php
- includes/frontend/class-ur-frontend-form-handler.php
Previously, Username accept  [ @  .   -  _  ], This PR solves this issue.
1. Open registration form.
2. Include special characters  in username and submit.
3. Check user created or not.
> Fix - Username accepting some special characters
> Fix - Username accepting some special characters

- includes/functions-ur-core.php
When user used template overriding through theme on my account page, the lost password url went wrong and was not working properly.
DGB Mata Theme: https://themegrill.atlassian.net/browse/UR-1866?focusedCommentId=24214
1. Install the dgb-mata theme create a page and set it empty and select Login template from right sidebar.
2. Select the page as our My Account Page.
3. In frontend check whether lost password and other endpoints work properly.
> Added - Check for UR my account and login in custom template.
> Added - Check for UR my account and login in custom template.

- assets/js/frontend/user-registration.js
Closes # .
Previously when WYSWYG field is made required. This field is required error was throwing even filled with value
1.Make WYSWYG  field required and verify if proper validation in client side
2.
3.
> Bug - Issue while making WYSWYG required
> UR-1519 Bug - Issue while making WYSWYG required

- includes/class-ur-email-confirmation.php
1. Check for email marketing addons whether after email confirmation user registration data is sent.
2. Check for ActiveCampaign and others.
> Added - Hook before automatic user login after email confirmation.
> Added - Hook before automatic user login after email confirmation

- includes/class-ur-emailer.php
Simplified Registration Email Flow.
Pro dependency: https://github.com/wpeverest/user-registration-pro/pull/520
Closes # .
1. Both on free and pro using different login options from form settings, Register a user.
2. Check if all the required emails are sent correctly and in flow to both admin and users.
3. Comment if anything looks off or out of flow.
> Tweak - Email sent to users and admin on registration.
> Fix - Status changed to pending mail on registration.

- includes/RestApi/controllers/version1/class-ur-modules.php
- includes/stats/class-ur-stats.php
Previously, TG User Tracking only track addons, This PR add feature to track module activation.
1. Install TG User Tracking plugin in new site( not localhost ).
2. Intsall User Registration Pro in another new site.
3. And activate module and look on TG User Tracking (First Site) whether module is list or not.
4. You need to install Adminer plugin to import sql file.
5. On first site where you have installed TG Tracking, you need to remove some code if your second site is taste.wp.
Note: Zip are in zira ticket [Ticket](https://themegrill.atlassian.net/browse/UR-1920). You need to change site url in User Registration Pro plugins from plugin editor.
REMOTE_URL = 'yoursite.com/wp-json/tgreporting/v1/process-premium/'
> Enhancement - Send active modules count like addons in tg tracking
> UR-1920 Enhancement - Send active modules count like addons in tg tracking

- assets/js/frontend/user-registration-form-validator.js
- includes/class-ur-frontend-scripts.php
This PR introduces the filter hook 'user_registration_checkbox_validation_message' to modify the checkbox validation message.
Closes # .
1. Use this filter 'user_registration_checkbox_validation_message' to modify the checkbox validation message content and check whether it is working accordingly or not.
> Tweak - Hook to modify checkbox validation message.
> Tweak - Hook to modify checkbox validation message.

- includes/functions-ur-template.php
Previously, in the text area field of User resgitration the text count was not translated into other languages. This PR fixes this issue.
Closes # .
1. Drag and drop the text area field.
2. Translate the character or word count text in the text area field and check whether it is working as expected or not.
> Fix - Translation issue in text area field.
> Fix - Translation issue in text area field.

- assets/js/frontend/user-registration.js
Previously, there was no trigger to modify the process while the form is being submitted. This PR adds the trigger to add custom JS code while the form is being submitted and after the form submission completes. This PR also adds the trigger for edit profile.
Closes # .
1.Create a custom function the js events user_registration_before_form_submit_completion and user_registration_after_form_submit_completion.
2. Similarly, for the edit profile: **user_registration_process_before_edit_profile_submit_completion** and **user_registration_process_after_edit_profile_submit_completion**
2.Check whether the event is working as expected or not.
> Tweak - My account page popup trigger and trigger form modal popup.
> Tweak - My account page popup trigger and trigger form modal popup.

- includes/admin/class-ur-admin-export-users.php
Previously, in our User Registration if we export large amount of users then the critcal error was thrown. This PR fixes this issue.
Closes # .
1. You need to have large amount of users in your database.
2. Go to **User Registration & Membership > Settings > Import/Export > Export Users**
3. Select the desired form to export the user and click on **Export Users** button.
4. Now check whether the critical error is thrown or not.
> Fix - Critical issue while exporting large amount of entries.
> Fix - Critical issue while exporting large amount of entries.

- assets/js/admin/form-builder.js
- includes/functions-ur-core.php
- includes/functions-ur-template.php
Calculation addons changes require for free version.
Closes # .
1. Checkout the[ calculation PR](https://github.com/wpeverest/user-registration-pro/pull/501) in pro for more.
- Feature - Compatibility changes free version for calculations
> UR 1859  Feature - Compatibility changes free version for calculations

- includes/admin/class-ur-admin-export-users.php
- includes/admin/class-ur-admin-profile.php
Previously, in User registration while using the Field Visibility with default value and its visibility only in the Profile Details, then while viewing the detail from the Admin dashboard those hidden fields values where not displayed. This PR fixes this issue.
Closes # .
1. Enable the Field Visibility module
2. Create a form with default value but visible only in the Profile Details
3. Now check whether the details are displayed accordingly or not in both User Registration > Users > Entry and Users > User Entry.
4. Also check while exporting the users entry.
> Fix - User entries details on import export and on admin dashboard while using field visibility.
> Fix - User entries details on import export and on admin dashboard while using field visibility.

- assets/js/admin/settings.js
There was JS issue on the Settings my account page while trying to assign.
Closes # .
1. Go to URM > Settings > General > 
2. Assign My Account Page and check whether it is assigning or not and also check if there is JS issue or not.
> Fix - Issue while assigning my account page in settings.
> Fix - Issue while assigning my account page in settings.

- includes/class-ur-smart-tags.php
This PR fixes the plugin conflict with YITH multi-vendor plugin.
Closes # .
1. Install and activate YITH multivendor plugin.
2. Go to YITH > Vendor > Vendor List > click on Add vendor button
3. Check whether the Add vendor button is clickable or not.
[Link to download YITH plugin](https://files.fm/u/hxtxqarewk)
> Fix - YITH multi vendor conflict.
> Fix - YITH multi vendor conflict.

- includes/functions-ur-core.php
This feature enhances the role based redirection conditionally for the passwordless login.
Closes # .
1. Refer to this doc for the role based redirection : [Role based redirection](https://docs.wpuserregistration.com/docs/role-based-redirection/)
2. Refer to this doc for the passwordless login [Passwordless Login](https://docs.wpuserregistration.com/docs/login-options/#0-toc-title)
3. Check whether it is working accordingly or not.
> Enhance - Compatibility of passwordless login and role based redirection.
> Enhance - Compatibility of passwordless login and role based redirection.

- assets/css/user-registration.scss
- assets/js/frontend/user-registration.js
- includes/class-ur-email-confirmation.php
This PR adds a success message that is displayed when the user clicks the confirmation link in the registration email.
Closes # .
1. Go to **URM > All Forms > Select a form or create a new one**. 
2.  Got to **Form Settings > General** > Select **Auto Approval after email confirmation** under **User Approval and Login option** dropdown.
3. Click on **Update Form** button.
4. Now perform the registration process and confirmation email will be sent on user's email.
5. Click on the **Click Here** link from the email
6. After this user must be redirected to the My account page with toast message of User registration successfully.
> Enhancement - Displays the sucess message after confirming registration through email.
> Enhancement - Displays the sucess message after confirming registration through email.

- includes/functions-ur-core.php
While using the {{all_fields}} smart tag on **Email Verified - Awaiting Admin Approval Email** it was not working. This PR fixes this issue.
Closes # .
1. Enable the **Email Verified - Awaiting Admin Approval Email** and use {{all_fields}} smart tag in the email content
2. Go to **URM > All forms > Select an existing form or create a new one**.
3. Then Go to **Form Settings > Select** **Admin approval after email confirmation** for User Approval and login Option.
4. Click on **Update Form** button.
5. Perform the entry and check whether **all_fields** smart tag is working or not.
> Fix - All field smart tag not working in admin verified email.
> Fix - All field smart tag not working in admin verified email.

- .github/sync-file-list.yml
- .github/workflows/sync.yml
- assets/js/admin/enhanced-select-custom.js
- includes/admin/class-ur-admin-assets.php
- includes/admin/class-ur-admin-menus.php
- includes/functions-ur-core.php
Closes # 
Previously, the Black Listed fields was not appearing for the draft elements and was only visible for the Published form.
Now the blacklisted fields appear for draft form as well. The black list form now is dynamic and shows realtime fields of the form.
Screenshot:
1. Create a new form
2. Go to the Form Settings > Extra > Black listed fields
3. Go to the Drop down of the black listed fields
4. Blacklisted Fields should appear
5. Blacklisted Fields should have the fields provided in the form
> UR-1887 : Updated blacklist field for unplublished form

- includes/class-ur-smart-tags.php
While using the check_box_uniqid smart tag in the email content for **Email Verified - Awaiting Admin Approval Email**, it was not parsing the smart tag values in email content. This PR fixes this issue.
Closes # .
1. Create a form using the checkbox.
2. Copy the id of that field and create the smart tag as {{copied_id}} in the Email content for **Email Verified - Awaiting Admin Approval Email**
3. Now register the user having **Admin Approval after email confirmation** and check the email content received for the admin after approval.
> Fix - Check box smart tag not working for Email Verified - Awaiting Admin Approval Email.
> Fix - Check box smart tag not working for Email Verified - Awaiting Admin Approval Email.

- assets/js/modules/membership/admin/membership-groups.js
- modules/membership/includes/Admin/Forms/Views/admin-membership.php
- modules/membership/includes/Templates/membership-registration-form.php
Reverts wpeverest/user-registration#832
> Revert "Ur 2144 conditional logic based on membership plans in membership field"

- modules/membership/includes/Admin/Services/EmailService.php
- modules/membership/includes/Admin/Services/OrderService.php
- modules/membership/includes/Admin/Services/Paypal/PaypalService.php
- modules/membership/includes/Admin/Services/SubscriptionService.php
- modules/membership/includes/Templates/Emails/payment-successful-email.php
Paypal Payment issues.
* Duration showing daily even when selected other fixed.
* Payment amount mismatch due to number_formar fixed.
* Incorrect Next billing date fixed.
Closes # .
1. Register a new user with subscription type membership form using paypal.
2. See if all these above fixes work.
Fix - Membership paypal payment issue
> UR 2265 Fix - Membership paypal payment issue

- includes/functions-ur-core.php
- includes/validation/class-ur-form-validation.php
- wpml-config.xml
Some texts were missing in the WPML string translation. This PR adds those additional strings.
Closes # .
1. Use the WPML String translation for email messages and error message which arte listed in the wpml-config.xml.
> Dev - Added string for wpml translation.
> Dev - Added string for wpml translation.

- includes/class-ur-ajax.php
- includes/class-ur-preview.php
- includes/frontend/class-ur-frontend-form-handler.php
- modules/membership/includes/AJAX.php
Checked user privilege as well as checked urm_user_just_created meta for validating users who are just registering.
Closes # .
1. Check this ticket https://helpdesk.themegrill.com/conversation/30842?folder_id=107 for testing.
Security - vulnerability fix reported by Wordfence.
> Ur-2324 Security - vulnerability fix reported by Wordfence.

- templates/myaccount/form-lost-password.php
This PR adds the hook to modify the Lost Password input placeholder.
Closes # .
1. Use the hook **user_registration_lost_password_user_login_placeholder** to modify the placeholder text of the lost password page input field.
2. Go to lost password page and check the placeholder text.
> Dev - Hook to modify lost passwors form placeholder.
> Dev - Hook to modify lost passwords form placeholder.

- assets/js/frontend/user-registration.js
This PR fixes the registration form validation while using the registration form through shortcode in Elemenor.
Closes # .
1. Create a popup that opens while clicking the link: refer to this doc [Link Popup](https://elementor.com/help/how-to-trigger-a-popup-from-a-nav-menu-item/)
2. Now open the site and check whether the registration form validation is working or not.
> Fix - Registration Form validation for elementor popup.
> Fix - Registration Form validation for elementor popup.

- assets/js/admin/login-settings.js
- includes/functions-ur-core.php
- templates/myaccount/form-login.php
This PR adds the feature to customize the Login Form title and description.
Closes # .
1. Go to URM Global Settings > Login Options > General
2. Enable Login Title
3. Enter the text for **Login Form Title** and **Login Form Description**
4. Click on **Update Form** button
5. Check the Login Form title and description on the frontend.
> Feature - Customize login form title and description.
> Feature - Customize login form title and description.

- assets/css/variables/_colors.scss
This PR updates the icon and the background color for the login with twitter option in social connect.
Closes # .
1. Grunt the CSS
2. Enable the Social login option and setup the twitter API setups.
3. Check the icon and the background color of Login with Twitter button in Login page.
[URM Social Connect PR Depenedency](https://github.com/wpeverest/user-registration-social-connect/pull/28)
> Tweak- Change twitter icon and background color for social login button.
> Tweak- Change twitter icon and background color for social login button.

- includes/class-ur-ajax.php
- includes/frontend/class-ur-frontend-form-handler.php
- includes/validation/class-ur-form-validation.php
Previously repeater field values were not being stored in the database due to some code conflicts. This PR fixes this issue.
1. Switch to this branch.
2. In a form, add repeater fields.
3. Check if the repeater fields values are being stored correctly.
> Fix - Repeater fields values not being saved
> UR-2495 Fix - Repeater fields values not being saved

- modules/membership/includes/AJAX.php
- modules/membership/includes/Admin/Services/Stripe/StripeService.php
After membership's blocks introduction the subscription feature was not properly saving the stripe's product and price id.
This PR fixes the issue.
Closes # .
1. Create a subscription based membership for stripe
2. Register and verify if user is registered properly.
>  Fix -Sstripe subscription invalid request.
> UR-2533 Fix -Sstripe subscription invalid request.

- includes/class-ur-smart-tags.php
Previously, in customize my account section while using {{all_fields}} smart tag it was displaying the empty content. This PR fixes this issue.
Closes # .
1. Enable Customize My Account addon.
2. Go to URM > Global Settings > Customize My Account > Select any endpoint > use {{all_fields}} smart tag in Endpoint custom content section.
3. Click on save button
4. Now login as any user go to the endpoint where you have configured the smart tag and check whether it is displaying data accordingly or not.
> Fix - All Fields smart tag not working on customize my account pages.
> Fix - All Fields smart tag not working on customize my account pages.

- .github/sync-file-list.yml
- .github/workflows/sync.yml
- assets/css/user-registration.scss
Previously, when form is used in default themes, the form width in frontend took full width, stretching our form from left to right. This PR now maintains appropriate width of the form in all column layouts i.e. one column layout, two column layout and three column layout.
1. Switch to this branch.
2. Check form width in frontend in different layouts.
> Fix - Form design issue
> UR-2519 Fix - Form design issue

- modules/membership/includes/Templates/membership-registration-form.php
This PR adds the hook to modify the membership plan payment option label.
Closes # .
1. Use the hook **user_registration_membership_payment_gateway_selection_labels** to change the label of membership payment plan.
> Dev - Hook to modify user registration membership payment option label.
> Dev - Hook to modify user registration membership payment option label.

- CHANGELOG.txt
- assets/css/user-registration.scss
- includes/class-ur-smart-tags.php
- readme.txt
PR fixes to design issues reported in this issue.
https://themegrill.atlassian.net/browse/UR-2195
Closes # .
1. Checkout from woocommerce and verify if the fields CSS load properly.
>  Fix -  Woocommerce checkout design fix.
> Ur 320 Fix -  Woocommerce checkout design fix.

- includes/admin/class-ur-admin-export-users.php
While assigning the default value in Radio button, the default value was exported in the CSV instead of user' selected option. This PR fixes this issue.
Closes # .
1. Create a form using radio button
2. Assign default value to the Radio button.
3. Perform the User entry and export the users, check whether the accurate data is exported or not.
4. You can use this form for reference: 
[members-registration-form-2025-06-19_10_12_12.json](https://github.com/user-attachments/files/20819018/members-registration-form-2025-06-19_10_12_12.json)
> Fix - Default value exported instead of selected value in CSV.
> Fix - Default value exported instead of selected value in CSV.

- includes/admin/class-ur-admin-export-users.php
The profile picture data was not exported in the CSV file. This PR fixes this issue.
Closes # .
1. Create a form field using profile picture field.
2. Go to URM > Setting > Import/ Export.
3. Select the form with profile picture filed and the select the profile picture field.
4. Now check whether the CSV is containing profile picture data or not.
> Fix - Profile picture not exported in CSV file.
> Fix - Profile picture not exported in CSV file.

- assets/css/user-registration.scss
- assets/js/admin/login-settings.js
- templates/myaccount/form-login.php
Previously the hover effect in style customizer for login was not showing , this PR fixes it.
Closes # .
1. Enable style customizer
2. Go to login settings from all Settings > General > Login Options >Click the brush icon
3. Apply hover effect to the button and see if it works.
> Fix - Hidden hover CSS in login form submit button
> UR 2361 Fix - Hidden hover css in login form submit button

- includes/RestApi/controllers/version1/class-ur-plugin-status.php
- src/form-templates/components/PluginStatus.js
Closes # .
Check whether the issue reported for the jira ticket is replicated or not.
> Fix - unable to check plugin status issue.
> UR-2578 - Fix Unable to check plugin status issue.

- assets/css/user-registration-default-frontend.scss
- assets/css/user-registration-form-preview.scss
- assets/css/user-registration.scss
While applying the Theme Style on the form it was not overriding the design provided by plugin. This PR fixes this issue.
Closes # .
1. Create a form and open it in preview
2. Enable Apply theme styles toggle and check whether the theme style is overriding the form component styling in embedded page.
> Ur 2817 Fix - Theme style not overrridding the plugin design styles

- assets/css/my-account-layout.scss
Closes # .
1. Add {{all_fields}} smart tag to any my account page.
2. Notice that the table entries will align to its parent container.
> Fix - Alignment for {{all_fields}} smart tag on my account page.
> Ur 2577 design issue all fields smart tag

- modules/content-restriction/class-urcr-frontend.php
While using content restriction on elementor's section it was not working. This PR fixes this issue.
Closes # .
1. Use URM and Elementor free
2. Create a page using Elementor and add the section in that page.
3. Go to Section>Additional Settings > Enable Restrict this section
4. Add the different resetriction rules from URM>Settings>Content Restriction.
5. Check whether the content restriction is working as expected or not.
> Fix - Partial restriction on section of elementor.
> Ur 2845 Fix - Partial restriction on section of elementor

- assets/css/settings.scss
- includes/admin/class-ur-admin-settings.php
- includes/admin/settings/class-ur-settings-email.php
---
This PR updates the label and improves the visual design of Smart Tags links by making them appear more like external URLs.
Closes # .
---
1. Navigate to **URM > Settings > Email > To Admin / To User**.
2. Inspect the design of Smart Tags.
3. Confirm that the updated styles now adheres to the suggestion made in the ticket comment [here](https://themegrill.atlassian.net/browse/UR-2763).
4. Confirm that the label is updated to "Smart Tags Reference".
---
---
---
> Tweak - Update smart tags link label and design in email settings.
> UR-2763 Tweak - Improve smart tags link label and design in email settings.

- assets/js/admin/settings.js
- modules/membership/includes/AJAX.php
- modules/membership/includes/Admin/Services/MembershipService.php
This PR fixes the design issue in membership settings when selecting a page.
Closes # .
1. Go to GlobalSettings > Membership
2. Select any other pages, and see if the design glitch appears.
> Fix - Fixed design glitch in membership settings.
> UR-2716 - Fix - Fixed design glitch in membership settings.

- assets/js/frontend/my-account.js
- templates/myaccount/form-edit-profile.php
---
Improves the profile picture/avatar upload experience:
- Button text dynamically changes depending on image state.
- **"Upload Picture"** when no image is present.
- **"Change"** when a profile picture is already uploaded.
- Clicking "Change" removes the current image and triggers the upload process again.
Closes # .
---
1. Go to the **My Account > Profile Detail**.
2. Upload a profile picture and confirm button label updates to **"Change"**.
3. Click **"Change"**, verify current picture is removed and upload dialog reopens.
4. Try uploading a new picture and confirm behavior.
---
---
---
> Enhance - Improve profile picture upload UX.
> UR-2714 Enhance - Improve profile picture upload UX.

- src/dashboard/components/Header/Header.js
This PR changes the order of upgrade to pro link and current version in URM dashboard navigation bar.
Closes # .
1. Go to URM > Dashboard
2. Check the order of upgrade to pro link and current version in navigation bar
3. The sequence must be Upgrade to pro link > Version > Changelog.
> Tweak - Sequence of upgrade and changelog in navigation bar.
> UR-2904 Tweak - Sequence of upgrade and changelog in navigation bar

- src/dashboard/screens/Dashboard/Dashboard.js
- src/welcome/components/App.js
This PR adds the classname consistency for the welcome page wizard button and the URM > Dashboard button classname.
Closes # .
1. Check the button type and color for welcome page wizard and on the URM dashboard button.
> Tweak - Classname consistency for all buttons.
> UR-2905 Tweak - Classname consistency for all buttons

- modules/membership/includes/Admin/Membership/Membership.php
Closes # .
1. Enable Frontend Listing
2. See if the design itself is not broken anywhere.
> Fix -  Frontend listing design issue for frontend and admin settings
> UR-2566 Fix - Frontend listing design issue for frontend and admin settings

- modules/membership/includes/Admin/Repositories/MembersRepository.php
Fix for reported security vulnerability by Wordfence in MembersListTable.
Closes # .
1. Follow the instructions in this [ticket](https://themegrill.atlassian.net/browse/UR-2923)
>  Security - Updated sql prepare for members list table query.
> UR - 2923  Security - Updated sql prepare for members list table query.

- assets/js/admin/admin.js
- includes/RestApi/controllers/version1/class-ur-getting-started.php
- includes/admin/class-ur-admin-welcome.php
- includes/admin/notifications/class-ur-admin-notices.php
- includes/admin/views/html-admin-page-status.php
- includes/functions-ur-core.php
- languages/user-registration.pot
- src/welcome/components/App.js
This PR introduces the ability to **re-run the Setup Wizard** from **User Registration > Tools > Setup Wizard**.
Previously, the setup wizard was only accessible on initial plugin activation. With this enhancement, users can now re-initiate the setup wizard at any time from the Tools tab, allowing easier reconfiguration and onboarding.
1. Navigate to **User Registration > Tools > Setup Wizard** in the WP admin dashboard.
2. Click the "Setup Wizard" button.
3. Confirm that the setup wizard runs properly with updated settings.
4. Make sure the admin notice is displayed to continue setup wizard if setup wizard was not completed properly.
5. Complete the wizard and verify updated settings are saved.
> Enhancement - Make Setup Wizard available from **URM > Tools > Setup Wizard** screen.
> UR-2815 Enhancement - Make setup wizard avaialble for re-run from URM > Tools > Setup Wizard

- assets/js/frontend/user-registration-form-validator.js
The required field validation for WooCommerce on both Single and multi part form was not working. This PR fixes this issue.
Closes # .
1. Create both forms single and multi part using the WooCommerce Fields
2. Make those fields required fields and check whether the form field validation is working as expected or not.
> Fix - WooCommerce required fields validation not working.
> Ur 2824 Fix - WooCommerce required fields validation not working

- assets/js/modules/membership/frontend/user-registration-membership-frontend.js
- includes/Functions/CoreFunctions.php
- modules/membership/includes/Frontend/Frontend.php
While adding the custom payment currency and making the position right then this was not working as expected. This PR fixes this issue.
Closes # .
1. Add the code snippet in functions.php from [Jira description](https://themegrill.atlassian.net/browse/UR-3060)
2. Check if the position of currency is currency_symbol value or value currency_symbol.
> Fix - Currency position not working in payment
> UR-3060 Fix - Currency position not working in payment

- assets/js/modules/membership/frontend/user-registration-membership-frontend.js
- modules/membership/includes/Frontend/Frontend.php
- modules/membership/includes/Templates/membership-registration-form.php
This PR adds the option to select stripe as a default payment option in Membership registration through filter **user_registration_membership_default_payment_gateway**
Closes # .
1. Use filter **user_registration_membership_default_payment_gateway** to define the default payment option.
2. Load form with membership registration, select membership option with stripe, bank, free or any other options
3. Check if the Stripe is selected as the default payment option or not.
> Dev - Select stripe as the default gateway in membership registration.
> UR-3039 Dev - Select stripe as the default gateway in membership registration

- includes/functions-ur-template.php
- user-registration.php
This PR refactors the Checkbox field HTML structure for better readability as in the TranslatePress translation '/' was causing the issue while displaying the selected option.
Closes # .
1. Create form using checkbox field
2. Fill up and submit the form
3. After form submission check the profile detail in My Account
4. Check if the data are displaying accurately.
5. Optionally, you can test it using TranslatePress translation plugin while submitting form.
> Refactor - Input field HTML for better readability.
> UR-3028 Refactor - Input field HTML for better readability

- includes/admin/settings/class-ur-users-list-table.php
In the users table there was limitation in search option it would search only on email, name and fullname. This PR allows to search data from any fields.
Closes # .
1. Create a form using as much as form field available or you can also use these fields in the existing forms.
2. Perform the entry.
3. Now check the user search from any field data as you want.
**Note: To search the users according to country field please use the country code as it stores data in that form**
> Enhance - Search filter in users table search.
> UR-2620 Enhance - Search filter in users table search

- assets/js/modules/membership/admin/user-registration-membership-admin.js
- modules/membership/includes/Admin/Services/MembershipService.php
Previously only the toggle for the PG's checked for the incomplete PG settings,
This PR adds a backend validation for the upgrade membership. 
Closes # .
1. Recreate using the steps suggested in this ticket.
2. https://themegrill.atlassian.net/browse/UR-2827
> Fix - Adeed backend validation for pg gateways.
> UR-2827 Fix - Adeed backend validation for pg gateways.
